// Code generated by tools/compiler/compiler.go DO NOT EDIT.

// Copyright Semantic STEP Technology GmbH, Germany & DCT Co., Ltd. Tianjin, China

package eed

import (
	"reflect"
	"git.semanticstep.net/x/sst/sst"
)

type pkg struct{ sst.ElementInfo }

var EEDVocabulary = sst.Vocabulary{BaseIRI: "http://ontology.semanticstep.net/eed"}

var (
	PKG = sst.ElementPkg(pkg{})
	_   = PKG
)

// Definitions of eed.BidirectionalMasterPort

type IsBidirectionalMasterPort interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23BidirectionalMasterPort()
}

type KindBidirectionalMasterPort interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23BidirectionalMasterPort()
}

type bidirectionalMasterPortI struct{ sst.ElementInfo }

func (bidirectionalMasterPortI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23BidirectionalMasterPort()   {}
func (bidirectionalMasterPortI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23BidirectionalMasterPort() {}
func (bidirectionalMasterPortI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23MasterPort()              {}
func (bidirectionalMasterPortI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23Individual()              {}
func (bidirectionalMasterPortI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23SpaceTimeIndividual()     {}
func (bidirectionalMasterPortI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()          {}

var bidirectionalMasterPortKindInterface reflect.Type

var BidirectionalMasterPort = bidirectionalMasterPortI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: EEDVocabulary, Name: "BidirectionalMasterPort"},
	ASubtypeOf:        []sst.ElementInformer{MasterPort},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
	AMainClassSupersedure: map[sst.Element]struct{}{MasterPort.Element: {}},
}}

// Definitions of eed.FunctionalDefinition

type IsFunctionalDefinition interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalDefinition()
}

type KindFunctionalDefinition interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalDefinition()
}

type functionalDefinitionI struct{ sst.ElementInfo }

func (functionalDefinitionI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalDefinition()   {}
func (functionalDefinitionI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalDefinition() {}
func (functionalDefinitionI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23Individual()           {}
func (functionalDefinitionI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23SpaceTimeIndividual()  {}
func (functionalDefinitionI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()       {}

var functionalDefinitionKindInterface reflect.Type

var FunctionalDefinition = functionalDefinitionI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: EEDVocabulary, Name: "FunctionalDefinition"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
	AMainClassSupersedure: map[sst.Element]struct{}{},
}}

// Definitions of eed.FunctionalDefinitionElement

type IsFunctionalDefinitionElement interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalDefinitionElement()
}

type KindFunctionalDefinitionElement interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalDefinitionElement()
}

type functionalDefinitionElementI struct{ sst.ElementInfo }

func (functionalDefinitionElementI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalDefinitionElement()   {}
func (functionalDefinitionElementI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalDefinitionElement() {}
func (functionalDefinitionElementI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23ArrangedIndividual()          {}
func (functionalDefinitionElementI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23Individual()                  {}
func (functionalDefinitionElementI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23SpaceTimeIndividual()         {}
func (functionalDefinitionElementI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fsso_23Aspect()                      {}
func (functionalDefinitionElementI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()              {}

var functionalDefinitionElementKindInterface reflect.Type

var FunctionalDefinitionElement = functionalDefinitionElementI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: EEDVocabulary, Name: "FunctionalDefinitionElement"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
	AMainClassSupersedure: map[sst.Element]struct{}{},
}}

// Definitions of eed.FunctionalDefinitionTerminal

type IsFunctionalDefinitionTerminal interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalDefinitionTerminal()
}

type KindFunctionalDefinitionTerminal interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalDefinitionTerminal()
}

type functionalDefinitionTerminalI struct{ sst.ElementInfo }

func (functionalDefinitionTerminalI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalDefinitionTerminal()   {}
func (functionalDefinitionTerminalI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalDefinitionElement()  {}
func (functionalDefinitionTerminalI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalDefinitionTerminal() {}
func (functionalDefinitionTerminalI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23ArrangedIndividual()           {}
func (functionalDefinitionTerminalI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23Individual()                   {}
func (functionalDefinitionTerminalI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23SpaceTimeIndividual()          {}
func (functionalDefinitionTerminalI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fsso_23Aspect()                       {}
func (functionalDefinitionTerminalI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()               {}

var functionalDefinitionTerminalKindInterface reflect.Type

var FunctionalDefinitionTerminal = functionalDefinitionTerminalI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: EEDVocabulary, Name: "FunctionalDefinitionTerminal"},
	ASubtypeOf:        []sst.ElementInformer{FunctionalDefinitionElement},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
	AMainClassSupersedure: map[sst.Element]struct{}{FunctionalDefinitionElement.Element: {}},
}}

// Definitions of eed.FunctionalInternallNode

type IsFunctionalInternallNode interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalInternallNode()
}

type KindFunctionalInternallNode interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalInternallNode()
}

type functionalInternallNodeI struct{ sst.ElementInfo }

func (functionalInternallNodeI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalInternallNode()       {}
func (functionalInternallNodeI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalDefinitionElement() {}
func (functionalInternallNodeI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalInternallNode()     {}
func (functionalInternallNodeI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalNode()              {}
func (functionalInternallNodeI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23ArrangedIndividual()          {}
func (functionalInternallNodeI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23Individual()                  {}
func (functionalInternallNodeI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23SpaceTimeIndividual()         {}
func (functionalInternallNodeI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fsso_23Aspect()                      {}
func (functionalInternallNodeI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()              {}

var functionalInternallNodeKindInterface reflect.Type

var FunctionalInternallNode = functionalInternallNodeI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: EEDVocabulary, Name: "FunctionalInternallNode"},
	ASubtypeOf:        []sst.ElementInformer{FunctionalNode},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
	AMainClassSupersedure: map[sst.Element]struct{}{FunctionalDefinitionElement.Element: {}},
}}

// Definitions of eed.FunctionalNetworkDefinition

type IsFunctionalNetworkDefinition interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalNetworkDefinition()
}

type KindFunctionalNetworkDefinition interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalNetworkDefinition()
}

type functionalNetworkDefinitionI struct{ sst.ElementInfo }

func (functionalNetworkDefinitionI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalNetworkDefinition()   {}
func (functionalNetworkDefinitionI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalDefinitionElement() {}
func (functionalNetworkDefinitionI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalNetworkDefinition() {}
func (functionalNetworkDefinitionI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23ArrangedIndividual()          {}
func (functionalNetworkDefinitionI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23Individual()                  {}
func (functionalNetworkDefinitionI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23SpaceTimeIndividual()         {}
func (functionalNetworkDefinitionI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fsso_23Aspect()                      {}
func (functionalNetworkDefinitionI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()              {}

var functionalNetworkDefinitionKindInterface reflect.Type

var FunctionalNetworkDefinition = functionalNetworkDefinitionI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: EEDVocabulary, Name: "FunctionalNetworkDefinition"},
	ASubtypeOf:        []sst.ElementInformer{FunctionalDefinitionElement},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
	AMainClassSupersedure: map[sst.Element]struct{}{FunctionalDefinitionElement.Element: {}},
}}

// Definitions of eed.FunctionalNode

type IsFunctionalNode interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalNode()
}

type KindFunctionalNode interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalNode()
}

type functionalNodeI struct{ sst.ElementInfo }

func (functionalNodeI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalNode()                {}
func (functionalNodeI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalDefinitionElement() {}
func (functionalNodeI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalNode()              {}
func (functionalNodeI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23ArrangedIndividual()          {}
func (functionalNodeI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23Individual()                  {}
func (functionalNodeI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23SpaceTimeIndividual()         {}
func (functionalNodeI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fsso_23Aspect()                      {}
func (functionalNodeI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()              {}

var functionalNodeKindInterface reflect.Type

var FunctionalNode = functionalNodeI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: EEDVocabulary, Name: "FunctionalNode"},
	ASubtypeOf:        []sst.ElementInformer{FunctionalDefinitionElement},

	AClass: true, AnOptionClass: false, AnAbstractClass: true, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of eed.FunctionalOccurrence

type IsFunctionalOccurrence interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalOccurrence()
}

type KindFunctionalOccurrence interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalOccurrence()
}

type functionalOccurrenceI struct{ sst.ElementInfo }

func (functionalOccurrenceI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalOccurrence()   {}
func (functionalOccurrenceI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalOccurrence() {}
func (functionalOccurrenceI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23Individual()           {}
func (functionalOccurrenceI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23SpaceTimeIndividual()  {}
func (functionalOccurrenceI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()       {}

var functionalOccurrenceKindInterface reflect.Type

var FunctionalOccurrence = functionalOccurrenceI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: EEDVocabulary, Name: "FunctionalOccurrence"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
	AMainClassSupersedure: map[sst.Element]struct{}{},
}}

// Definitions of eed.FunctionalOccurrenceTerminal

type IsFunctionalOccurrenceTerminal interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalOccurrenceTerminal()
}

type KindFunctionalOccurrenceTerminal interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalOccurrenceTerminal()
}

type functionalOccurrenceTerminalI struct{ sst.ElementInfo }

func (functionalOccurrenceTerminalI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalOccurrenceTerminal()   {}
func (functionalOccurrenceTerminalI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalOccurrenceTerminal() {}
func (functionalOccurrenceTerminalI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23ArrangedIndividual()           {}
func (functionalOccurrenceTerminalI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23Individual()                   {}
func (functionalOccurrenceTerminalI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23SpaceTimeIndividual()          {}
func (functionalOccurrenceTerminalI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fsso_23Aspect()                       {}
func (functionalOccurrenceTerminalI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()               {}

var functionalOccurrenceTerminalKindInterface reflect.Type

var FunctionalOccurrenceTerminal = functionalOccurrenceTerminalI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: EEDVocabulary, Name: "FunctionalOccurrenceTerminal"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
	AMainClassSupersedure: map[sst.Element]struct{}{},
}}

// Definitions of eed.FunctionalTerminalNode

type IsFunctionalTerminalNode interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalTerminalNode()
}

type KindFunctionalTerminalNode interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalTerminalNode()
}

type functionalTerminalNodeI struct{ sst.ElementInfo }

func (functionalTerminalNodeI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalTerminalNode()         {}
func (functionalTerminalNodeI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalDefinitionElement()  {}
func (functionalTerminalNodeI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalDefinitionTerminal() {}
func (functionalTerminalNodeI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalNode()               {}
func (functionalTerminalNodeI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23FunctionalTerminalNode()       {}
func (functionalTerminalNodeI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23ArrangedIndividual()           {}
func (functionalTerminalNodeI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23Individual()                   {}
func (functionalTerminalNodeI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23SpaceTimeIndividual()          {}
func (functionalTerminalNodeI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fsso_23Aspect()                       {}
func (functionalTerminalNodeI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()               {}

var functionalTerminalNodeKindInterface reflect.Type

var FunctionalTerminalNode = functionalTerminalNodeI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: EEDVocabulary, Name: "FunctionalTerminalNode"},
	ASubtypeOf:        []sst.ElementInformer{FunctionalDefinitionTerminal, FunctionalNode},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
	AMainClassSupersedure: map[sst.Element]struct{}{FunctionalDefinitionElement.Element: {}, FunctionalDefinitionTerminal.Element: {}},
}}

// Definitions of eed.InputMasterPort

type IsInputMasterPort interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23InputMasterPort()
}

type KindInputMasterPort interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23InputMasterPort()
}

type inputMasterPortI struct{ sst.ElementInfo }

func (inputMasterPortI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23InputMasterPort()       {}
func (inputMasterPortI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23InputMasterPort()     {}
func (inputMasterPortI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23MasterPort()          {}
func (inputMasterPortI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23Individual()          {}
func (inputMasterPortI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23SpaceTimeIndividual() {}
func (inputMasterPortI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()      {}

var inputMasterPortKindInterface reflect.Type

var InputMasterPort = inputMasterPortI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: EEDVocabulary, Name: "InputMasterPort"},
	ASubtypeOf:        []sst.ElementInformer{MasterPort},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
	AMainClassSupersedure: map[sst.Element]struct{}{MasterPort.Element: {}},
}}

// Definitions of eed.LayerShapeRepresentation

type IsLayerShapeRepresentation interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23LayerShapeRepresentation()
}

type KindLayerShapeRepresentation interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23LayerShapeRepresentation()
}

type layerShapeRepresentationI struct{ sst.ElementInfo }

func (layerShapeRepresentationI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23LayerShapeRepresentation()   {}
func (layerShapeRepresentationI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23LayerShapeRepresentation() {}
func (layerShapeRepresentationI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23Individual()               {}
func (layerShapeRepresentationI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23SpaceTimeIndividual()      {}
func (layerShapeRepresentationI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Frep_23Representation()           {}
func (layerShapeRepresentationI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Frep_23ShapeRepresentation()      {}
func (layerShapeRepresentationI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()           {}

var layerShapeRepresentationKindInterface reflect.Type

var LayerShapeRepresentation = layerShapeRepresentationI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: EEDVocabulary, Name: "LayerShapeRepresentation"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of eed.MasterPort

type IsMasterPort interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23MasterPort()
}

type KindMasterPort interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23MasterPort()
}

type masterPortI struct{ sst.ElementInfo }

func (masterPortI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23MasterPort()            {}
func (masterPortI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23MasterPort()          {}
func (masterPortI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23Individual()          {}
func (masterPortI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23SpaceTimeIndividual() {}
func (masterPortI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()      {}

var masterPortKindInterface reflect.Type

var MasterPort = masterPortI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: EEDVocabulary, Name: "MasterPort"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
	AMainClassSupersedure: map[sst.Element]struct{}{},
}}

// Definitions of eed.MasterPortBundle

type IsMasterPortBundle interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23MasterPortBundle()
}

type KindMasterPortBundle interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23MasterPortBundle()
}

type masterPortBundleI struct{ sst.ElementInfo }

func (masterPortBundleI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23MasterPortBundle()      {}
func (masterPortBundleI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23MasterPortBundle()    {}
func (masterPortBundleI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23Individual()          {}
func (masterPortBundleI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23SpaceTimeIndividual() {}
func (masterPortBundleI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()      {}

var masterPortBundleKindInterface reflect.Type

var MasterPortBundle = masterPortBundleI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: EEDVocabulary, Name: "MasterPortBundle"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
	AMainClassSupersedure: map[sst.Element]struct{}{},
}}

// Definitions of eed.MountingTechnology

type IsMountingTechnology interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23MountingTechnology()
}

type KindMountingTechnology interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23MountingTechnology()
}

type mountingTechnologyI struct{ sst.ElementInfo }

func (mountingTechnologyI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23MountingTechnology()   {}
func (mountingTechnologyI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23MountingTechnology() {}
func (mountingTechnologyI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23OptionClass()     {}
func (mountingTechnologyI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()     {}

var mountingTechnologyKindInterface reflect.Type

var MountingTechnology = mountingTechnologyI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: EEDVocabulary, Name: "MountingTechnology"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of eed.MountingTechnology_surface

type IsMountingTechnology_surface interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23MountingTechnology_5Fsurface()
}

type KindMountingTechnology_surface interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23MountingTechnology_5Fsurface()
}

type mountingTechnology_SurfaceI struct{ sst.ElementInfo }

func (mountingTechnology_SurfaceI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23MountingTechnology_5Fsurface()   {}
func (mountingTechnology_SurfaceI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23MountingTechnology_5Fsurface() {}
func (mountingTechnology_SurfaceI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()               {}
func (mountingTechnology_SurfaceI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2002_2F07_2Fowl_23Thing()                           {}

var mountingTechnology_SurfaceKindInterface reflect.Type

var MountingTechnology_surface = mountingTechnology_SurfaceI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: EEDVocabulary, Name: "MountingTechnology_surface"},

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: true,
}}

// Definitions of eed.MountingTechnology_throughHole

type IsMountingTechnology_throughHole interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23MountingTechnology_5FthroughHole()
}

type KindMountingTechnology_throughHole interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23MountingTechnology_5FthroughHole()
}

type mountingTechnology_ThroughHoleI struct{ sst.ElementInfo }

func (mountingTechnology_ThroughHoleI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23MountingTechnology_5FthroughHole()   {}
func (mountingTechnology_ThroughHoleI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23MountingTechnology_5FthroughHole() {}
func (mountingTechnology_ThroughHoleI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()                   {}
func (mountingTechnology_ThroughHoleI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2002_2F07_2Fowl_23Thing()                               {}

var mountingTechnology_ThroughHoleKindInterface reflect.Type

var MountingTechnology_throughHole = mountingTechnology_ThroughHoleI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: EEDVocabulary, Name: "MountingTechnology_throughHole"},

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: true,
}}

// Definitions of eed.OutputMasterPort

type IsOutputMasterPort interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23OutputMasterPort()
}

type KindOutputMasterPort interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23OutputMasterPort()
}

type outputMasterPortI struct{ sst.ElementInfo }

func (outputMasterPortI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23OutputMasterPort()      {}
func (outputMasterPortI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23MasterPort()          {}
func (outputMasterPortI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23OutputMasterPort()    {}
func (outputMasterPortI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23Individual()          {}
func (outputMasterPortI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23SpaceTimeIndividual() {}
func (outputMasterPortI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()      {}

var outputMasterPortKindInterface reflect.Type

var OutputMasterPort = outputMasterPortI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: EEDVocabulary, Name: "OutputMasterPort"},
	ASubtypeOf:        []sst.ElementInformer{MasterPort},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
	AMainClassSupersedure: map[sst.Element]struct{}{MasterPort.Element: {}},
}}

// Definitions of eed.Package

type IsPackage interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23Package()
}

type KindPackage interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23Package()
}

type packageI struct{ sst.ElementInfo }

func (packageI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23Package()                  {}
func (packageI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23Package()                {}
func (packageI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23Template()               {}
func (packageI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23Individual()             {}
func (packageI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23SpaceTimeIndividual()    {}
func (packageI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fsso_23ShapeFeatureDefinition() {}
func (packageI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()         {}

var packageKindInterface reflect.Type

var Package = packageI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: EEDVocabulary, Name: "Package"},
	ASubtypeOf:        []sst.ElementInformer{Template},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
	AMainClassSupersedure: map[sst.Element]struct{}{Template.Element: {}},
}}

// Definitions of eed.PackageFeature

type IsPackageFeature interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23PackageFeature()
}

type KindPackageFeature interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23PackageFeature()
}

type packageFeatureI struct{ sst.ElementInfo }

func (packageFeatureI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23PackageFeature()                  {}
func (packageFeatureI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23PackageFeature()                {}
func (packageFeatureI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23ArrangedIndividual()            {}
func (packageFeatureI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23Individual()                    {}
func (packageFeatureI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23SpaceTimeIndividual()           {}
func (packageFeatureI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fsso_23Aspect()                        {}
func (packageFeatureI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fsso_23ShapeElement()                  {}
func (packageFeatureI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fsso_23ShapeFeatureDefinitionElement() {}
func (packageFeatureI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()                {}

var packageFeatureKindInterface reflect.Type

var PackageFeature = packageFeatureI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: EEDVocabulary, Name: "PackageFeature"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
	AMainClassSupersedure: map[sst.Element]struct{}{},
}}

// Definitions of eed.PackageTerminal

type IsPackageTerminal interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23PackageTerminal()
}

type KindPackageTerminal interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23PackageTerminal()
}

type packageTerminalI struct{ sst.ElementInfo }

func (packageTerminalI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23PackageTerminal()                 {}
func (packageTerminalI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23PackageFeature()                {}
func (packageTerminalI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23PackageTerminal()               {}
func (packageTerminalI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23ArrangedIndividual()            {}
func (packageTerminalI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23Individual()                    {}
func (packageTerminalI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23SpaceTimeIndividual()           {}
func (packageTerminalI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fsso_23Aspect()                        {}
func (packageTerminalI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fsso_23ShapeElement()                  {}
func (packageTerminalI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fsso_23ShapeFeatureDefinitionElement() {}
func (packageTerminalI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()                {}

var packageTerminalKindInterface reflect.Type

var PackageTerminal = packageTerminalI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: EEDVocabulary, Name: "PackageTerminal"},
	ASubtypeOf:        []sst.ElementInformer{PackageFeature},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
	AMainClassSupersedure: map[sst.Element]struct{}{PackageFeature.Element: {}},
}}

// Definitions of eed.PackageTerminalTemplate

type IsPackageTerminalTemplate interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23PackageTerminalTemplate()
}

type KindPackageTerminalTemplate interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23PackageTerminalTemplate()
}

type packageTerminalTemplateI struct{ sst.ElementInfo }

func (packageTerminalTemplateI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23PackageTerminalTemplate()   {}
func (packageTerminalTemplateI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23PackageTerminalTemplate() {}
func (packageTerminalTemplateI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23Individual()              {}
func (packageTerminalTemplateI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23SpaceTimeIndividual()     {}
func (packageTerminalTemplateI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fsso_23ShapeFeatureDefinition()  {}
func (packageTerminalTemplateI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()          {}

var packageTerminalTemplateKindInterface reflect.Type

var PackageTerminalTemplate = packageTerminalTemplateI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: EEDVocabulary, Name: "PackageTerminalTemplate"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
	AMainClassSupersedure: map[sst.Element]struct{}{},
}}

// Definitions of eed.PackageType

type IsPackageType interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23PackageType()
}

type KindPackageType interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23PackageType()
}

type packageTypeI struct{ sst.ElementInfo }

func (packageTypeI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23PackageType()      {}
func (packageTypeI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23PackageType()    {}
func (packageTypeI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23OptionClass() {}
func (packageTypeI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource() {}

var packageTypeKindInterface reflect.Type

var PackageType = packageTypeI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: EEDVocabulary, Name: "PackageType"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of eed.PackageType_BGA

type IsPackageType_BGA interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23PackageType_5FBGA()
}

type KindPackageType_BGA interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23PackageType_5FBGA()
}

type packageType_BGAI struct{ sst.ElementInfo }

func (packageType_BGAI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23PackageType_5FBGA()              {}
func (packageType_BGAI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23MountingTechnology_5Fsurface() {}
func (packageType_BGAI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23PackageType_5FBGA()            {}
func (packageType_BGAI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()               {}

var packageType_BGAKindInterface reflect.Type

var PackageType_BGA = packageType_BGAI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: EEDVocabulary, Name: "PackageType_BGA"},
	ASubtypeOf:        []sst.ElementInformer{MountingTechnology_surface},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of eed.PackageType_DIP

type IsPackageType_DIP interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23PackageType_5FDIP()
}

type KindPackageType_DIP interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23PackageType_5FDIP()
}

type packageType_DIPI struct{ sst.ElementInfo }

func (packageType_DIPI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23PackageType_5FDIP()                  {}
func (packageType_DIPI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23MountingTechnology_5FthroughHole() {}
func (packageType_DIPI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23PackageType_5FDIP()                {}
func (packageType_DIPI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()                   {}

var packageType_DIPKindInterface reflect.Type

var PackageType_DIP = packageType_DIPI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: EEDVocabulary, Name: "PackageType_DIP"},
	ASubtypeOf:        []sst.ElementInformer{MountingTechnology_throughHole},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of eed.PackageType_SIP

type IsPackageType_SIP interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23PackageType_5FSIP()
}

type KindPackageType_SIP interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23PackageType_5FSIP()
}

type packageType_SIPI struct{ sst.ElementInfo }

func (packageType_SIPI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23PackageType_5FSIP()                  {}
func (packageType_SIPI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23MountingTechnology_5FthroughHole() {}
func (packageType_SIPI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23PackageType_5FSIP()                {}
func (packageType_SIPI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()                   {}

var packageType_SIPKindInterface reflect.Type

var PackageType_SIP = packageType_SIPI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: EEDVocabulary, Name: "PackageType_SIP"},
	ASubtypeOf:        []sst.ElementInformer{MountingTechnology_throughHole},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of eed.Template

type IsTemplate interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23Template()
}

type KindTemplate interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23Template()
}

type templateI struct{ sst.ElementInfo }

func (templateI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23Template()                 {}
func (templateI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23Template()               {}
func (templateI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23Individual()             {}
func (templateI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23SpaceTimeIndividual()    {}
func (templateI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fsso_23ShapeFeatureDefinition() {}
func (templateI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()         {}

var templateKindInterface reflect.Type

var Template = templateI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: EEDVocabulary, Name: "Template"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
	AMainClassSupersedure: map[sst.Element]struct{}{},
}}

// Definitions of eed.TemplateContactFeature

type IsTemplateContactFeature interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23TemplateContactFeature()
}

type KindTemplateContactFeature interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23TemplateContactFeature()
}

type templateContactFeatureI struct{ sst.ElementInfo }

func (templateContactFeatureI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23TemplateContactFeature()          {}
func (templateContactFeatureI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23TemplateContactFeature()        {}
func (templateContactFeatureI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23TemplateFeature()               {}
func (templateContactFeatureI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23ArrangedIndividual()            {}
func (templateContactFeatureI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23Individual()                    {}
func (templateContactFeatureI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23SpaceTimeIndividual()           {}
func (templateContactFeatureI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fsso_23Aspect()                        {}
func (templateContactFeatureI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fsso_23ShapeElement()                  {}
func (templateContactFeatureI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fsso_23ShapeFeatureDefinitionElement() {}
func (templateContactFeatureI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()                {}

var templateContactFeatureKindInterface reflect.Type

var TemplateContactFeature = templateContactFeatureI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: EEDVocabulary, Name: "TemplateContactFeature"},
	ASubtypeOf:        []sst.ElementInformer{TemplateFeature},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
	AMainClassSupersedure: map[sst.Element]struct{}{TemplateFeature.Element: {}},
}}

// Definitions of eed.TemplateFeature

type IsTemplateFeature interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23TemplateFeature()
}

type KindTemplateFeature interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23TemplateFeature()
}

type templateFeatureI struct{ sst.ElementInfo }

func (templateFeatureI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23TemplateFeature()                 {}
func (templateFeatureI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23TemplateFeature()               {}
func (templateFeatureI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23ArrangedIndividual()            {}
func (templateFeatureI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23Individual()                    {}
func (templateFeatureI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23SpaceTimeIndividual()           {}
func (templateFeatureI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fsso_23Aspect()                        {}
func (templateFeatureI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fsso_23ShapeElement()                  {}
func (templateFeatureI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fsso_23ShapeFeatureDefinitionElement() {}
func (templateFeatureI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()                {}

var templateFeatureKindInterface reflect.Type

var TemplateFeature = templateFeatureI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: EEDVocabulary, Name: "TemplateFeature"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
	AMainClassSupersedure: map[sst.Element]struct{}{},
}}

// Definitions of eed.TemplateTerminal

type IsTemplateTerminal interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23TemplateTerminal()
}

type KindTemplateTerminal interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23TemplateTerminal()
}

type templateTerminalI struct{ sst.ElementInfo }

func (templateTerminalI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23TemplateTerminal()                {}
func (templateTerminalI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23TemplateContactFeature()        {}
func (templateTerminalI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23TemplateFeature()               {}
func (templateTerminalI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23TemplateTerminal()              {}
func (templateTerminalI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23ArrangedIndividual()            {}
func (templateTerminalI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23Individual()                    {}
func (templateTerminalI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23SpaceTimeIndividual()           {}
func (templateTerminalI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fsso_23Aspect()                        {}
func (templateTerminalI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fsso_23ShapeElement()                  {}
func (templateTerminalI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fsso_23ShapeFeatureDefinitionElement() {}
func (templateTerminalI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()                {}

var templateTerminalKindInterface reflect.Type

var TemplateTerminal = templateTerminalI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: EEDVocabulary, Name: "TemplateTerminal"},
	ASubtypeOf:        []sst.ElementInformer{TemplateContactFeature},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
	AMainClassSupersedure: map[sst.Element]struct{}{TemplateContactFeature.Element: {}, TemplateFeature.Element: {}},
}}

// Definitions of eed.connectedTerminal

type IsConnectedTerminal interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23connectedTerminal()
}

type KindConnectedTerminal interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23connectedTerminal()
}

type connectedTerminalI struct{ sst.ElementInfo }

func (connectedTerminalI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23connectedTerminal()     {}
func (connectedTerminalI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23connectedTerminal()   {}
func (connectedTerminalI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23connectedTo()         {}
func (connectedTerminalI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23directlyConnectedTo() {}
func (connectedTerminalI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()      {}

var connectedTerminalKindInterface reflect.Type

var ConnectedTerminal = connectedTerminalI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: EEDVocabulary, Name: "connectedTerminal"},
	ARange:            FunctionalOccurrenceTerminal,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: true, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of eed.ipcId

type IsIpcID interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23ipcId()
}

type KindIpcID interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23ipcId()
}

type ipcIdI struct{ sst.ElementInfo }

func (ipcIdI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23ipcId()                     {}
func (ipcIdI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23ipcId()                   {}
func (ipcIdI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23identificationBy()        {}
func (ipcIdI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23identificationByLiteral() {}
func (ipcIdI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23representationByLiteral() {}
func (ipcIdI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fsso_23id()                      {}
func (ipcIdI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()          {}

var ipcIdKindInterface reflect.Type

var IpcID = ipcIdI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: EEDVocabulary, Name: "ipcId"},
	ADomain:           Package,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: true, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of eed.jedecId

type IsJedecID interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23jedecId()
}

type KindJedecID interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23jedecId()
}

type jedecIdI struct{ sst.ElementInfo }

func (jedecIdI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23jedecId()                   {}
func (jedecIdI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23jedecId()                 {}
func (jedecIdI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23identificationBy()        {}
func (jedecIdI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23identificationByLiteral() {}
func (jedecIdI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Flci_23representationByLiteral() {}
func (jedecIdI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fsso_23id()                      {}
func (jedecIdI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()          {}

var jedecIdKindInterface reflect.Type

var JedecID = jedecIdI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: EEDVocabulary, Name: "jedecId"},
	ADomain:           Package,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: true, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of eed.mapPartTerminalToFunctionalTerminal

type IsMapPartTerminalToFunctionalTerminal interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23mapPartTerminalToFunctionalTerminal()
}

type KindMapPartTerminalToFunctionalTerminal interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23mapPartTerminalToFunctionalTerminal()
}

type mapPartTerminalToFunctionalTerminalI struct{ sst.ElementInfo }

func (mapPartTerminalToFunctionalTerminalI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23mapPartTerminalToFunctionalTerminal()   {}
func (mapPartTerminalToFunctionalTerminalI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23mapPartTerminalToFunctionalTerminal() {}
func (mapPartTerminalToFunctionalTerminalI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()                      {}

var mapPartTerminalToFunctionalTerminalKindInterface reflect.Type

var MapPartTerminalToFunctionalTerminal = mapPartTerminalToFunctionalTerminalI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: EEDVocabulary, Name: "mapPartTerminalToFunctionalTerminal"},
	ARange:            FunctionalDefinitionTerminal,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: true, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of eed.mapPartTerminalToTemplateTerminal

type IsMapPartTerminalToTemplateTerminal interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23mapPartTerminalToTemplateTerminal()
}

type KindMapPartTerminalToTemplateTerminal interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23mapPartTerminalToTemplateTerminal()
}

type mapPartTerminalToTemplateTerminalI struct{ sst.ElementInfo }

func (mapPartTerminalToTemplateTerminalI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23mapPartTerminalToTemplateTerminal()   {}
func (mapPartTerminalToTemplateTerminalI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23mapPartTerminalToTemplateTerminal() {}
func (mapPartTerminalToTemplateTerminalI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()                    {}

var mapPartTerminalToTemplateTerminalKindInterface reflect.Type

var MapPartTerminalToTemplateTerminal = mapPartTerminalToTemplateTerminalI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: EEDVocabulary, Name: "mapPartTerminalToTemplateTerminal"},
	ARange:            TemplateTerminal,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: true, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of eed.mapPartToFunctional

type IsMapPartToFunctional interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23mapPartToFunctional()
}

type KindMapPartToFunctional interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23mapPartToFunctional()
}

type mapPartToFunctionalI struct{ sst.ElementInfo }

func (mapPartToFunctionalI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23mapPartToFunctional()   {}
func (mapPartToFunctionalI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23mapPartToFunctional() {}
func (mapPartToFunctionalI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()      {}

var mapPartToFunctionalKindInterface reflect.Type

var MapPartToFunctional = mapPartToFunctionalI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: EEDVocabulary, Name: "mapPartToFunctional"},
	ARange:            FunctionalDefinition,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: true, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of eed.mapPartToTemplate

type IsMapPartToTemplate interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23mapPartToTemplate()
}

type KindMapPartToTemplate interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23mapPartToTemplate()
}

type mapPartToTemplateI struct{ sst.ElementInfo }

func (mapPartToTemplateI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23mapPartToTemplate()   {}
func (mapPartToTemplateI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Feed_23mapPartToTemplate() {}
func (mapPartToTemplateI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()    {}

var mapPartToTemplateKindInterface reflect.Type

var MapPartToTemplate = mapPartToTemplateI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: EEDVocabulary, Name: "mapPartToTemplate"},
	ARange:            Template,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: true, 
	ADatatype: false, AnIndividual: false,
}}
