// Code generated by tools/compiler/compiler.go DO NOT EDIT.

// Copyright Semantic STEP Technology GmbH, Germany & DCT Co., Ltd. Tianjin, China

package skos

import (
	"reflect"
	"github.com/semanticstep/sst-core/sst"
	"github.com/semanticstep/sst-core/vocabularies/rdf"
	"github.com/semanticstep/sst-core/vocabularies/rdfs"
)

type pkg struct{ sst.ElementInfo }

var COREVocabulary = sst.Vocabulary{BaseIRI: "http://www.w3.org/2004/02/skos/core"}

var (
	PKG = sst.ElementPkg(pkg{})
	_   = PKG
)

// Definitions of core.Collection

type IsCollection interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23Collection()
}

type KindCollection interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23Collection()
}

type collectionI struct{ sst.ElementInfo }

func (collectionI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23Collection()   {}
func (collectionI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()  {}
func (collectionI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23Collection() {}

var collectionKindInterface reflect.Type

var Collection = collectionI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: COREVocabulary, Name: "Collection"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of core.Concept

type IsConcept interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23Concept()
}

type KindConcept interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23Concept()
}

type conceptI struct{ sst.ElementInfo }

func (conceptI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23Concept()     {}
func (conceptI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource() {}
func (conceptI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23Concept()   {}

var conceptKindInterface reflect.Type

var Concept = conceptI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: COREVocabulary, Name: "Concept"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of core.ConceptScheme

type IsConceptScheme interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23ConceptScheme()
}

type KindConceptScheme interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23ConceptScheme()
}

type conceptSchemeI struct{ sst.ElementInfo }

func (conceptSchemeI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23ConceptScheme()   {}
func (conceptSchemeI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()     {}
func (conceptSchemeI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23ConceptScheme() {}

var conceptSchemeKindInterface reflect.Type

var ConceptScheme = conceptSchemeI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: COREVocabulary, Name: "ConceptScheme"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of core.OrderedCollection

type IsOrderedCollection interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23OrderedCollection()
}

type KindOrderedCollection interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23OrderedCollection()
}

type orderedCollectionI struct{ sst.ElementInfo }

func (orderedCollectionI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23OrderedCollection()   {}
func (orderedCollectionI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()         {}
func (orderedCollectionI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23Collection()        {}
func (orderedCollectionI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23OrderedCollection() {}

var orderedCollectionKindInterface reflect.Type

var OrderedCollection = orderedCollectionI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: COREVocabulary, Name: "OrderedCollection"},
	ASubtypeOf:        []sst.ElementInformer{Collection},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of core.altLabel

type IsAltLabel interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23altLabel()
}

type KindAltLabel interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23altLabel()
}

type altLabelI struct{ sst.ElementInfo }

func (altLabelI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23altLabel()    {}
func (altLabelI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource() {}
func (altLabelI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23label()    {}
func (altLabelI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23altLabel()  {}

var altLabelKindInterface reflect.Type

var AltLabel = altLabelI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: COREVocabulary, Name: "altLabel"},
	ADomain:           rdfs.Resource,
	ARange:            rdfs.Literal,
	ASubPropertyOf:    rdfs.Label,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of core.broadMatch

type IsBroadMatch interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23broadMatch()
}

type KindBroadMatch interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23broadMatch()
}

type broadMatchI struct{ sst.ElementInfo }

func (broadMatchI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23broadMatch()          {}
func (broadMatchI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()         {}
func (broadMatchI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23broadMatch()        {}
func (broadMatchI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23broader()           {}
func (broadMatchI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23broaderTransitive() {}
func (broadMatchI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23mappingRelation()   {}
func (broadMatchI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23semanticRelation()  {}

var broadMatchKindInterface reflect.Type

var BroadMatch = broadMatchI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: COREVocabulary, Name: "broadMatch"},
	ADomain:           Concept,
	ARange:            Concept,
	ASubPropertyOf:    MappingRelation,
	AnInverseOf:       NarrowMatch,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: true, 
	ADatatype: false, AnIndividual: false,
}}

func (narrowMatchI) InverseOf() sst.ElementInformer { return BroadMatch }

// Definitions of core.broader

type IsBroader interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23broader()
}

type KindBroader interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23broader()
}

type broaderI struct{ sst.ElementInfo }

func (broaderI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23broader()             {}
func (broaderI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()         {}
func (broaderI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23broader()           {}
func (broaderI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23broaderTransitive() {}
func (broaderI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23semanticRelation()  {}

var broaderKindInterface reflect.Type

var Broader = broaderI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: COREVocabulary, Name: "broader"},
	ADomain:           Concept,
	ARange:            Concept,
	ASubPropertyOf:    BroaderTransitive,
	AnInverseOf:       Narrower,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: true, 
	ADatatype: false, AnIndividual: false,
}}

func (narrowerI) InverseOf() sst.ElementInformer { return Broader }

// Definitions of core.broaderTransitive

type IsBroaderTransitive interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23broaderTransitive()
}

type KindBroaderTransitive interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23broaderTransitive()
}

type broaderTransitiveI struct{ sst.ElementInfo }

func (broaderTransitiveI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23broaderTransitive()   {}
func (broaderTransitiveI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()         {}
func (broaderTransitiveI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23broaderTransitive() {}
func (broaderTransitiveI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23semanticRelation()  {}

var broaderTransitiveKindInterface reflect.Type

var BroaderTransitive = broaderTransitiveI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: COREVocabulary, Name: "broaderTransitive"},
	ADomain:           Concept,
	ARange:            Concept,
	ASubPropertyOf:    SemanticRelation,
	AnInverseOf:       NarrowerTransitive,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: true, 
	ADatatype: false, AnIndividual: false,
}}

func (narrowerTransitiveI) InverseOf() sst.ElementInformer { return BroaderTransitive }

// Definitions of core.changeNote

type IsChangeNote interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23changeNote()
}

type KindChangeNote interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23changeNote()
}

type changeNoteI struct{ sst.ElementInfo }

func (changeNoteI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23changeNote()   {}
func (changeNoteI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()  {}
func (changeNoteI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23changeNote() {}
func (changeNoteI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23note()       {}

var changeNoteKindInterface reflect.Type

var ChangeNote = changeNoteI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: COREVocabulary, Name: "changeNote"},
	ASubPropertyOf:    Note,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of core.closeMatch

type IsCloseMatch interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23closeMatch()
}

type KindCloseMatch interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23closeMatch()
}

type closeMatchI struct{ sst.ElementInfo }

func (closeMatchI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23closeMatch()         {}
func (closeMatchI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()        {}
func (closeMatchI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23closeMatch()       {}
func (closeMatchI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23mappingRelation()  {}
func (closeMatchI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23semanticRelation() {}

var closeMatchKindInterface reflect.Type

var CloseMatch = closeMatchI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: COREVocabulary, Name: "closeMatch"},
	ADomain:           Concept,
	ARange:            Concept,
	ASubPropertyOf:    MappingRelation,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: true, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of core.definition

type IsDefinition interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23definition()
}

type KindDefinition interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23definition()
}

type definitionI struct{ sst.ElementInfo }

func (definitionI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23definition()   {}
func (definitionI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()  {}
func (definitionI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23definition() {}
func (definitionI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23note()       {}

var definitionKindInterface reflect.Type

var Definition = definitionI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: COREVocabulary, Name: "definition"},
	ASubPropertyOf:    Note,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of core.editorialNote

type IsEditorialNote interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23editorialNote()
}

type KindEditorialNote interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23editorialNote()
}

type editorialNoteI struct{ sst.ElementInfo }

func (editorialNoteI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23editorialNote()   {}
func (editorialNoteI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()     {}
func (editorialNoteI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23editorialNote() {}
func (editorialNoteI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23note()          {}

var editorialNoteKindInterface reflect.Type

var EditorialNote = editorialNoteI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: COREVocabulary, Name: "editorialNote"},
	ASubPropertyOf:    Note,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of core.exactMatch

type IsExactMatch interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23exactMatch()
}

type KindExactMatch interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23exactMatch()
}

type exactMatchI struct{ sst.ElementInfo }

func (exactMatchI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23exactMatch()         {}
func (exactMatchI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()        {}
func (exactMatchI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23closeMatch()       {}
func (exactMatchI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23exactMatch()       {}
func (exactMatchI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23mappingRelation()  {}
func (exactMatchI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23semanticRelation() {}

var exactMatchKindInterface reflect.Type

var ExactMatch = exactMatchI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: COREVocabulary, Name: "exactMatch"},
	ADomain:           Concept,
	ARange:            Concept,
	ASubPropertyOf:    CloseMatch,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: true, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of core.example

type IsExample interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23example()
}

type KindExample interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23example()
}

type exampleI struct{ sst.ElementInfo }

func (exampleI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23example()     {}
func (exampleI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource() {}
func (exampleI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23example()   {}
func (exampleI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23note()      {}

var exampleKindInterface reflect.Type

var Example = exampleI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: COREVocabulary, Name: "example"},
	ASubPropertyOf:    Note,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of core.hasTopConcept

type IsHasTopConcept interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23hasTopConcept()
}

type KindHasTopConcept interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23hasTopConcept()
}

type hasTopConceptI struct{ sst.ElementInfo }

func (hasTopConceptI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23hasTopConcept()   {}
func (hasTopConceptI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()     {}
func (hasTopConceptI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23hasTopConcept() {}

var hasTopConceptKindInterface reflect.Type

var HasTopConcept = hasTopConceptI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: COREVocabulary, Name: "hasTopConcept"},
	ADomain:           ConceptScheme,
	ARange:            Concept,
	AnInverseOf:       TopConceptOf,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: true, 
	ADatatype: false, AnIndividual: false,
}}

func (topConceptOfI) InverseOf() sst.ElementInformer { return HasTopConcept }

// Definitions of core.hiddenLabel

type IsHiddenLabel interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23hiddenLabel()
}

type KindHiddenLabel interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23hiddenLabel()
}

type hiddenLabelI struct{ sst.ElementInfo }

func (hiddenLabelI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23hiddenLabel()   {}
func (hiddenLabelI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()   {}
func (hiddenLabelI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23label()      {}
func (hiddenLabelI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23hiddenLabel() {}

var hiddenLabelKindInterface reflect.Type

var HiddenLabel = hiddenLabelI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: COREVocabulary, Name: "hiddenLabel"},
	ADomain:           rdfs.Resource,
	ARange:            rdfs.Literal,
	ASubPropertyOf:    rdfs.Label,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of core.historyNote

type IsHistoryNote interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23historyNote()
}

type KindHistoryNote interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23historyNote()
}

type historyNoteI struct{ sst.ElementInfo }

func (historyNoteI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23historyNote()   {}
func (historyNoteI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()   {}
func (historyNoteI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23historyNote() {}
func (historyNoteI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23note()        {}

var historyNoteKindInterface reflect.Type

var HistoryNote = historyNoteI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: COREVocabulary, Name: "historyNote"},
	ASubPropertyOf:    Note,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of core.inScheme

type IsInScheme interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23inScheme()
}

type KindInScheme interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23inScheme()
}

type inSchemeI struct{ sst.ElementInfo }

func (inSchemeI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23inScheme()    {}
func (inSchemeI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource() {}
func (inSchemeI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23inScheme()  {}

var inSchemeKindInterface reflect.Type

var InScheme = inSchemeI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: COREVocabulary, Name: "inScheme"},
	ARange:            ConceptScheme,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: true, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of core.mappingRelation

type IsMappingRelation interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23mappingRelation()
}

type KindMappingRelation interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23mappingRelation()
}

type mappingRelationI struct{ sst.ElementInfo }

func (mappingRelationI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23mappingRelation()    {}
func (mappingRelationI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()        {}
func (mappingRelationI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23mappingRelation()  {}
func (mappingRelationI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23semanticRelation() {}

var mappingRelationKindInterface reflect.Type

var MappingRelation = mappingRelationI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: COREVocabulary, Name: "mappingRelation"},
	ADomain:           Concept,
	ARange:            Concept,
	ASubPropertyOf:    SemanticRelation,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: true, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of core.member

type IsMember interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23member()
}

type KindMember interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23member()
}

type memberI struct{ sst.ElementInfo }

func (memberI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23member()      {}
func (memberI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource() {}
func (memberI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23member()    {}

var memberKindInterface reflect.Type

var Member = memberI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: COREVocabulary, Name: "member"},
	ADomain:           Collection,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: true, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of core.memberList

type IsMemberList interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23memberList()
}

type KindMemberList interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23memberList()
}

type memberListI struct{ sst.ElementInfo }

func (memberListI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23memberList()   {}
func (memberListI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()  {}
func (memberListI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23memberList() {}

var memberListKindInterface reflect.Type

var MemberList = memberListI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: COREVocabulary, Name: "memberList"},
	ADomain:           OrderedCollection,
	ARange:            rdf.List,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: true, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of core.narrowMatch

type IsNarrowMatch interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23narrowMatch()
}

type KindNarrowMatch interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23narrowMatch()
}

type narrowMatchI struct{ sst.ElementInfo }

func (narrowMatchI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23narrowMatch()          {}
func (narrowMatchI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()          {}
func (narrowMatchI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23mappingRelation()    {}
func (narrowMatchI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23narrowMatch()        {}
func (narrowMatchI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23narrower()           {}
func (narrowMatchI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23narrowerTransitive() {}
func (narrowMatchI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23semanticRelation()   {}

var narrowMatchKindInterface reflect.Type

var NarrowMatch = narrowMatchI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: COREVocabulary, Name: "narrowMatch"},
	ADomain:           Concept,
	ARange:            Concept,
	ASubPropertyOf:    Narrower,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: true, 
	ADatatype: false, AnIndividual: false,
}}

func (broadMatchI) InverseOf() sst.ElementInformer { return NarrowMatch }

// Definitions of core.narrower

type IsNarrower interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23narrower()
}

type KindNarrower interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23narrower()
}

type narrowerI struct{ sst.ElementInfo }

func (narrowerI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23narrower()             {}
func (narrowerI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()          {}
func (narrowerI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23narrower()           {}
func (narrowerI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23narrowerTransitive() {}
func (narrowerI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23semanticRelation()   {}

var narrowerKindInterface reflect.Type

var Narrower = narrowerI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: COREVocabulary, Name: "narrower"},
	ADomain:           Concept,
	ARange:            Concept,
	ASubPropertyOf:    NarrowerTransitive,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: true, 
	ADatatype: false, AnIndividual: false,
}}

func (broaderI) InverseOf() sst.ElementInformer { return Narrower }

// Definitions of core.narrowerTransitive

type IsNarrowerTransitive interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23narrowerTransitive()
}

type KindNarrowerTransitive interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23narrowerTransitive()
}

type narrowerTransitiveI struct{ sst.ElementInfo }

func (narrowerTransitiveI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23narrowerTransitive()   {}
func (narrowerTransitiveI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()          {}
func (narrowerTransitiveI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23narrowerTransitive() {}
func (narrowerTransitiveI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23semanticRelation()   {}

var narrowerTransitiveKindInterface reflect.Type

var NarrowerTransitive = narrowerTransitiveI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: COREVocabulary, Name: "narrowerTransitive"},
	ADomain:           Concept,
	ARange:            Concept,
	ASubPropertyOf:    SemanticRelation,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: true, 
	ADatatype: false, AnIndividual: false,
}}

func (broaderTransitiveI) InverseOf() sst.ElementInformer { return NarrowerTransitive }

// Definitions of core.notation

type IsNotation interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23notation()
}

type KindNotation interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23notation()
}

type notationI struct{ sst.ElementInfo }

func (notationI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23notation()    {}
func (notationI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource() {}
func (notationI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23notation()  {}

var notationKindInterface reflect.Type

var Notation = notationI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: COREVocabulary, Name: "notation"},

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: true, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of core.note

type IsNote interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23note()
}

type KindNote interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23note()
}

type noteI struct{ sst.ElementInfo }

func (noteI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23note()        {}
func (noteI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource() {}
func (noteI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23note()      {}

var noteKindInterface reflect.Type

var Note = noteI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: COREVocabulary, Name: "note"},

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of core.prefLabel

type IsPrefLabel interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23prefLabel()
}

type KindPrefLabel interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23prefLabel()
}

type prefLabelI struct{ sst.ElementInfo }

func (prefLabelI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23prefLabel()   {}
func (prefLabelI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource() {}
func (prefLabelI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23label()    {}
func (prefLabelI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23prefLabel() {}

var prefLabelKindInterface reflect.Type

var PrefLabel = prefLabelI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: COREVocabulary, Name: "prefLabel"},
	ADomain:           rdfs.Resource,
	ARange:            rdfs.Literal,
	ASubPropertyOf:    rdfs.Label,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of core.related

type IsRelated interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23related()
}

type KindRelated interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23related()
}

type relatedI struct{ sst.ElementInfo }

func (relatedI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23related()            {}
func (relatedI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()        {}
func (relatedI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23related()          {}
func (relatedI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23semanticRelation() {}

var relatedKindInterface reflect.Type

var Related = relatedI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: COREVocabulary, Name: "related"},
	ADomain:           Concept,
	ARange:            Concept,
	ASubPropertyOf:    SemanticRelation,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: true, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of core.relatedMatch

type IsRelatedMatch interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23relatedMatch()
}

type KindRelatedMatch interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23relatedMatch()
}

type relatedMatchI struct{ sst.ElementInfo }

func (relatedMatchI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23relatedMatch()       {}
func (relatedMatchI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()        {}
func (relatedMatchI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23mappingRelation()  {}
func (relatedMatchI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23related()          {}
func (relatedMatchI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23relatedMatch()     {}
func (relatedMatchI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23semanticRelation() {}

var relatedMatchKindInterface reflect.Type

var RelatedMatch = relatedMatchI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: COREVocabulary, Name: "relatedMatch"},
	ADomain:           Concept,
	ARange:            Concept,
	ASubPropertyOf:    Related,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: true, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of core.scopeNote

type IsScopeNote interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23scopeNote()
}

type KindScopeNote interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23scopeNote()
}

type scopeNoteI struct{ sst.ElementInfo }

func (scopeNoteI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23scopeNote()   {}
func (scopeNoteI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource() {}
func (scopeNoteI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23note()      {}
func (scopeNoteI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23scopeNote() {}

var scopeNoteKindInterface reflect.Type

var ScopeNote = scopeNoteI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: COREVocabulary, Name: "scopeNote"},
	ASubPropertyOf:    Note,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of core.semanticRelation

type IsSemanticRelation interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23semanticRelation()
}

type KindSemanticRelation interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23semanticRelation()
}

type semanticRelationI struct{ sst.ElementInfo }

func (semanticRelationI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23semanticRelation()   {}
func (semanticRelationI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()        {}
func (semanticRelationI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23semanticRelation() {}

var semanticRelationKindInterface reflect.Type

var SemanticRelation = semanticRelationI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: COREVocabulary, Name: "semanticRelation"},
	ADomain:           Concept,
	ARange:            Concept,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: true, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of core.topConceptOf

type IsTopConceptOf interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23topConceptOf()
}

type KindTopConceptOf interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23topConceptOf()
}

type topConceptOfI struct{ sst.ElementInfo }

func (topConceptOfI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23topConceptOf()   {}
func (topConceptOfI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()    {}
func (topConceptOfI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23inScheme()     {}
func (topConceptOfI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2004_2F02_2Fskos_2Fcore_23topConceptOf() {}

var topConceptOfKindInterface reflect.Type

var TopConceptOf = topConceptOfI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: COREVocabulary, Name: "topConceptOf"},
	ADomain:           Concept,
	ARange:            ConceptScheme,
	ASubPropertyOf:    InScheme,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: true, 
	ADatatype: false, AnIndividual: false,
}}

func (hasTopConceptI) InverseOf() sst.ElementInformer { return TopConceptOf }
