// Code generated by tools/compiler/compiler.go DO NOT EDIT.

// Copyright Semantic STEP Technology GmbH, Germany & DCT Co., Ltd. Tianjin, China

package ssmeta

import (
	"reflect"
	"github.com/semanticstep/sst-core/sst"
)

type pkg struct{ sst.ElementInfo }

var SSMETAVocabulary = sst.Vocabulary{BaseIRI: "http://ontology.semanticstep.net/ssmeta"}

var (
	PKG = sst.ElementPkg(pkg{})
	_   = PKG
)

// Definitions of ssmeta.AbstractClass

type IsAbstractClass interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23AbstractClass()
}

type KindAbstractClass interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23AbstractClass()
}

type abstractClassI struct{ sst.ElementInfo }

func (abstractClassI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23AbstractClass()   {}
func (abstractClassI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23AbstractClass() {}
func (abstractClassI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()   {}

var abstractClassKindInterface reflect.Type

var AbstractClass = abstractClassI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "AbstractClass"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of ssmeta.AbstractProperty

type IsAbstractProperty interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23AbstractProperty()
}

type KindAbstractProperty interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23AbstractProperty()
}

type abstractPropertyI struct{ sst.ElementInfo }

func (abstractPropertyI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23AbstractProperty()        {}
func (abstractPropertyI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23AbstractProperty()      {}
func (abstractPropertyI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23Property() {}
func (abstractPropertyI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()           {}

var abstractPropertyKindInterface reflect.Type

var AbstractProperty = abstractPropertyI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "AbstractProperty"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of ssmeta.ConnotationalClass

type IsConnotationalClass interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23ConnotationalClass()
}

type KindConnotationalClass interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23ConnotationalClass()
}

type connotationalClassI struct{ sst.ElementInfo }

func (connotationalClassI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23ConnotationalClass()   {}
func (connotationalClassI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23ConnotationalClass() {}
func (connotationalClassI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()        {}

var connotationalClassKindInterface reflect.Type

var ConnotationalClass = connotationalClassI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "ConnotationalClass"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of ssmeta.DefinedType

type IsDefinedType interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23DefinedType()
}

type KindDefinedType interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23DefinedType()
}

type definedTypeI struct{ sst.ElementInfo }

func (definedTypeI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23DefinedType()   {}
func (definedTypeI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23DefinedType() {}
func (definedTypeI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource() {}

var definedTypeKindInterface reflect.Type

var DefinedType = definedTypeI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "DefinedType"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
	AMainClassSupersedure: map[sst.Element]struct{}{},
}}

// Definitions of ssmeta.Entity

type IsEntity interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23Entity()
}

type KindEntity interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23Entity()
}

type entityI struct{ sst.ElementInfo }

func (entityI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23Entity()        {}
func (entityI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23Entity()      {}
func (entityI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource() {}

var entityKindInterface reflect.Type

var Entity = entityI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "Entity"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
	AMainClassSupersedure: map[sst.Element]struct{}{},
}}

// Definitions of ssmeta.EntityInstance

type IsEntityInstance interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23EntityInstance()
}

type KindEntityInstance interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23EntityInstance()
}

type entityInstanceI struct{ sst.ElementInfo }

func (entityInstanceI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23EntityInstance()   {}
func (entityInstanceI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23EntityInstance() {}
func (entityInstanceI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()    {}

var entityInstanceKindInterface reflect.Type

var EntityInstance = entityInstanceI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "EntityInstance"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
	AMainClassSupersedure: map[sst.Element]struct{}{},
}}

// Definitions of ssmeta.EnumerationClass

type IsEnumerationClass interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23EnumerationClass()
}

type KindEnumerationClass interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23EnumerationClass()
}

type enumerationClassI struct{ sst.ElementInfo }

func (enumerationClassI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23EnumerationClass()   {}
func (enumerationClassI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23EnumerationClass() {}
func (enumerationClassI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()      {}

var enumerationClassKindInterface reflect.Type

var EnumerationClass = enumerationClassI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "EnumerationClass"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of ssmeta.EnumerationValue

type IsEnumerationValue interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23EnumerationValue()
}

type KindEnumerationValue interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23EnumerationValue()
}

type enumerationValueI struct{ sst.ElementInfo }

func (enumerationValueI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23EnumerationValue()   {}
func (enumerationValueI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23EnumerationValue() {}
func (enumerationValueI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()      {}

var enumerationValueKindInterface reflect.Type

var EnumerationValue = enumerationValueI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "EnumerationValue"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
	AMainClassSupersedure: map[sst.Element]struct{}{},
}}

// Definitions of ssmeta.Field

type IsField interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23Field()
}

type KindField interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23Field()
}

type fieldI struct{ sst.ElementInfo }

func (fieldI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23Field()                   {}
func (fieldI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23Field()                 {}
func (fieldI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23Property() {}
func (fieldI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()           {}

var fieldKindInterface reflect.Type

var Field = fieldI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "Field"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
	AMainClassSupersedure: map[sst.Element]struct{}{},
}}

// Definitions of ssmeta.ListOfProperties

type IsListOfProperties interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23ListOfProperties()
}

type KindListOfProperties interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23ListOfProperties()
}

type listOfPropertiesI struct{ sst.ElementInfo }

func (listOfPropertiesI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23ListOfProperties()    {}
func (listOfPropertiesI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23ListOfProperties()  {}
func (listOfPropertiesI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23List() {}
func (listOfPropertiesI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()       {}

var listOfPropertiesKindInterface reflect.Type

var ListOfProperties = listOfPropertiesI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "ListOfProperties"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of ssmeta.MainClass

type IsMainClass interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23MainClass()
}

type KindMainClass interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23MainClass()
}

type mainClassI struct{ sst.ElementInfo }

func (mainClassI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23MainClass()     {}
func (mainClassI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23MainClass()   {}
func (mainClassI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource() {}

var mainClassKindInterface reflect.Type

var MainClass = mainClassI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "MainClass"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of ssmeta.OptionClass

type IsOptionClass interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23OptionClass()
}

type KindOptionClass interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23OptionClass()
}

type optionClassI struct{ sst.ElementInfo }

func (optionClassI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23OptionClass()   {}
func (optionClassI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23OptionClass() {}
func (optionClassI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource() {}

var optionClassKindInterface reflect.Type

var OptionClass = optionClassI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "OptionClass"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of ssmeta.PropertyAssignment

type IsPropertyAssignment interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23PropertyAssignment()
}

type KindPropertyAssignment interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23PropertyAssignment()
}

type propertyAssignmentI struct{ sst.ElementInfo }

func (propertyAssignmentI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23PropertyAssignment()   {}
func (propertyAssignmentI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23PropertyAssignment() {}
func (propertyAssignmentI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()        {}

var propertyAssignmentKindInterface reflect.Type

var PropertyAssignment = propertyAssignmentI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "PropertyAssignment"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of ssmeta.Schema

type IsSchema interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23Schema()
}

type KindSchema interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23Schema()
}

type schemaI struct{ sst.ElementInfo }

func (schemaI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23Schema()        {}
func (schemaI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23Schema()      {}
func (schemaI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource() {}

var schemaKindInterface reflect.Type

var Schema = schemaI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "Schema"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
	AMainClassSupersedure: map[sst.Element]struct{}{},
}}

// Definitions of ssmeta.SelectClass

type IsSelectClass interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23SelectClass()
}

type KindSelectClass interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23SelectClass()
}

type selectClassI struct{ sst.ElementInfo }

func (selectClassI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23SelectClass()   {}
func (selectClassI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23SelectClass() {}
func (selectClassI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource() {}

var selectClassKindInterface reflect.Type

var SelectClass = selectClassI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "SelectClass"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of ssmeta.SingleEntityValue

type IsSingleEntityValue interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23SingleEntityValue()
}

type KindSingleEntityValue interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23SingleEntityValue()
}

type singleEntityValueI struct{ sst.ElementInfo }

func (singleEntityValueI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23SingleEntityValue()   {}
func (singleEntityValueI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23SingleEntityValue() {}
func (singleEntityValueI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()       {}

var singleEntityValueKindInterface reflect.Type

var SingleEntityValue = singleEntityValueI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "SingleEntityValue"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
	AMainClassSupersedure: map[sst.Element]struct{}{},
}}

// Definitions of ssmeta.SpecialPropertyValue

type IsSpecialPropertyValue interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23SpecialPropertyValue()
}

type KindSpecialPropertyValue interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23SpecialPropertyValue()
}

type specialPropertyValueI struct{ sst.ElementInfo }

func (specialPropertyValueI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23SpecialPropertyValue()   {}
func (specialPropertyValueI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23SpecialPropertyValue() {}
func (specialPropertyValueI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()          {}

var specialPropertyValueKindInterface reflect.Type

var SpecialPropertyValue = specialPropertyValueI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "SpecialPropertyValue"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
	AMainClassSupersedure: map[sst.Element]struct{}{},
}}

// Definitions of ssmeta.StepImMapAttributeSpecial

type IsStepImMapAttributeSpecial interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23StepImMapAttributeSpecial()
}

type KindStepImMapAttributeSpecial interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23StepImMapAttributeSpecial()
}

type stepImMapAttributeSpecialI struct{ sst.ElementInfo }

func (stepImMapAttributeSpecialI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23StepImMapAttributeSpecial()   {}
func (stepImMapAttributeSpecialI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23StepImMapAttributeSpecial() {}
func (stepImMapAttributeSpecialI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()               {}
func (stepImMapAttributeSpecialI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2002_2F07_2Fowl_23Thing()                           {}

var stepImMapAttributeSpecialKindInterface reflect.Type

var StepImMapAttributeSpecial = stepImMapAttributeSpecialI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "StepImMapAttributeSpecial"},

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: true,
}}

// Definitions of ssmeta.assignedProperty

type IsAssignedProperty interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23assignedProperty()
}

type KindAssignedProperty interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23assignedProperty()
}

type assignedPropertyI struct{ sst.ElementInfo }

func (assignedPropertyI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23assignedProperty()   {}
func (assignedPropertyI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23assignedProperty() {}
func (assignedPropertyI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()      {}

var assignedPropertyKindInterface reflect.Type

var AssignedProperty = assignedPropertyI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "assignedProperty"},
	ADomain:           PropertyAssignment,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: true, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of ssmeta.assignedPropertyMandatory

type IsAssignedPropertyMandatory interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23assignedPropertyMandatory()
}

type KindAssignedPropertyMandatory interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23assignedPropertyMandatory()
}

type assignedPropertyMandatoryI struct{ sst.ElementInfo }

func (assignedPropertyMandatoryI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23assignedPropertyMandatory()   {}
func (assignedPropertyMandatoryI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23assignedProperty()          {}
func (assignedPropertyMandatoryI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23assignedPropertyMandatory() {}
func (assignedPropertyMandatoryI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()               {}

var assignedPropertyMandatoryKindInterface reflect.Type

var AssignedPropertyMandatory = assignedPropertyMandatoryI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "assignedPropertyMandatory"},
	ASubtypeOf:        []sst.ElementInformer{AssignedProperty},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: true, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of ssmeta.assignedPropertyMandatorySet

type IsAssignedPropertyMandatorySet interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23assignedPropertyMandatorySet()
}

type KindAssignedPropertyMandatorySet interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23assignedPropertyMandatorySet()
}

type assignedPropertyMandatorySetI struct{ sst.ElementInfo }

func (assignedPropertyMandatorySetI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23assignedPropertyMandatorySet()   {}
func (assignedPropertyMandatorySetI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23assignedProperty()             {}
func (assignedPropertyMandatorySetI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23assignedPropertyMandatorySet() {}
func (assignedPropertyMandatorySetI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()                  {}

var assignedPropertyMandatorySetKindInterface reflect.Type

var AssignedPropertyMandatorySet = assignedPropertyMandatorySetI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "assignedPropertyMandatorySet"},
	ASubtypeOf:        []sst.ElementInformer{AssignedProperty},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: true, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of ssmeta.assignedPropertyOptional

type IsAssignedPropertyOptional interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23assignedPropertyOptional()
}

type KindAssignedPropertyOptional interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23assignedPropertyOptional()
}

type assignedPropertyOptionalI struct{ sst.ElementInfo }

func (assignedPropertyOptionalI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23assignedPropertyOptional()   {}
func (assignedPropertyOptionalI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23assignedProperty()         {}
func (assignedPropertyOptionalI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23assignedPropertyOptional() {}
func (assignedPropertyOptionalI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()              {}

var assignedPropertyOptionalKindInterface reflect.Type

var AssignedPropertyOptional = assignedPropertyOptionalI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "assignedPropertyOptional"},
	ASubtypeOf:        []sst.ElementInformer{AssignedProperty},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: true, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of ssmeta.assignedPropertyOptionalSet

type IsAssignedPropertyOptionalSet interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23assignedPropertyOptionalSet()
}

type KindAssignedPropertyOptionalSet interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23assignedPropertyOptionalSet()
}

type assignedPropertyOptionalSetI struct{ sst.ElementInfo }

func (assignedPropertyOptionalSetI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23assignedPropertyOptionalSet()   {}
func (assignedPropertyOptionalSetI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23assignedProperty()            {}
func (assignedPropertyOptionalSetI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23assignedPropertyOptionalSet() {}
func (assignedPropertyOptionalSetI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()                 {}

var assignedPropertyOptionalSetKindInterface reflect.Type

var AssignedPropertyOptionalSet = assignedPropertyOptionalSetI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "assignedPropertyOptionalSet"},
	ASubtypeOf:        []sst.ElementInformer{AssignedProperty},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: true, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of ssmeta.attributeValues

type IsAttributeValues interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23attributeValues()
}

type KindAttributeValues interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23attributeValues()
}

type attributeValuesI struct{ sst.ElementInfo }

func (attributeValuesI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23attributeValues()   {}
func (attributeValuesI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23attributeValues() {}
func (attributeValuesI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()     {}

var attributeValuesKindInterface reflect.Type

var AttributeValues = attributeValuesI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "attributeValues"},

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: true, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of ssmeta.complexInstanceValue

type IsComplexInstanceValue interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23complexInstanceValue()
}

type KindComplexInstanceValue interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23complexInstanceValue()
}

type complexInstanceValueI struct{ sst.ElementInfo }

func (complexInstanceValueI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23complexInstanceValue()   {}
func (complexInstanceValueI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23complexInstanceValue() {}
func (complexInstanceValueI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()          {}

var complexInstanceValueKindInterface reflect.Type

var ComplexInstanceValue = complexInstanceValueI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "complexInstanceValue"},
	ADomain:           EntityInstance,
	ARange:            SingleEntityValue,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: true, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of ssmeta.derivedValue

type IsDerivedValue interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23derivedValue()
}

type KindDerivedValue interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23derivedValue()
}

type derivedValueI struct{ sst.ElementInfo }

func (derivedValueI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23derivedValue()   {}
func (derivedValueI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23derivedValue() {}
func (derivedValueI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()  {}
func (derivedValueI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2002_2F07_2Fowl_23Thing()              {}

var derivedValueKindInterface reflect.Type

var DerivedValue = derivedValueI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "derivedValue"},

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: true,
}}

// Definitions of ssmeta.directive

type IsDirective interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23directive()
}

type KindDirective interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23directive()
}

type directiveI struct{ sst.ElementInfo }

func (directiveI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23directive()     {}
func (directiveI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23directive()   {}
func (directiveI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource() {}

var directiveKindInterface reflect.Type

var Directive = directiveI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "directive"},

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of ssmeta.emptyAgggregateValue

type IsEmptyAgggregateValue interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23emptyAgggregateValue()
}

type KindEmptyAgggregateValue interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23emptyAgggregateValue()
}

type emptyAgggregateValueI struct{ sst.ElementInfo }

func (emptyAgggregateValueI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23emptyAgggregateValue()   {}
func (emptyAgggregateValueI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23emptyAgggregateValue() {}
func (emptyAgggregateValueI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()          {}
func (emptyAgggregateValueI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2002_2F07_2Fowl_23Thing()                      {}

var emptyAgggregateValueKindInterface reflect.Type

var EmptyAgggregateValue = emptyAgggregateValueI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "emptyAgggregateValue"},

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: true,
}}

// Definitions of ssmeta.entityInstanceType

type IsEntityInstanceType interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23entityInstanceType()
}

type KindEntityInstanceType interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23entityInstanceType()
}

type entityInstanceTypeI struct{ sst.ElementInfo }

func (entityInstanceTypeI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23entityInstanceType()   {}
func (entityInstanceTypeI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23entityInstanceType() {}
func (entityInstanceTypeI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()        {}

var entityInstanceTypeKindInterface reflect.Type

var EntityInstanceType = entityInstanceTypeI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "entityInstanceType"},
	ADomain:           EntityInstance,
	ARange:            Entity,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: true, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of ssmeta.externalMap

type IsExternalMap interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23externalMap()
}

type KindExternalMap interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23externalMap()
}

type externalMapI struct{ sst.ElementInfo }

func (externalMapI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23externalMap()   {}
func (externalMapI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23externalMap() {}
func (externalMapI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource() {}
func (externalMapI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23label()    {}

var externalMapKindInterface reflect.Type

var ExternalMap = externalMapI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "externalMap"},

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: true, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of ssmeta.formClassProperties

type IsFormClassProperties interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23formClassProperties()
}

type KindFormClassProperties interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23formClassProperties()
}

type formClassPropertiesI struct{ sst.ElementInfo }

func (formClassPropertiesI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23formClassProperties()   {}
func (formClassPropertiesI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23formClassProperties() {}
func (formClassPropertiesI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()         {}

var formClassPropertiesKindInterface reflect.Type

var FormClassProperties = formClassPropertiesI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "formClassProperties"},
	ARange:            ListOfProperties,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: true, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of ssmeta.formIndividualProperties

type IsFormIndividualProperties interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23formIndividualProperties()
}

type KindFormIndividualProperties interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23formIndividualProperties()
}

type formIndividualPropertiesI struct{ sst.ElementInfo }

func (formIndividualPropertiesI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23formIndividualProperties()   {}
func (formIndividualPropertiesI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23formIndividualProperties() {}
func (formIndividualPropertiesI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()              {}

var formIndividualPropertiesKindInterface reflect.Type

var FormIndividualProperties = formIndividualPropertiesI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "formIndividualProperties"},
	ARange:            ListOfProperties,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: true, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of ssmeta.formProperties

type IsFormProperties interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23formProperties()
}

type KindFormProperties interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23formProperties()
}

type formPropertiesI struct{ sst.ElementInfo }

func (formPropertiesI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23formProperties()   {}
func (formPropertiesI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23formProperties() {}
func (formPropertiesI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()    {}

var formPropertiesKindInterface reflect.Type

var FormProperties = formPropertiesI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "formProperties"},
	ARange:            ListOfProperties,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: true, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of ssmeta.goAlias

type IsGoAlias interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23goAlias()
}

type KindGoAlias interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23goAlias()
}

type goAliasI struct{ sst.ElementInfo }

func (goAliasI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23goAlias()       {}
func (goAliasI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23goAlias()     {}
func (goAliasI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource() {}

var goAliasKindInterface reflect.Type

var GoAlias = goAliasI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "goAlias"},

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: true, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of ssmeta.indeterminateValue

type IsIndeterminateValue interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23indeterminateValue()
}

type KindIndeterminateValue interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23indeterminateValue()
}

type indeterminateValueI struct{ sst.ElementInfo }

func (indeterminateValueI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23indeterminateValue()   {}
func (indeterminateValueI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23indeterminateValue() {}
func (indeterminateValueI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()        {}
func (indeterminateValueI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2002_2F07_2Fowl_23Thing()                    {}

var indeterminateValueKindInterface reflect.Type

var IndeterminateValue = indeterminateValueI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "indeterminateValue"},

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: true,
}}

// Definitions of ssmeta.isAbstract

type IsIsAbstract interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23isAbstract()
}

type KindIsAbstract interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23isAbstract()
}

type isAbstractI struct{ sst.ElementInfo }

func (isAbstractI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23isAbstract()    {}
func (isAbstractI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23isAbstract()  {}
func (isAbstractI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource() {}

var isAbstractKindInterface reflect.Type

var IsAbstract = isAbstractI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "isAbstract"},

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: true, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of ssmeta.isActive

type IsIsActive interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23isActive()
}

type KindIsActive interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23isActive()
}

type isActiveI struct{ sst.ElementInfo }

func (isActiveI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23isActive()      {}
func (isActiveI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23isActive()    {}
func (isActiveI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource() {}

var isActiveKindInterface reflect.Type

var IsActive = isActiveI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "isActive"},

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: true, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of ssmeta.isSystem

type IsIsSystem interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23isSystem()
}

type KindIsSystem interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23isSystem()
}

type isSystemI struct{ sst.ElementInfo }

func (isSystemI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23isSystem()      {}
func (isSystemI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23isSystem()    {}
func (isSystemI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource() {}

var isSystemKindInterface reflect.Type

var IsSystem = isSystemI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "isSystem"},

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: true, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of ssmeta.ofType

type IsOfType interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23ofType()
}

type KindOfType interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23ofType()
}

type ofTypeI struct{ sst.ElementInfo }

func (ofTypeI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23ofType()        {}
func (ofTypeI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23ofType()      {}
func (ofTypeI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource() {}

var ofTypeKindInterface reflect.Type

var OfType = ofTypeI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "ofType"},

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: true, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of ssmeta.simpleInstanceValue

type IsSimpleInstanceValue interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23simpleInstanceValue()
}

type KindSimpleInstanceValue interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23simpleInstanceValue()
}

type simpleInstanceValueI struct{ sst.ElementInfo }

func (simpleInstanceValueI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23simpleInstanceValue()   {}
func (simpleInstanceValueI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23simpleInstanceValue() {}
func (simpleInstanceValueI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()         {}

var simpleInstanceValueKindInterface reflect.Type

var SimpleInstanceValue = simpleInstanceValueI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "simpleInstanceValue"},
	ADomain:           EntityInstance,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of ssmeta.singleEntityValueType

type IsSingleEntityValueType interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23singleEntityValueType()
}

type KindSingleEntityValueType interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23singleEntityValueType()
}

type singleEntityValueTypeI struct{ sst.ElementInfo }

func (singleEntityValueTypeI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23singleEntityValueType()   {}
func (singleEntityValueTypeI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23singleEntityValueType() {}
func (singleEntityValueTypeI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()           {}

var singleEntityValueTypeKindInterface reflect.Type

var SingleEntityValueType = singleEntityValueTypeI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "singleEntityValueType"},
	ADomain:           SingleEntityValue,
	ARange:            Entity,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: true, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of ssmeta.sourceDataset

type IsSourceDataset interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23sourceDataset()
}

type KindSourceDataset interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23sourceDataset()
}

type sourceDatasetI struct{ sst.ElementInfo }

func (sourceDatasetI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23sourceDataset()   {}
func (sourceDatasetI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23sourceDataset() {}
func (sourceDatasetI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()   {}

var sourceDatasetKindInterface reflect.Type

var SourceDataset = sourceDatasetI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "sourceDataset"},

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of ssmeta.sourceDatasetDateTime

type IsSourceDatasetDateTime interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23sourceDatasetDateTime()
}

type KindSourceDatasetDateTime interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23sourceDatasetDateTime()
}

type sourceDatasetDateTimeI struct{ sst.ElementInfo }

func (sourceDatasetDateTimeI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23sourceDatasetDateTime()   {}
func (sourceDatasetDateTimeI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23sourceDatasetDateTime() {}
func (sourceDatasetDateTimeI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()           {}

var sourceDatasetDateTimeKindInterface reflect.Type

var SourceDatasetDateTime = sourceDatasetDateTimeI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "sourceDatasetDateTime"},

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of ssmeta.sourceDatasetHash256

type IsSourceDatasetHash256 interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23sourceDatasetHash256()
}

type KindSourceDatasetHash256 interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23sourceDatasetHash256()
}

type sourceDatasetHash256I struct{ sst.ElementInfo }

func (sourceDatasetHash256I) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23sourceDatasetHash256()   {}
func (sourceDatasetHash256I) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23sourceDatasetHash256() {}
func (sourceDatasetHash256I) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()          {}

var sourceDatasetHash256KindInterface reflect.Type

var SourceDatasetHash256 = sourceDatasetHash256I{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "sourceDatasetHash256"},

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of ssmeta.sourceSystem

type IsSourceSystem interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23sourceSystem()
}

type KindSourceSystem interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23sourceSystem()
}

type sourceSystemI struct{ sst.ElementInfo }

func (sourceSystemI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23sourceSystem()   {}
func (sourceSystemI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23sourceSystem() {}
func (sourceSystemI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()  {}

var sourceSystemKindInterface reflect.Type

var SourceSystem = sourceSystemI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "sourceSystem"},

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of ssmeta.stepArmMap

type IsStepArmMap interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23stepArmMap()
}

type KindStepArmMap interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23stepArmMap()
}

type stepArmMapI struct{ sst.ElementInfo }

func (stepArmMapI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23stepArmMap()    {}
func (stepArmMapI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23stepArmMap()  {}
func (stepArmMapI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource() {}
func (stepArmMapI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23label()    {}

var stepArmMapKindInterface reflect.Type

var StepArmMap = stepArmMapI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "stepArmMap"},

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: true, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of ssmeta.stepDmEnumerationMap

type IsStepDmEnumerationMap interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23stepDmEnumerationMap()
}

type KindStepDmEnumerationMap interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23stepDmEnumerationMap()
}

type stepDmEnumerationMapI struct{ sst.ElementInfo }

func (stepDmEnumerationMapI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23stepDmEnumerationMap()   {}
func (stepDmEnumerationMapI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23stepDmEnumerationMap() {}
func (stepDmEnumerationMapI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()          {}
func (stepDmEnumerationMapI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23label()             {}

var stepDmEnumerationMapKindInterface reflect.Type

var StepDmEnumerationMap = stepDmEnumerationMapI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "stepDmEnumerationMap"},

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: true, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of ssmeta.stepDmMap

type IsStepDmMap interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23stepDmMap()
}

type KindStepDmMap interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23stepDmMap()
}

type stepDmMapI struct{ sst.ElementInfo }

func (stepDmMapI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23stepDmMap()     {}
func (stepDmMapI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23stepDmMap()   {}
func (stepDmMapI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource() {}
func (stepDmMapI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23label()    {}

var stepDmMapKindInterface reflect.Type

var StepDmMap = stepDmMapI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "stepDmMap"},

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: true, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of ssmeta.stepImAttributeMap

type IsStepImAttributeMap interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23stepImAttributeMap()
}

type KindStepImAttributeMap interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23stepImAttributeMap()
}

type stepImAttributeMapI struct{ sst.ElementInfo }

func (stepImAttributeMapI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23stepImAttributeMap()   {}
func (stepImAttributeMapI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23stepImAttributeMap() {}
func (stepImAttributeMapI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()        {}
func (stepImAttributeMapI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23label()           {}

var stepImAttributeMapKindInterface reflect.Type

var StepImAttributeMap = stepImAttributeMapI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "stepImAttributeMap"},

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: true, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of ssmeta.stepImDefinedTypeMap

type IsStepImDefinedTypeMap interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23stepImDefinedTypeMap()
}

type KindStepImDefinedTypeMap interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23stepImDefinedTypeMap()
}

type stepImDefinedTypeMapI struct{ sst.ElementInfo }

func (stepImDefinedTypeMapI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23stepImDefinedTypeMap()   {}
func (stepImDefinedTypeMapI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23stepImDefinedTypeMap() {}
func (stepImDefinedTypeMapI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()          {}
func (stepImDefinedTypeMapI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23label()             {}

var stepImDefinedTypeMapKindInterface reflect.Type

var StepImDefinedTypeMap = stepImDefinedTypeMapI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "stepImDefinedTypeMap"},

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: true, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of ssmeta.stepImEntityMap

type IsStepImEntityMap interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23stepImEntityMap()
}

type KindStepImEntityMap interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23stepImEntityMap()
}

type stepImEntityMapI struct{ sst.ElementInfo }

func (stepImEntityMapI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23stepImEntityMap()   {}
func (stepImEntityMapI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23stepImEntityMap() {}
func (stepImEntityMapI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()     {}
func (stepImEntityMapI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23label()        {}

var stepImEntityMapKindInterface reflect.Type

var StepImEntityMap = stepImEntityMapI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "stepImEntityMap"},

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: true, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of ssmeta.stepImEnumerationMap

type IsStepImEnumerationMap interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23stepImEnumerationMap()
}

type KindStepImEnumerationMap interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23stepImEnumerationMap()
}

type stepImEnumerationMapI struct{ sst.ElementInfo }

func (stepImEnumerationMapI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23stepImEnumerationMap()   {}
func (stepImEnumerationMapI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23stepImEnumerationMap() {}
func (stepImEnumerationMapI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()          {}
func (stepImEnumerationMapI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23label()             {}

var stepImEnumerationMapKindInterface reflect.Type

var StepImEnumerationMap = stepImEnumerationMapI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "stepImEnumerationMap"},

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: true, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of ssmeta.stepImMapAttributeOrder

type IsStepImMapAttributeOrder interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23stepImMapAttributeOrder()
}

type KindStepImMapAttributeOrder interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23stepImMapAttributeOrder()
}

type stepImMapAttributeOrderI struct{ sst.ElementInfo }

func (stepImMapAttributeOrderI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23stepImMapAttributeOrder()   {}
func (stepImMapAttributeOrderI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23stepImMapAttributeOrder() {}
func (stepImMapAttributeOrderI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()             {}

var stepImMapAttributeOrderKindInterface reflect.Type

var StepImMapAttributeOrder = stepImMapAttributeOrderI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "stepImMapAttributeOrder"},
	ADomain:           MainClass,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: true, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of ssmeta.stepImMapSupertypeOrder

type IsStepImMapSupertypeOrder interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23stepImMapSupertypeOrder()
}

type KindStepImMapSupertypeOrder interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23stepImMapSupertypeOrder()
}

type stepImMapSupertypeOrderI struct{ sst.ElementInfo }

func (stepImMapSupertypeOrderI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23stepImMapSupertypeOrder()   {}
func (stepImMapSupertypeOrderI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23stepImMapSupertypeOrder() {}
func (stepImMapSupertypeOrderI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()             {}

var stepImMapSupertypeOrderKindInterface reflect.Type

var StepImMapSupertypeOrder = stepImMapSupertypeOrderI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "stepImMapSupertypeOrder"},
	ADomain:           MainClass,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: true, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of ssmeta.stepImSelectMap

type IsStepImSelectMap interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23stepImSelectMap()
}

type KindStepImSelectMap interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23stepImSelectMap()
}

type stepImSelectMapI struct{ sst.ElementInfo }

func (stepImSelectMapI) AsIs_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23stepImSelectMap()   {}
func (stepImSelectMapI) AsKind_http_3A_2F_2Fontology_2Esemanticstep_2Enet_2Fssmeta_23stepImSelectMap() {}
func (stepImSelectMapI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()     {}
func (stepImSelectMapI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23label()        {}

var stepImSelectMapKindInterface reflect.Type

var StepImSelectMap = stepImSelectMapI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: SSMETAVocabulary, Name: "stepImSelectMap"},

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: true, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}
