// Copyright Semantic STEP Technology GmbH, Germany & DCT Co., Ltd. Tianjin, China

/*
HelloWorldWrite is an example SST application that shows how to create
a simple RDF graph and export it into both, a Turtle and into an SST binary file.

The resulting Turtle file contains the followng data:

	@prefix lci:	<http://ontology.semanticstep.net/lci#> .
	@prefix rdfs:	<http://www.w3.org/2000/01/rdf-schema#> .
	@prefix owl:	<http://www.w3.org/2002/07/owl#> .
	@prefix :	<urn:uuid:da02e201-d7ea-41cb-ab46-2b46788cff3f#> .

	<urn:uuid:da02e201-d7ea-41cb-ab46-2b46788cff3f>	a	owl:Ontology .
	:9399268c-1287-4846-b0e7-897358885699	a	lci:Individual ;
		rdfs:label	"hello world" .

There are two IBNodes.
The first one has no fragment and it is representing the whole NamedGraph and has a triple to sepcify that is an Ontology.
This is generated by SST automatically.
The second IBNode has a UUID fragment and contains two subject triples. First one to state that it is an Individual,
and the second with the lable "hello world".
*/
package main

import (
	"fmt"
	"log"
	"os"

	"git.semanticstep.net/x/sst/sst"
	// This fixed import with "_" is essential to intialize the SST dictionary.
	// This need to be manually added.
	_ "git.semanticstep.net/x/sst/vocabularies/dict"
	"git.semanticstep.net/x/sst/vocabularies/lci"
	"git.semanticstep.net/x/sst/vocabularies/rdfs"
)

func main() {
	fmt.Printf("HelloWorldWrite ... ")

	// The first thing in an SST application is to create a stage into which we are going to work in;
	// here it is an ephemeral stage (new, empty) that is not bound to any existing [Repository] and [Dataset].
	// Therefore, changes in ephemeral stage can not be committed.
	stage := sst.OpenStage(sst.DefaultTriplexMode)

	// A stage is bound to a dataset which consists of a default NamedGraph and other direct or indirect imported NamedGraph.
	// Here we pick the default NamedGraph.
	// The Dataset and so the default NamedGraph are assigned a random UUID-URN, e.g. <urn:uuid:a8f3dc19-68f5-44d1-97bc-21ba2d8a6037#>
	graph := stage.CreateNamedGraph("")

	// within the default namedGraph a new IRI node is created.
	// In this case the node is identified by a fragment that contains a random-UUID within the NamedGraph.
	// E.g. the UUID of the fragment is 6d52b623-f933-4c26-ba18-164a6cc50ae8,
	// and so the complete IRI of the node is e.g. <urn:uuid:a8f3dc19-68f5-44d1-97bc-21ba2d8a6037#6d52b623-f933-4c26-ba18-164a6cc50ae8>.
	// Note that this IRI contains 2 different UUIDs, one for the NamedGraph, and one for the fragment of the node in that NamedGraph.
	// An IBNode can exist in a NamedGraph only when it has at least one subject triple; so here we say it has the type lci.Individual.
	ib := graph.CreateIRINode("", lci.Individual)

	// with AddStatement we can add further triples
	ib.AddStatement(rdfs.Label, sst.String("HelloWorld"))

	// Next we create a triple (s statement) with:
	// * subject: the IRI node we created
	// * predicate: rdf:type
	// * object : an lci:individual, that is a concept of the life-cycle integration ontology on which SST is based on.

	// the created graph can be exported into a Turtle (*.ttl) file that has a readable text representation
	f, err := os.Create("helloworldwrite.ttl")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	err = graph.RdfWrite(f, sst.RdfFormatTurtle)
	if err != nil {
		log.Panic(err)
	}

	// alternatively the created graph can be exported into a binary SST file that is much faster to process compared to turtle.
	// for this we first create a file ...
	out, err := os.Create("helloworldwrite.sst")
	if err != nil {
		log.Panic(err)
	}
	// ... ensure that the file will be closed at the end ...
	defer func() {
		_ = out.Close()
	}()
	// ... and write the binary graph content out into the file.
	err = graph.SstWrite(out)
	if err != nil {
		log.Panic(err)
	}

	fmt.Printf("Done\n")
}
