// Code generated by tools/compiler/compiler.go DO NOT EDIT.

// Copyright Semantic STEP Technology GmbH, Germany & DCT Co., Ltd. Tianjin, China

package rdf

import (
	"reflect"
	"git.semanticstep.net/x/sst/sst"
)

type pkg struct{ sst.ElementInfo }

var RDFVocabulary = sst.Vocabulary{BaseIRI: "http://www.w3.org/1999/02/22-rdf-syntax-ns"}

var (
	PKG = sst.ElementPkg(pkg{})
	_   = PKG
)

// Definitions of rdf.Alt

type IsAlt interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23Alt()
}

type KindAlt interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23Alt()
}

type altI struct{ sst.ElementInfo }

func (altI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23Alt()   {}
func (altI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23Alt() {}
func (altI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Container()     {}
func (altI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()      {}

var altKindInterface reflect.Type

var Alt = altI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: RDFVocabulary, Name: "Alt"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of rdf.Bag

type IsBag interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23Bag()
}

type KindBag interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23Bag()
}

type bagI struct{ sst.ElementInfo }

func (bagI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23Bag()   {}
func (bagI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23Bag() {}
func (bagI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Container()     {}
func (bagI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()      {}

var bagKindInterface reflect.Type

var Bag = bagI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: RDFVocabulary, Name: "Bag"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of rdf.CompoundLiteral

type IsCompoundLiteral interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23CompoundLiteral()
}

type KindCompoundLiteral interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23CompoundLiteral()
}

type compoundLiteralI struct{ sst.ElementInfo }

func (compoundLiteralI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23CompoundLiteral()   {}
func (compoundLiteralI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23CompoundLiteral() {}
func (compoundLiteralI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()                  {}

var compoundLiteralKindInterface reflect.Type

var CompoundLiteral = compoundLiteralI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: RDFVocabulary, Name: "CompoundLiteral"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of rdf.HTML

type IsHTML interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23HTML()
}

type KindHTML interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23HTML()
}

type htmlI struct{ sst.ElementInfo }

func (htmlI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23HTML()   {}
func (htmlI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23HTML() {}
func (htmlI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Literal()        {}
func (htmlI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()       {}

var htmlKindInterface reflect.Type

var HTML = htmlI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: RDFVocabulary, Name: "HTML"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: true, AnIndividual: false,
}}

// Definitions of rdf.JSON

type IsJSON interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23JSON()
}

type KindJSON interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23JSON()
}

type jsonI struct{ sst.ElementInfo }

func (jsonI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23JSON()   {}
func (jsonI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23JSON() {}
func (jsonI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Literal()        {}
func (jsonI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()       {}

var jsonKindInterface reflect.Type

var JSON = jsonI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: RDFVocabulary, Name: "JSON"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: true, AnIndividual: false,
}}

// Definitions of rdf.List

type IsList interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23List()
}

type KindList interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23List()
}

type listI struct{ sst.ElementInfo }

func (listI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23List()   {}
func (listI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23List() {}
func (listI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()       {}

var listKindInterface reflect.Type

var List = listI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: RDFVocabulary, Name: "List"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of rdf.PlainLiteral

type IsPlainLiteral interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23PlainLiteral()
}

type KindPlainLiteral interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23PlainLiteral()
}

type plainLiteralI struct{ sst.ElementInfo }

func (plainLiteralI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23PlainLiteral()   {}
func (plainLiteralI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23PlainLiteral() {}
func (plainLiteralI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Literal()                {}
func (plainLiteralI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()               {}

var plainLiteralKindInterface reflect.Type

var PlainLiteral = plainLiteralI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: RDFVocabulary, Name: "PlainLiteral"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: true, AnIndividual: false,
}}

// Definitions of rdf.Property

type IsProperty interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23Property()
}

type KindProperty interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23Property()
}

type propertyI struct{ sst.ElementInfo }

func (propertyI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23Property()   {}
func (propertyI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23Property() {}
func (propertyI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()           {}

var propertyKindInterface reflect.Type

var Property = propertyI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: RDFVocabulary, Name: "Property"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of rdf.Seq

type IsSeq interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23Seq()
}

type KindSeq interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23Seq()
}

type seqI struct{ sst.ElementInfo }

func (seqI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23Seq()   {}
func (seqI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23Seq() {}
func (seqI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Container()     {}
func (seqI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()      {}

var seqKindInterface reflect.Type

var Seq = seqI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: RDFVocabulary, Name: "Seq"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of rdf.Statement

type IsStatement interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23Statement()
}

type KindStatement interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23Statement()
}

type statementI struct{ sst.ElementInfo }

func (statementI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23Statement()   {}
func (statementI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23Statement() {}
func (statementI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()            {}

var statementKindInterface reflect.Type

var Statement = statementI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: RDFVocabulary, Name: "Statement"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of rdf.XMLLiteral

type IsXMLLiteral interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23XMLLiteral()
}

type KindXMLLiteral interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23XMLLiteral()
}

type xmlliteralI struct{ sst.ElementInfo }

func (xmlliteralI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23XMLLiteral()   {}
func (xmlliteralI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23XMLLiteral() {}
func (xmlliteralI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Literal()              {}
func (xmlliteralI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()             {}

var xmlliteralKindInterface reflect.Type

var XMLLiteral = xmlliteralI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: RDFVocabulary, Name: "XMLLiteral"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: true, AnIndividual: false,
}}

// Definitions of rdf.direction

type IsDirection interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23direction()
}

type KindDirection interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23direction()
}

type directionI struct{ sst.ElementInfo }

func (directionI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23direction()   {}
func (directionI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23direction() {}
func (directionI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()            {}

var directionKindInterface reflect.Type

var Direction = directionI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: RDFVocabulary, Name: "direction"},
	ADomain:           CompoundLiteral,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of rdf.first

type IsFirst interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23first()
}

type KindFirst interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23first()
}

type firstI struct{ sst.ElementInfo }

func (firstI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23first()   {}
func (firstI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23first() {}
func (firstI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()        {}

var firstKindInterface reflect.Type

var First = firstI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: RDFVocabulary, Name: "first"},
	ADomain:           List,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of rdf.langString

type IsLangString interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23langString()
}

type KindLangString interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23langString()
}

type langStringI struct{ sst.ElementInfo }

func (langStringI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23langString()   {}
func (langStringI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23langString() {}
func (langStringI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Literal()              {}
func (langStringI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()             {}

var langStringKindInterface reflect.Type

var LangString = langStringI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: RDFVocabulary, Name: "langString"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: true, AnIndividual: false,
}}

// Definitions of rdf.language

type IsLanguage interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23language()
}

type KindLanguage interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23language()
}

type languageI struct{ sst.ElementInfo }

func (languageI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23language()   {}
func (languageI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23language() {}
func (languageI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()           {}

var languageKindInterface reflect.Type

var Language = languageI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: RDFVocabulary, Name: "language"},
	ADomain:           CompoundLiteral,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of rdf.nil

type IsNil interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23nil()
}

type KindNil interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23nil()
}

type nilI struct{ sst.ElementInfo }

func (nilI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23nil()   {}
func (nilI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23nil() {}
func (nilI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()      {}
func (nilI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2002_2F07_2Fowl_23Thing()                  {}

var nilKindInterface reflect.Type

var Nil = nilI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: RDFVocabulary, Name: "nil"},

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: true,
}}

// Definitions of rdf.object

type IsObject interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23object()
}

type KindObject interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23object()
}

type objectI struct{ sst.ElementInfo }

func (objectI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23object()   {}
func (objectI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23object() {}
func (objectI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()         {}

var objectKindInterface reflect.Type

var Object = objectI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: RDFVocabulary, Name: "object"},
	ADomain:           Statement,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of rdf.predicate

type IsPredicate interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23predicate()
}

type KindPredicate interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23predicate()
}

type predicateI struct{ sst.ElementInfo }

func (predicateI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23predicate()   {}
func (predicateI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23predicate() {}
func (predicateI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()            {}

var predicateKindInterface reflect.Type

var Predicate = predicateI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: RDFVocabulary, Name: "predicate"},
	ADomain:           Statement,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of rdf.rest

type IsRest interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23rest()
}

type KindRest interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23rest()
}

type restI struct{ sst.ElementInfo }

func (restI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23rest()   {}
func (restI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23rest() {}
func (restI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()       {}

var restKindInterface reflect.Type

var Rest = restI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: RDFVocabulary, Name: "rest"},
	ADomain:           List,
	ARange:            List,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of rdf.subject

type IsSubject interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23subject()
}

type KindSubject interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23subject()
}

type subjectI struct{ sst.ElementInfo }

func (subjectI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23subject()   {}
func (subjectI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23subject() {}
func (subjectI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()          {}

var subjectKindInterface reflect.Type

var Subject = subjectI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: RDFVocabulary, Name: "subject"},
	ADomain:           Statement,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of rdf.type

type IsType interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23type()
}

type KindType interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23type()
}

type typeI struct{ sst.ElementInfo }

func (typeI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23type()   {}
func (typeI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23type() {}
func (typeI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()       {}

var typeKindInterface reflect.Type

var Type = typeI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: RDFVocabulary, Name: "type"},

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of rdf.value

type IsValue interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23value()
}

type KindValue interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23value()
}

type valueI struct{ sst.ElementInfo }

func (valueI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23value()   {}
func (valueI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23value() {}
func (valueI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()        {}

var valueKindInterface reflect.Type

var Value = valueI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: RDFVocabulary, Name: "value"},

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}
