// Code generated by tools/compiler/compiler.go DO NOT EDIT.

// Copyright Semantic STEP Technology GmbH, Germany & DCT Co., Ltd. Tianjin, China

package color

import "git.semanticstep.net/x/sst/sst"

type pkg struct{ sst.ElementInfo }

var COLORVocabulary = sst.Vocabulary{BaseIRI: "http://ontology.semanticstep.net/color"}

var (
	PKG = sst.ElementPkg(pkg{})
	_   = PKG
)

var (
	Aliceblue = sst.Element{Vocabulary: COLORVocabulary, Name: "aliceblue"}
	Antiquewhite = sst.Element{Vocabulary: COLORVocabulary, Name: "antiquewhite"}
	Aqua = sst.Element{Vocabulary: COLORVocabulary, Name: "aqua"}
	Aquamarine = sst.Element{Vocabulary: COLORVocabulary, Name: "aquamarine"}
	Azure = sst.Element{Vocabulary: COLORVocabulary, Name: "azure"}
	Beige = sst.Element{Vocabulary: COLORVocabulary, Name: "beige"}
	Bisque = sst.Element{Vocabulary: COLORVocabulary, Name: "bisque"}
	Black = sst.Element{Vocabulary: COLORVocabulary, Name: "black"}
	Blanchedalmond = sst.Element{Vocabulary: COLORVocabulary, Name: "blanchedalmond"}
	Blue = sst.Element{Vocabulary: COLORVocabulary, Name: "blue"}
	Blueviolet = sst.Element{Vocabulary: COLORVocabulary, Name: "blueviolet"}
	Brown = sst.Element{Vocabulary: COLORVocabulary, Name: "brown"}
	Burlywood = sst.Element{Vocabulary: COLORVocabulary, Name: "burlywood"}
	Cadetblue = sst.Element{Vocabulary: COLORVocabulary, Name: "cadetblue"}
	Chartreuse = sst.Element{Vocabulary: COLORVocabulary, Name: "chartreuse"}
	Chocolate = sst.Element{Vocabulary: COLORVocabulary, Name: "chocolate"}
	Coral = sst.Element{Vocabulary: COLORVocabulary, Name: "coral"}
	Cornflowerblue = sst.Element{Vocabulary: COLORVocabulary, Name: "cornflowerblue"}
	Cornsilk = sst.Element{Vocabulary: COLORVocabulary, Name: "cornsilk"}
	Crimson = sst.Element{Vocabulary: COLORVocabulary, Name: "crimson"}
	Cyan = sst.Element{Vocabulary: COLORVocabulary, Name: "cyan"}
	Darkblue = sst.Element{Vocabulary: COLORVocabulary, Name: "darkblue"}
	Darkcyan = sst.Element{Vocabulary: COLORVocabulary, Name: "darkcyan"}
	Darkgoldenrod = sst.Element{Vocabulary: COLORVocabulary, Name: "darkgoldenrod"}
	Darkgray = sst.Element{Vocabulary: COLORVocabulary, Name: "darkgray"}
	Darkgreen = sst.Element{Vocabulary: COLORVocabulary, Name: "darkgreen"}
	Darkgrey = sst.Element{Vocabulary: COLORVocabulary, Name: "darkgrey"}
	Darkkhaki = sst.Element{Vocabulary: COLORVocabulary, Name: "darkkhaki"}
	Darkmagenta = sst.Element{Vocabulary: COLORVocabulary, Name: "darkmagenta"}
	Darkolivegreen = sst.Element{Vocabulary: COLORVocabulary, Name: "darkolivegreen"}
	Darkorange = sst.Element{Vocabulary: COLORVocabulary, Name: "darkorange"}
	Darkorchid = sst.Element{Vocabulary: COLORVocabulary, Name: "darkorchid"}
	Darkred = sst.Element{Vocabulary: COLORVocabulary, Name: "darkred"}
	Darksalmon = sst.Element{Vocabulary: COLORVocabulary, Name: "darksalmon"}
	Darkseagreen = sst.Element{Vocabulary: COLORVocabulary, Name: "darkseagreen"}
	Darkslateblue = sst.Element{Vocabulary: COLORVocabulary, Name: "darkslateblue"}
	Darkslategray = sst.Element{Vocabulary: COLORVocabulary, Name: "darkslategray"}
	Darkslategrey = sst.Element{Vocabulary: COLORVocabulary, Name: "darkslategrey"}
	Darkturquoise = sst.Element{Vocabulary: COLORVocabulary, Name: "darkturquoise"}
	Darkviolet = sst.Element{Vocabulary: COLORVocabulary, Name: "darkviolet"}
	Deeppink = sst.Element{Vocabulary: COLORVocabulary, Name: "deeppink"}
	Deepskyblue = sst.Element{Vocabulary: COLORVocabulary, Name: "deepskyblue"}
	Dimgray = sst.Element{Vocabulary: COLORVocabulary, Name: "dimgray"}
	Dimgrey = sst.Element{Vocabulary: COLORVocabulary, Name: "dimgrey"}
	Dodgerblue = sst.Element{Vocabulary: COLORVocabulary, Name: "dodgerblue"}
	Firebrick = sst.Element{Vocabulary: COLORVocabulary, Name: "firebrick"}
	Floralwhite = sst.Element{Vocabulary: COLORVocabulary, Name: "floralwhite"}
	Forestgreen = sst.Element{Vocabulary: COLORVocabulary, Name: "forestgreen"}
	Fuchsia = sst.Element{Vocabulary: COLORVocabulary, Name: "fuchsia"}
	Gainsboro = sst.Element{Vocabulary: COLORVocabulary, Name: "gainsboro"}
	Ghostwhite = sst.Element{Vocabulary: COLORVocabulary, Name: "ghostwhite"}
	Gold = sst.Element{Vocabulary: COLORVocabulary, Name: "gold"}
	Goldenrod = sst.Element{Vocabulary: COLORVocabulary, Name: "goldenrod"}
	Gray = sst.Element{Vocabulary: COLORVocabulary, Name: "gray"}
	Green = sst.Element{Vocabulary: COLORVocabulary, Name: "green"}
	Greenyellow = sst.Element{Vocabulary: COLORVocabulary, Name: "greenyellow"}
	Grey = sst.Element{Vocabulary: COLORVocabulary, Name: "grey"}
	Honeydew = sst.Element{Vocabulary: COLORVocabulary, Name: "honeydew"}
	Hotpink = sst.Element{Vocabulary: COLORVocabulary, Name: "hotpink"}
	Indianred = sst.Element{Vocabulary: COLORVocabulary, Name: "indianred"}
	Indigo = sst.Element{Vocabulary: COLORVocabulary, Name: "indigo"}
	Ivory = sst.Element{Vocabulary: COLORVocabulary, Name: "ivory"}
	Khaki = sst.Element{Vocabulary: COLORVocabulary, Name: "khaki"}
	Lavender = sst.Element{Vocabulary: COLORVocabulary, Name: "lavender"}
	Lavenderblush = sst.Element{Vocabulary: COLORVocabulary, Name: "lavenderblush"}
	Lawngreen = sst.Element{Vocabulary: COLORVocabulary, Name: "lawngreen"}
	Lemonchiffon = sst.Element{Vocabulary: COLORVocabulary, Name: "lemonchiffon"}
	Lightblue = sst.Element{Vocabulary: COLORVocabulary, Name: "lightblue"}
	Lightcoral = sst.Element{Vocabulary: COLORVocabulary, Name: "lightcoral"}
	Lightcyan = sst.Element{Vocabulary: COLORVocabulary, Name: "lightcyan"}
	Lightgoldenrodyellow = sst.Element{Vocabulary: COLORVocabulary, Name: "lightgoldenrodyellow"}
	Lightgray = sst.Element{Vocabulary: COLORVocabulary, Name: "lightgray"}
	Lightgreen = sst.Element{Vocabulary: COLORVocabulary, Name: "lightgreen"}
	Lightgrey = sst.Element{Vocabulary: COLORVocabulary, Name: "lightgrey"}
	Lightpink = sst.Element{Vocabulary: COLORVocabulary, Name: "lightpink"}
	Lightsalmon = sst.Element{Vocabulary: COLORVocabulary, Name: "lightsalmon"}
	Lightseagreen = sst.Element{Vocabulary: COLORVocabulary, Name: "lightseagreen"}
	Lightskyblue = sst.Element{Vocabulary: COLORVocabulary, Name: "lightskyblue"}
	Lightslategray = sst.Element{Vocabulary: COLORVocabulary, Name: "lightslategray"}
	Lightslategrey = sst.Element{Vocabulary: COLORVocabulary, Name: "lightslategrey"}
	Lightsteelblue = sst.Element{Vocabulary: COLORVocabulary, Name: "lightsteelblue"}
	Lightyellow = sst.Element{Vocabulary: COLORVocabulary, Name: "lightyellow"}
	Lime = sst.Element{Vocabulary: COLORVocabulary, Name: "lime"}
	Limegreen = sst.Element{Vocabulary: COLORVocabulary, Name: "limegreen"}
	Linen = sst.Element{Vocabulary: COLORVocabulary, Name: "linen"}
	Magenta = sst.Element{Vocabulary: COLORVocabulary, Name: "magenta"}
	Maroon = sst.Element{Vocabulary: COLORVocabulary, Name: "maroon"}
	Mediumaquamarine = sst.Element{Vocabulary: COLORVocabulary, Name: "mediumaquamarine"}
	Mediumblue = sst.Element{Vocabulary: COLORVocabulary, Name: "mediumblue"}
	Mediumorchid = sst.Element{Vocabulary: COLORVocabulary, Name: "mediumorchid"}
	Mediumpurple = sst.Element{Vocabulary: COLORVocabulary, Name: "mediumpurple"}
	Mediumseagreen = sst.Element{Vocabulary: COLORVocabulary, Name: "mediumseagreen"}
	Mediumslateblue = sst.Element{Vocabulary: COLORVocabulary, Name: "mediumslateblue"}
	Mediumspringgreen = sst.Element{Vocabulary: COLORVocabulary, Name: "mediumspringgreen"}
	Mediumturquoise = sst.Element{Vocabulary: COLORVocabulary, Name: "mediumturquoise"}
	Mediumvioletred = sst.Element{Vocabulary: COLORVocabulary, Name: "mediumvioletred"}
	Midnightblue = sst.Element{Vocabulary: COLORVocabulary, Name: "midnightblue"}
	Mintcream = sst.Element{Vocabulary: COLORVocabulary, Name: "mintcream"}
	Mistyrose = sst.Element{Vocabulary: COLORVocabulary, Name: "mistyrose"}
	Moccasin = sst.Element{Vocabulary: COLORVocabulary, Name: "moccasin"}
	Navajowhite = sst.Element{Vocabulary: COLORVocabulary, Name: "navajowhite"}
	Navy = sst.Element{Vocabulary: COLORVocabulary, Name: "navy"}
	Oldlace = sst.Element{Vocabulary: COLORVocabulary, Name: "oldlace"}
	Olive = sst.Element{Vocabulary: COLORVocabulary, Name: "olive"}
	Olivedrab = sst.Element{Vocabulary: COLORVocabulary, Name: "olivedrab"}
	Orange = sst.Element{Vocabulary: COLORVocabulary, Name: "orange"}
	Orangered = sst.Element{Vocabulary: COLORVocabulary, Name: "orangered"}
	Orchid = sst.Element{Vocabulary: COLORVocabulary, Name: "orchid"}
	Palegoldenrod = sst.Element{Vocabulary: COLORVocabulary, Name: "palegoldenrod"}
	Palegreen = sst.Element{Vocabulary: COLORVocabulary, Name: "palegreen"}
	Paleturquoise = sst.Element{Vocabulary: COLORVocabulary, Name: "paleturquoise"}
	Palevioletred = sst.Element{Vocabulary: COLORVocabulary, Name: "palevioletred"}
	Papayawhip = sst.Element{Vocabulary: COLORVocabulary, Name: "papayawhip"}
	Peachpuff = sst.Element{Vocabulary: COLORVocabulary, Name: "peachpuff"}
	Peru = sst.Element{Vocabulary: COLORVocabulary, Name: "peru"}
	Pink = sst.Element{Vocabulary: COLORVocabulary, Name: "pink"}
	Plum = sst.Element{Vocabulary: COLORVocabulary, Name: "plum"}
	Powderblue = sst.Element{Vocabulary: COLORVocabulary, Name: "powderblue"}
	Purple = sst.Element{Vocabulary: COLORVocabulary, Name: "purple"}
	Red = sst.Element{Vocabulary: COLORVocabulary, Name: "red"}
	Rosybrown = sst.Element{Vocabulary: COLORVocabulary, Name: "rosybrown"}
	Royalblue = sst.Element{Vocabulary: COLORVocabulary, Name: "royalblue"}
	Saddlebrown = sst.Element{Vocabulary: COLORVocabulary, Name: "saddlebrown"}
	Salmon = sst.Element{Vocabulary: COLORVocabulary, Name: "salmon"}
	Sandybrown = sst.Element{Vocabulary: COLORVocabulary, Name: "sandybrown"}
	Seagreen = sst.Element{Vocabulary: COLORVocabulary, Name: "seagreen"}
	Seashell = sst.Element{Vocabulary: COLORVocabulary, Name: "seashell"}
	Sienna = sst.Element{Vocabulary: COLORVocabulary, Name: "sienna"}
	Silver = sst.Element{Vocabulary: COLORVocabulary, Name: "silver"}
	Skyblue = sst.Element{Vocabulary: COLORVocabulary, Name: "skyblue"}
	Slateblue = sst.Element{Vocabulary: COLORVocabulary, Name: "slateblue"}
	Slategray = sst.Element{Vocabulary: COLORVocabulary, Name: "slategray"}
	Slategrey = sst.Element{Vocabulary: COLORVocabulary, Name: "slategrey"}
	Snow = sst.Element{Vocabulary: COLORVocabulary, Name: "snow"}
	Springgreen = sst.Element{Vocabulary: COLORVocabulary, Name: "springgreen"}
	Steelblue = sst.Element{Vocabulary: COLORVocabulary, Name: "steelblue"}
	Tan = sst.Element{Vocabulary: COLORVocabulary, Name: "tan"}
	Teal = sst.Element{Vocabulary: COLORVocabulary, Name: "teal"}
	Thistle = sst.Element{Vocabulary: COLORVocabulary, Name: "thistle"}
	Tomato = sst.Element{Vocabulary: COLORVocabulary, Name: "tomato"}
	Turquoise = sst.Element{Vocabulary: COLORVocabulary, Name: "turquoise"}
	Violet = sst.Element{Vocabulary: COLORVocabulary, Name: "violet"}
	Wheat = sst.Element{Vocabulary: COLORVocabulary, Name: "wheat"}
	White = sst.Element{Vocabulary: COLORVocabulary, Name: "white"}
	Whitesmoke = sst.Element{Vocabulary: COLORVocabulary, Name: "whitesmoke"}
	Yellow = sst.Element{Vocabulary: COLORVocabulary, Name: "yellow"}
	Yellowgreen = sst.Element{Vocabulary: COLORVocabulary, Name: "yellowgreen"}
)
