// Copyright Semantic STEP Technology GmbH, Germany & DCT Co., Ltd. Tianjin, China

// Code generated by goyacc -l -o iso10303p21y2016parser.go iso10303p21y2016.y. DO NOT EDIT.


// yacc source generated by ebnf2y[1]
// at 2021-09-29 07:43:56.497651 +0300 EEST m=+0.002046394
//
//  $ ~/go/bin/ebnf2y -start EXCHANGE_FILE -o iso10303p21y2016.y iso10303p21y2016.ebnf
//
//   [1]: http://modernc.org/ebnf2y

package p21

import __yyfmt__ "fmt"

import (
	"git.semanticstep.net/x/sst/sst"
	"git.semanticstep.net/x/sst/vocabularies/ssmeta"
	"git.semanticstep.net/x/sst/vocabularies/rdfs"
)

type (
	item interface{} // TODO insert real field(s)
)

type yySymType struct {
	yys  int
	item item
}

const ANCHOR_NAME = 57346
const BINARY = 57347
const CONSTANT_ENTITY_NAME = 57348
const CONSTANT_VALUE_NAME = 57349
const ENTITY_INSTANCE_NAME = 57350
const ENUMERATION = 57351
const INTEGER = 57352
const REAL = 57353
const RESOURCE = 57354
const SIGNATURE_CONTENT = 57355
const STANDARD_KEYWORD = 57356
const STRING = 57357
const TAG_NAME = 57358
const USER_DEFINED_KEYWORD = 57359
const VALUE_INSTANCE_NAME = 57360
const ANCHOR = 57361
const DATA = 57362
const ENDISO1030321 = 57363
const ENDSEC = 57364
const HEADER = 57365
const ISO1030321 = 57366
const REFERENCE = 57367
const SIGNATURE = 57368

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"ANCHOR_NAME",
	"BINARY",
	"CONSTANT_ENTITY_NAME",
	"CONSTANT_VALUE_NAME",
	"ENTITY_INSTANCE_NAME",
	"ENUMERATION",
	"INTEGER",
	"REAL",
	"RESOURCE",
	"SIGNATURE_CONTENT",
	"STANDARD_KEYWORD",
	"STRING",
	"TAG_NAME",
	"USER_DEFINED_KEYWORD",
	"VALUE_INSTANCE_NAME",
	"ANCHOR",
	"DATA",
	"ENDISO1030321",
	"ENDSEC",
	"HEADER",
	"ISO1030321",
	"REFERENCE",
	"SIGNATURE",
	"'('",
	"')'",
	"';'",
	"','",
	"'='",
	"'$'",
	"'{'",
	"':'",
	"'}'",
	"'*'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//TODO remove demo stuff below

// type (
// 	ANCHOR0 interface{}
// 	ANCHOR1 interface{}
// 	ANCHOR_ITEM interface{}
// 	ANCHOR_ITEM_LIST interface{}
// 	ANCHOR_ITEM_LIST1 interface{}
// 	ANCHOR_ITEM_LIST11 interface{}
// 	ANCHOR_LIST interface{}
// 	ANCHOR_LIST1 interface{}
// 	ANCHOR_SECTION interface{}
// 	ANCHOR_TAG interface{}
// 	COMPLEX_ENTITY_INSTANCE interface{}
// 	DATA_SECTION interface{}
// 	DATA_SECTION1 interface{}
// 	ENTITY_INSTANCE interface{}
// 	ENTITY_INSTANCE_START interface{}
// 	ENTITY_INSTANCE_LIST interface{}
// 	ENTITY_INSTANCE_LIST1 interface{}
// 	EXCHANGE_FILE interface{}
// 	EXCHANGE_FILE1 interface{}
// 	EXCHANGE_FILE2 interface{}
// 	EXCHANGE_FILE3 interface{}
// 	EXCHANGE_FILE4 interface{}
// 	HEADER_ENTITY interface{}
// 	HEADER_ENTITY1 interface{}
// 	HEADER_ENTITY_LIST interface{}
// 	HEADER_ENTITY_LIST1 interface{}
// 	HEADER_SECTION interface{}
// 	HEADER_SECTION1 interface{}
// 	KEYWORD interface{}
// 	LHS_OCCURRENCE_NAME interface{}
// 	LHS_OCCURRENCE_NAME1 interface{}
// 	LIST interface{}
// 	LIST1 interface{}
// 	LIST_START interface{}
// 	LIST11 interface{}
// 	OMITTED_PARAMETER interface{}
// 	PARAMETER interface{}
// 	PARAMETER_LIST interface{}
// 	PARAMETER_LIST1 interface{}
// 	REFERENCE0 interface{}
// 	REFERENCE_LIST interface{}
// 	REFERENCE_LIST1 interface{}
// 	REFERENCE_SECTION interface{}
// 	RHS_OCCURRENCE_NAME interface{}
// 	RHS_OCCURRENCE_NAME1 interface{}
// 	SIGNATURE_SECTION interface{}
// 	SIMPLE_ENTITY_INSTANCE interface{}
// 	SIMPLE_RECORD interface{}
// 	SIMPLE_RECORD_START interface{}
// 	SIMPLE_RECORD1 interface{}
// 	SIMPLE_RECORD_LIST interface{}
// 	SIMPLE_RECORD_LIST1 interface{}
// 	SUBSUPER_RECORD interface{}
// 	Start interface{}
// 	TYPED_PARAMETER interface{}
// 	UNTYPED_PARAMETER interface{}
// )

// End of demo stuff

var yyExca = [...]int16{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 19,
	28, 11,
	-2, 93,
	-1, 44,
	28, 70,
	-2, 93,
	-1, 126,
	28, 58,
	-2, 93,
	-1, 143,
	28, 60,
	-2, 56,
}

const yyPrivate = 57344

const yyLast = 153

var yyAct = [...]uint8{
	124, 38, 72, 10, 28, 29, 9, 40, 47, 48,
	45, 39, 35, 36, 145, 131, 18, 37, 107, 130,
	46, 71, 109, 59, 120, 26, 101, 86, 134, 49,
	133, 144, 106, 62, 34, 92, 85, 65, 42, 142,
	141, 78, 47, 48, 45, 77, 74, 75, 80, 112,
	67, 76, 110, 105, 46, 88, 63, 129, 87, 70,
	19, 79, 15, 82, 91, 3, 5, 115, 73, 114,
	83, 53, 52, 50, 8, 93, 23, 57, 12, 119,
	102, 11, 94, 118, 79, 97, 25, 58, 33, 128,
	31, 98, 99, 100, 30, 1, 127, 125, 143, 137,
	135, 126, 122, 90, 43, 14, 22, 113, 21, 54,
	64, 32, 89, 44, 66, 41, 56, 55, 60, 4,
	84, 61, 79, 132, 27, 68, 20, 13, 138, 6,
	2, 136, 139, 79, 140, 104, 103, 117, 121, 116,
	69, 51, 123, 108, 146, 7, 17, 16, 111, 96,
	81, 95, 24,
}

var yyPact = [...]int16{
	41, -1000, -1000, 43, 55, 64, 37, -1000, -1000, 64,
	33, -1000, -1000, -1000, -1000, -1000, 54, 82, 64, 2,
	52, 49, 69, -1000, -1000, -8, 64, 28, -1000, -1000,
	-1000, -1000, -1000, 64, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, 2, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 32, -1000, -1000, -10, -1000, -1000, -1000, 36,
	48, -1000, -1000, 7, -3, 31, 27, -1000, 38, 6,
	2, 70, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 36, -1000, 64, -1000, 2, 2, -1000, -4,
	-1000, 67, -1000, 25, 3, -11, 24, -1000, -1000, -1000,
	21, 2, 47, 45, 75, -1000, -1000, -1000, -1000, 63,
	-1000, -6, -1000, -1000, -1000, -1000, -1000, 30, -12, -19,
	36, -1000, -1000, -1000, 1, -1, 2, -1000, 64, -1000,
	-1000, 36, -1000, -1000, -1000, 12, -1000, 11, -1000, 4,
	-21, -1000, -1000, -1000, -1000, -1000, -1000,
}

var yyPgo = [...]uint8{
	0, 152, 151, 2, 150, 149, 148, 147, 146, 145,
	143, 142, 141, 140, 139, 138, 137, 136, 135, 130,
	129, 127, 126, 125, 6, 124, 121, 120, 119, 118,
	3, 117, 116, 115, 114, 113, 112, 111, 5, 4,
	110, 109, 108, 106, 105, 1, 104, 103, 102, 0,
	101, 100, 99, 98, 97, 96, 95, 94, 90, 89,
	88,
}

var yyR1 = [...]int8{
	0, 19, 20, 20, 21, 21, 22, 22, 23, 23,
	24, 25, 25, 26, 27, 27, 28, 29, 29, 9,
	7, 8, 8, 4, 5, 5, 6, 6, 1, 2,
	2, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	10, 12, 13, 13, 17, 18, 18, 14, 16, 15,
	15, 11, 55, 54, 48, 49, 59, 50, 51, 51,
	52, 53, 53, 30, 30, 31, 32, 32, 33, 35,
	34, 34, 36, 36, 37, 38, 38, 38, 39, 40,
	40, 41, 42, 43, 43, 44, 45, 46, 46, 46,
	46, 47, 56, 60, 57, 58, 58, 58, 58, 58,
	58, 58, 58,
}

var yyR2 = [...]int8{
	0, 7, 0, 1, 0, 1, 0, 2, 0, 2,
	5, 0, 1, 2, 0, 2, 6, 0, 1, 3,
	1, 0, 2, 3, 0, 2, 0, 3, 5, 0,
	2, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	5, 5, 0, 3, 1, 0, 2, 2, 2, 1,
	1, 2, 1, 3, 2, 3, 0, 3, 0, 1,
	2, 0, 2, 1, 1, 1, 1, 1, 3, 1,
	0, 2, 0, 3, 1, 1, 1, 1, 2, 0,
	3, 4, 1, 0, 2, 3, 1, 1, 1, 1,
	1, 3, 1, 0, 5, 1, 1, 1, 1, 1,
	1, 1, 1,
}

var yyChk = [...]int16{
	-1000, -56, -19, 24, -28, 23, -20, -9, 19, -24,
	-30, 17, 14, -21, -44, 25, -7, -8, -24, 27,
	-22, -42, -43, 22, -1, 4, -24, -25, -39, -38,
	-57, -58, -37, -60, 32, 10, 11, 15, -45, 9,
	5, -33, 36, -46, -35, 8, 18, 6, 7, 27,
	21, -12, 20, 22, -41, -31, -32, 8, 18, 31,
	-29, -26, -24, 28, -40, -30, -34, -38, -23, -13,
	27, 31, -3, 32, 10, 11, 15, 9, 5, -45,
	12, -4, 27, 22, -27, 29, 30, 27, 28, -36,
	-47, 26, 29, -39, 12, -2, -5, -3, -24, -38,
	-38, 30, 13, -17, -18, 28, 29, 29, -10, 33,
	28, -6, 28, -38, 22, 22, -14, -16, 8, 16,
	30, -15, -48, -11, -49, -54, -50, -55, -59, 27,
	31, 34, -3, 29, 29, -51, -39, -52, -49, -30,
	-3, 28, 28, -53, 27, 35, -49,
}

var yyDef = [...]int8{
	0, -2, 92, 0, 2, 0, 4, 3, 21, 0,
	0, 63, 64, 6, 5, 83, 0, 20, 0, -2,
	0, 0, 82, 19, 22, 0, 17, 0, 12, 79,
	75, 76, 77, 0, 95, 96, 97, 98, 99, 100,
	101, 102, 74, 86, -2, 87, 88, 89, 90, 69,
	8, 7, 42, 85, 84, 0, 65, 66, 67, 0,
	0, 18, 14, 0, 78, 0, 0, 72, 1, 0,
	93, 0, 29, 31, 32, 33, 34, 35, 36, 37,
	38, 39, 24, 16, 13, 10, 93, 93, 68, 71,
	9, 0, 45, 0, 0, 0, 0, 26, 15, 80,
	0, 93, 0, 0, 44, 43, 81, 28, 30, 0,
	23, 25, 94, 73, 91, 41, 46, 56, 0, 0,
	0, 47, 49, 50, 0, 0, -2, 56, 0, 52,
	48, 0, 27, 54, 51, 0, 59, 0, 61, 0,
	0, 55, 53, -2, 57, 40, 62,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 32, 3, 3, 3,
	27, 28, 36, 3, 30, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 34, 29,
	3, 31, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 33, 3, 35,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-7 : yypt+1]
		{
			// $$ = []EXCHANGE_FILE{"ISO-10303-21;", $2, $3, $4, $5, "END-ISO-10303-21;", $7} //TODO 32
		}
	case 2:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			// $$ = nil //TODO 33
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// $$ = $1 //TODO 34
		}
	case 4:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			// $$ = nil //TODO 35
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// $$ = $1 //TODO 36
		}
	case 6:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			// $$ = []EXCHANGE_FILE3(nil) //TODO 37
		}
	case 7:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			// $$ = append($1.([]EXCHANGE_FILE3), $2) //TODO 38
		}
	case 8:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			// $$ = []EXCHANGE_FILE4(nil) //TODO 39
		}
	case 9:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			// $$ = append($1.([]EXCHANGE_FILE4), $2) //TODO 40
		}
	case 10:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			// $$ = []HEADER_ENTITY{$1, "(", $3, ")", ";"} //TODO 41
		}
	case 11:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			// $$ = nil //TODO 42
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// $$ = $1 //TODO 43
		}
	case 13:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			// $$ = []HEADER_ENTITY_LIST{$1, $2} //TODO 44
		}
	case 14:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			// $$ = []HEADER_ENTITY_LIST1(nil) //TODO 45
		}
	case 15:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			// $$ = append($1.([]HEADER_ENTITY_LIST1), $2) //TODO 46
		}
	case 16:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			// $$ = []HEADER_SECTION{"HEADER;", $2, $3, $4, $5, "ENDSEC;"} //TODO 47
		}
	case 17:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			// $$ = nil //TODO 48
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// $$ = $1 //TODO 49
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			// $$ = []ANCHOR_SECTION{"ANCHOR;", $2, "ENDSEC;"} //TODO 21
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// $$ = $1 //TODO 18
		}
	case 21:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			// $$ = []ANCHOR_LIST1(nil) //TODO 19
		}
	case 22:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			// $$ = append($1.([]ANCHOR_LIST1), $2) //TODO 20
		}
	case 23:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			// $$ = []ANCHOR_ITEM_LIST{"(", $2, ")"} //TODO 13
		}
	case 24:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			// $$ = nil //TODO 14
		}
	case 25:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			// $$ = []ANCHOR_ITEM_LIST1{$1, $2} //TODO 15
		}
	case 26:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			// $$ = []ANCHOR_ITEM_LIST11(nil) //TODO 16
		}
	case 27:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			// $$ = append($1.([]ANCHOR_ITEM_LIST11), ",", $3) //TODO 17
		}
	case 28:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			// $$ = []ANCHOR0{$1, "=", $3, $4, ";"} //TODO 1
		}
	case 29:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			// $$ = []ANCHOR1(nil) //TODO 2
		}
	case 30:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			// $$ = append($1.([]ANCHOR1), $2) //TODO 3
		}
	case 31:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// $$ = "$" //TODO 4
		}
	case 32:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// $$ = $1 //TODO 5
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// $$ = $1 //TODO 6
		}
	case 34:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// $$ = $1 //TODO 7
		}
	case 35:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// $$ = $1 //TODO 8
		}
	case 36:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// $$ = $1 //TODO 9
		}
	case 37:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// $$ = $1 //TODO 10
		}
	case 38:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// $$ = $1 //TODO 11
		}
	case 39:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// $$ = $1 //TODO 12
		}
	case 40:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			// $$ = []ANCHOR_TAG{"{", $2, ":", $4, "}"} //TODO 22
		}
	case 41:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			// $$ = []DATA_SECTION{"DATA", $2, ";", $4, "ENDSEC;"} //TODO 24
		}
	case 42:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			// $$ = nil //TODO 25
		}
	case 43:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			// $$ = []DATA_SECTION1{"(", $2, ")"} //TODO 26
		}
	case 44:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// $$ = $1 //TODO 29
		}
	case 45:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			// $$ = []ENTITY_INSTANCE_LIST1(nil) //TODO 30
		}
	case 46:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			// $$ = append($1.([]ENTITY_INSTANCE_LIST1), $2) //TODO 31
		}
	case 47:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			// $$ = $1 //TODO 28d
			yylexer(yylex).sd.instanceMode = parserNoInstanceMode // end of processing an ENTITY_INSTANCE
			yylexer(yylex).sd.instanceActual = nil
			yylexer(yylex).sd.instanceValue = nil
		}
	case 48:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			// $$ = []HEADER_SECTION{$1, "="} //TODO 27a
			sd := yylexer(yylex).sd
			sd.instanceMode = parserSimpleEntityInstance // assume SIMPLE_ENTITY_INSTANCE
			sd.instanceActual = sd.instanceValue
		}
	case 49:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// $$ = $1 //TODO 27b
		}
	case 50:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// $$ = $1 //TODO 28c
		}
	case 51:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			// $$ = []COMPLEX_ENTITY_INSTANCE{$1, ";"} //TODO 23
			// __yyfmt__.Printf(" complex entity instance = %s\n", $$)
		}
	case 52:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// $$ = "(" //TODO 85b
			yylexer(yylex).sd.instanceMode = parserComplexEntityInstance // COMPLEX_ENTITY_INSTANCE has started
		}
	case 53:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			// $$ = []SUBSUPER_RECORD{"(", $2, ")"} //TODO 85a
		}
	case 54:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			// $$ = []SIMPLE_ENTITY_INSTANCE{$1, ";"} //TODO 78
			// __yyfmt__.Printf(" simple entity instance = %s\n", $$)
		}
	case 55:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			// $$ = []SIMPLE_RECORD{$1, $2, ")"} //TODO 79
			sd := yylexer(yylex).sd
			if len(sd.attributeValues) > 0 {
				switch sd.instanceMode {
				case parserSimpleEntityInstance:
					col:= sd.graph.CreateCollection(sd.attributeValues...)
					sd.instanceActual.AddStatement(ssmeta.AttributeValues, col)
				case parserComplexEntityInstance:
					col:= sd.graph.CreateCollection(sd.attributeValues...)
					sd.entityValueActual.AddStatement(ssmeta.AttributeValues, col)
				case parserNoInstanceMode:
				}
			}
		}
	case 56:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yylexer(yylex).sd.keywordType = parserEntity // ssmeta.Entity
		}
	case 57:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			// $$ = []SIMPLE_RECORD_START{$2, "("} //TODO 79a
			sd := yylexer(yylex).sd
			// __yyfmt__.Printf(" => instanceActual = %v\n", sd.instanceActual)
			// __yyfmt__.Printf(" => entityActual = %v\n", sd.entityActual)
			switch sd.instanceMode {
			case parserSimpleEntityInstance:
				sd.instanceActual.AddStatement(ssmeta.EntityInstanceType, sd.entityActual)
				sd.entityActual = nil // clear for next instance/value
				sd.attributeValues = nil
			case parserComplexEntityInstance:
				sd.entityValueActual = sd.graph.CreateIRINode("", ssmeta.SingleEntityValue)
				sd.instanceActual.AddStatement(ssmeta.ComplexInstanceValue, sd.entityValueActual)
				sd.entityValueActual.AddStatement(ssmeta.SingleEntityValueType, sd.entityActual)
				sd.attributeValues = nil
			case parserNoInstanceMode:
			}
			sd.keywordType = parserKeywordNoType
		}
	case 58:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			// $$ = nil //TODO 80
		}
	case 59:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// $$ = $1 //TODO 81
		}
	case 60:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			// $$ = []SIMPLE_RECORD_LIST{$1, $2} //TODO 82
		}
	case 61:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			// $$ = []SIMPLE_RECORD_LIST1(nil) //TODO 83
		}
	case 62:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			// $$ = append($1.([]SIMPLE_RECORD_LIST1), $2) //TODO 84
		}
	case 63:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// $$ = $1 //TODO 50
		}
	case 64:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// $$ = $1 //TODO 51
			// __yyfmt__.Printf(" keyword = %s", $$)
			sd := yylexer(yylex).sd
			if sd.instanceMode > parserNoInstanceMode {
				switch sd.keywordType {
				case parserEntity:
					// __yyfmt__.Printf(" //entity\n")
					entity := sd.entityMap[sd.stringValue]
					if entity == nil {
						entity = sd.graph.CreateIRINode("", ssmeta.Entity)
						sd.entityMap[sd.stringValue] = entity
						entity.AddStatement(rdfs.Label, sst.String(sd.stringValue))
					}
					sd.entityActual = entity
				case parserDefinedType:
					// __yyfmt__.Printf(" //definedType\n")
					definedType := sd.definedTypeMap[sd.stringValue]
					if definedType == nil {
						definedType = sd.graph.CreateIRINode("", ssmeta.DefinedType)
						sd.definedTypeMap[sd.stringValue] = definedType
						definedType.AddStatement(rdfs.Label, sst.String(sd.stringValue))
					}
					sd.definedTypeActual = definedType
					sd.attributeValues = append(sd.attributeValues, definedType)
				case parserKeywordNoType:
					// __yyfmt__.Printf(" //no-type\n")
				}
			} else {
				// __yyfmt__.Printf(" //not instance mode\n")
			}
		}
	case 65:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// $$ = $1 //TODO 52
		}
	case 66:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// $$ = $1 //TODO 53
		}
	case 67:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// $$ = $1 //TODO 54
		}
	case 68:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			// $$ = []LIST{$1, $2, ")"} //TODO 55
			sd := yylexer(yylex).sd
			if sd.instanceMode > parserNoInstanceMode {
				attributeValues := sd.popAttributeValues()
				var val sst.Term
				if len(attributeValues) > 0 {
					val= sd.graph.CreateCollection(attributeValues...)
				} else {
					val,_ = sd.graph.Stage().IBNodeByVocabulary(ssmeta.EmptyAgggregateValue)
				}
				// __yyfmt__.Printf(" LIST_END =%v\n", val)
				sd.attributeValues = append(sd.attributeValues, val)
			}
		}
	case 69:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// $$ = []LIST_START{"("} //TODO 55
			sd := yylexer(yylex).sd
			if sd.instanceMode > parserNoInstanceMode {
				sd.pushAttributeValues()
				// __yyfmt__.Printf(" LIST_START ")
			}
		}
	case 70:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			// $$ = nil //TODO 56
		}
	case 71:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			// $$ = []LIST1{$1, $2} //TODO 57
		}
	case 72:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			// $$ = []LIST11(nil) //TODO 58
		}
	case 73:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			// $$ = append($1.([]LIST11), ",", $3) //TODO 59
		}
	case 74:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// $$ = "*" //TODO 60
			sd := yylexer(yylex).sd
			if sd.instanceMode > parserNoInstanceMode {
				stage := sd.graph.Stage()
				ib,_ := stage.IBNodeByVocabulary(ssmeta.DerivedValue)
				sd.attributeValues = append(sd.attributeValues, ib)

			}
		}
	case 75:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// $$ = $1 //TODO 61
		}
	case 76:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// $$ = $1 //TODO 62
		}
	case 77:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// $$ = $1 //TODO 63
		}
	case 78:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			// $$ = []PARAMETER_LIST{$1, $2} //TODO 64
		}
	case 79:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			// $$ = []PARAMETER_LIST1(nil) //TODO 65
		}
	case 80:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			// $$ = append($1.([]PARAMETER_LIST1), ",", $3) //TODO 66
		}
	case 81:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			// $$ = []REFERENCE0{$1, "=", $3, ";"} //TODO 67
		}
	case 82:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// $$ = $1 //TODO 68
		}
	case 83:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			// $$ = []REFERENCE_LIST1(nil) //TODO 69
		}
	case 84:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			// $$ = append($1.([]REFERENCE_LIST1), $2) //TODO 70
		}
	case 85:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			// $$ = []REFERENCE_SECTION{"REFERENCE;", $2, "ENDSEC;"} //TODO 71
		}
	case 86:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// $$ = $1 //TODO 72
		}
	case 87:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// $$ = $1 //TODO 73
			sd := yylexer(yylex).sd
			if sd.instanceMode > parserNoInstanceMode {
				sd.attributeValues = append(sd.attributeValues, sd.instanceValue)
			}
		}
	case 88:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// $$ = $1 //TODO 74
		}
	case 89:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// $$ = $1 //TODO 75
		}
	case 90:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// $$ = $1 //TODO 76
		}
	case 91:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			// $$ = []SIGNATURE_SECTION{"SIGNATURE", $2, "ENDSEC;"} //TODO 77
		}
	case 92:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylexer(yylex).parserResult = yyDollar[1].item //TODO 86
		}
	case 93:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			sd := yylexer(yylex).sd
			if sd.instanceMode > parserNoInstanceMode {
				sd.keywordType = parserDefinedType
				sd.definedTypeNesting++
				sd.pushAttributeValues()
			}
		}
	case 94:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			// $$ = []TYPED_PARAMETER{$2, "(", $4, ")"} //TODO 87
			sd := yylexer(yylex).sd
			if sd.instanceMode > parserNoInstanceMode {
				sd.keywordType = parserKeywordNoType
				sd.definedTypeNesting--
				attributeValues := sd.popAttributeValues()
				if sd.definedTypeNesting == 0 { // end of possible chain of defined types
					var val sst.Term
					if len(attributeValues) > 0 {
						val= sd.graph.CreateCollection(attributeValues...)
					} else {
						val,_ =sd.graph.Stage().IBNodeByVocabulary(ssmeta.EmptyAgggregateValue)
					}
					sd.attributeValues = append(sd.attributeValues, val)
					// __yyfmt__.Printf(" LIST_END =%v\n", val)
				} else {
					for i := 0; i < len(attributeValues); i++ {
						sd.attributeValues = append(sd.attributeValues, attributeValues[i])
					}
					// __yyfmt__.Printf(" LIST_END SOMEHOW INTERMEDIATE\n")
				}
			}
			sd.entityActual = nil
			sd.definedTypeActual = nil
		}
	case 95:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// $$ = "$" //TODO 88
			sd := yylexer(yylex).sd
			if sd.instanceMode > parserNoInstanceMode {
				stage := sd.graph.Stage()
				ib,_ := stage.IBNodeByVocabulary(ssmeta.IndeterminateValue)
				sd.attributeValues = append(sd.attributeValues, ib)
			}
		}
	case 96:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// $$ = $1 //TODO 89
			sd := yylexer(yylex).sd
			if sd.instanceMode > parserNoInstanceMode {
				sd.attributeValues = append(sd.attributeValues, sst.Integer(sd.integerValue))
			}
		}
	case 97:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// $$ = $1 //TODO 90
			sd := yylexer(yylex).sd
			if sd.instanceMode > parserNoInstanceMode {
				sd.attributeValues = append(sd.attributeValues, sst.Double(sd.realValue))
			}
		}
	case 98:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// $$ = $1 //TODO 91
			sd := yylexer(yylex).sd
			if sd.instanceMode > parserNoInstanceMode {
				sd.attributeValues = append(sd.attributeValues, sst.String(sd.stringValue))
			}
		}
	case 99:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// $$ = $1 //TODO 92
		}
	case 100:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// $$ = $1 //TODO 93
			sd := yylexer(yylex).sd
			if sd.instanceMode > parserNoInstanceMode {
				enumerationValue := sd.enumerationValueMap[sd.stringValue]
				if enumerationValue == nil {
					enumerationValue= sd.graph.CreateIRINode("", ssmeta.EnumerationValue)
					sd.enumerationValueMap[sd.stringValue] = enumerationValue
					enumerationValue.AddStatement(rdfs.Label, sst.String(sd.stringValue))
				}
				sd.attributeValues = append(sd.attributeValues, enumerationValue)
			}
		}
	case 101:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// $$ = $1 //TODO 94
			sd := yylexer(yylex).sd
			if sd.instanceMode > parserNoInstanceMode {
				sd.attributeValues = append(sd.attributeValues, sst.String("BINARY"))
			}
		}
	case 102:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// $$ = $1 //TODO 95
		}
	}
	goto yystack /* stack new state and value */
}
