// Copyright Semantic STEP Technology GmbH, Germany & DCT Co., Ltd. Tianjin, China

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: repository.proto

package bboltproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RepoManagerService_ListRepos_FullMethodName  = "/sst.repository.RepoManagerService/ListRepos"
	RepoManagerService_CreateRepo_FullMethodName = "/sst.repository.RepoManagerService/CreateRepo"
	RepoManagerService_DeleteRepo_FullMethodName = "/sst.repository.RepoManagerService/DeleteRepo"
)

// RepoManagerServiceClient is the client API for RepoManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RepoManagerServiceClient interface {
	ListRepos(ctx context.Context, in *ListReposRequest, opts ...grpc.CallOption) (*ListReposReply, error)
	CreateRepo(ctx context.Context, in *CreateRepoRequest, opts ...grpc.CallOption) (*CreateRepoReply, error)
	DeleteRepo(ctx context.Context, in *DeleteRepoRequest, opts ...grpc.CallOption) (*DeleteRepoReply, error)
}

type repoManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRepoManagerServiceClient(cc grpc.ClientConnInterface) RepoManagerServiceClient {
	return &repoManagerServiceClient{cc}
}

func (c *repoManagerServiceClient) ListRepos(ctx context.Context, in *ListReposRequest, opts ...grpc.CallOption) (*ListReposReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReposReply)
	err := c.cc.Invoke(ctx, RepoManagerService_ListRepos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repoManagerServiceClient) CreateRepo(ctx context.Context, in *CreateRepoRequest, opts ...grpc.CallOption) (*CreateRepoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRepoReply)
	err := c.cc.Invoke(ctx, RepoManagerService_CreateRepo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repoManagerServiceClient) DeleteRepo(ctx context.Context, in *DeleteRepoRequest, opts ...grpc.CallOption) (*DeleteRepoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRepoReply)
	err := c.cc.Invoke(ctx, RepoManagerService_DeleteRepo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RepoManagerServiceServer is the server API for RepoManagerService service.
// All implementations must embed UnimplementedRepoManagerServiceServer
// for forward compatibility.
type RepoManagerServiceServer interface {
	ListRepos(context.Context, *ListReposRequest) (*ListReposReply, error)
	CreateRepo(context.Context, *CreateRepoRequest) (*CreateRepoReply, error)
	DeleteRepo(context.Context, *DeleteRepoRequest) (*DeleteRepoReply, error)
	mustEmbedUnimplementedRepoManagerServiceServer()
}

// UnimplementedRepoManagerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRepoManagerServiceServer struct{}

func (UnimplementedRepoManagerServiceServer) ListRepos(context.Context, *ListReposRequest) (*ListReposReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRepos not implemented")
}
func (UnimplementedRepoManagerServiceServer) CreateRepo(context.Context, *CreateRepoRequest) (*CreateRepoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRepo not implemented")
}
func (UnimplementedRepoManagerServiceServer) DeleteRepo(context.Context, *DeleteRepoRequest) (*DeleteRepoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRepo not implemented")
}
func (UnimplementedRepoManagerServiceServer) mustEmbedUnimplementedRepoManagerServiceServer() {}
func (UnimplementedRepoManagerServiceServer) testEmbeddedByValue()                            {}

// UnsafeRepoManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RepoManagerServiceServer will
// result in compilation errors.
type UnsafeRepoManagerServiceServer interface {
	mustEmbedUnimplementedRepoManagerServiceServer()
}

func RegisterRepoManagerServiceServer(s grpc.ServiceRegistrar, srv RepoManagerServiceServer) {
	// If the following call pancis, it indicates UnimplementedRepoManagerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RepoManagerService_ServiceDesc, srv)
}

func _RepoManagerService_ListRepos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReposRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepoManagerServiceServer).ListRepos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RepoManagerService_ListRepos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepoManagerServiceServer).ListRepos(ctx, req.(*ListReposRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RepoManagerService_CreateRepo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRepoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepoManagerServiceServer).CreateRepo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RepoManagerService_CreateRepo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepoManagerServiceServer).CreateRepo(ctx, req.(*CreateRepoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RepoManagerService_DeleteRepo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRepoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepoManagerServiceServer).DeleteRepo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RepoManagerService_DeleteRepo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepoManagerServiceServer).DeleteRepo(ctx, req.(*DeleteRepoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RepoManagerService_ServiceDesc is the grpc.ServiceDesc for RepoManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RepoManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sst.repository.RepoManagerService",
	HandlerType: (*RepoManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRepos",
			Handler:    _RepoManagerService_ListRepos_Handler,
		},
		{
			MethodName: "CreateRepo",
			Handler:    _RepoManagerService_CreateRepo_Handler,
		},
		{
			MethodName: "DeleteRepo",
			Handler:    _RepoManagerService_DeleteRepo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "repository.proto",
}

const (
	DatasetService_RemoveBranch_FullMethodName               = "/sst.repository.DatasetService/RemoveBranch"
	DatasetService_SetBranch_FullMethodName                  = "/sst.repository.DatasetService/SetBranch"
	DatasetService_GetBranches_FullMethodName                = "/sst.repository.DatasetService/GetBranches"
	DatasetService_GetLeafCommits_FullMethodName             = "/sst.repository.DatasetService/GetLeafCommits"
	DatasetService_GetBleveInfo_FullMethodName               = "/sst.repository.DatasetService/GetBleveInfo"
	DatasetService_ListDatasets_FullMethodName               = "/sst.repository.DatasetService/ListDatasets"
	DatasetService_GetDataset_FullMethodName                 = "/sst.repository.DatasetService/GetDataset"
	DatasetService_CreateDataset_FullMethodName              = "/sst.repository.DatasetService/CreateDataset"
	DatasetService_FetchDatasets_FullMethodName              = "/sst.repository.DatasetService/FetchDatasets"
	DatasetService_PushDatasets_FullMethodName               = "/sst.repository.DatasetService/PushDatasets"
	DatasetService_GetRepositoryInfo_FullMethodName          = "/sst.repository.DatasetService/GetRepositoryInfo"
	DatasetService_GetRepositoryLog_FullMethodName           = "/sst.repository.DatasetService/GetRepositoryLog"
	DatasetService_DocumentSet_FullMethodName                = "/sst.repository.DatasetService/DocumentSet"
	DatasetService_Document_FullMethodName                   = "/sst.repository.DatasetService/Document"
	DatasetService_Documents_FullMethodName                  = "/sst.repository.DatasetService/Documents"
	DatasetService_DocumentDelete_FullMethodName             = "/sst.repository.DatasetService/DocumentDelete"
	DatasetService_DownloadNamedGraphRevision_FullMethodName = "/sst.repository.DatasetService/DownloadNamedGraphRevision"
	DatasetService_FindCommonParentRevision_FullMethodName   = "/sst.repository.DatasetService/FindCommonParentRevision"
	DatasetService_SyncFrom_FullMethodName                   = "/sst.repository.DatasetService/SyncFrom"
	DatasetService_SyncTo_FullMethodName                     = "/sst.repository.DatasetService/SyncTo"
)

// DatasetServiceClient is the client API for DatasetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DatasetServiceClient interface {
	RemoveBranch(ctx context.Context, in *RemoveBranchRequest, opts ...grpc.CallOption) (*RemoveBranchResponse, error)
	SetBranch(ctx context.Context, in *SetBranchRequest, opts ...grpc.CallOption) (*SetBranchResponse, error)
	GetBranches(ctx context.Context, in *GetBranchesRequest, opts ...grpc.CallOption) (*GetBranchesResponse, error)
	GetLeafCommits(ctx context.Context, in *GetLeafCommitsRequest, opts ...grpc.CallOption) (*GetLeafCommitsResponse, error)
	GetBleveInfo(ctx context.Context, in *GetRepoBleveInfoRequest, opts ...grpc.CallOption) (*GetRepoBleveInfoResponse, error)
	ListDatasets(ctx context.Context, in *ListDatasetsRequest, opts ...grpc.CallOption) (*ListDatasetsResponse, error)
	GetDataset(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[GetDatasetRequest, Dataset], error)
	CreateDataset(ctx context.Context, in *CreateDatasetRequest, opts ...grpc.CallOption) (*Dataset, error)
	FetchDatasets(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DatasetInquiry, DatasetObject], error)
	PushDatasets(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DatasetSuggestion, DatasetInquiry], error)
	GetRepositoryInfo(ctx context.Context, in *GetRepositoryInfoRequest, opts ...grpc.CallOption) (*GetRepositoryInfoResponse, error)
	GetRepositoryLog(ctx context.Context, in *GetRepositoryLogRequest, opts ...grpc.CallOption) (*GetRepositoryLogResponse, error)
	DocumentSet(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DocumentSetRequest, DocumentSetResponse], error)
	Document(ctx context.Context, in *DocumentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DocumentResponse], error)
	Documents(ctx context.Context, in *DocumentsListRequest, opts ...grpc.CallOption) (*DocumentsListResponse, error)
	DocumentDelete(ctx context.Context, in *DocumentDeleteRequest, opts ...grpc.CallOption) (*DocumentDeleteResponse, error)
	DownloadNamedGraphRevision(ctx context.Context, in *DownloadNamedGraphRevisionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadNamedGraphRevisionResponse], error)
	FindCommonParentRevision(ctx context.Context, in *FindCommonParentRevisionRequest, opts ...grpc.CallOption) (*FindCommonParentRevisionResponse, error)
	SyncFrom(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SyncFromRequest, SyncFromResponse], error)
	// SyncTo streams bucket data from server to client (for remote to local sync)
	SyncTo(ctx context.Context, in *SyncToRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SyncToResponse], error)
}

type datasetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDatasetServiceClient(cc grpc.ClientConnInterface) DatasetServiceClient {
	return &datasetServiceClient{cc}
}

func (c *datasetServiceClient) RemoveBranch(ctx context.Context, in *RemoveBranchRequest, opts ...grpc.CallOption) (*RemoveBranchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveBranchResponse)
	err := c.cc.Invoke(ctx, DatasetService_RemoveBranch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datasetServiceClient) SetBranch(ctx context.Context, in *SetBranchRequest, opts ...grpc.CallOption) (*SetBranchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetBranchResponse)
	err := c.cc.Invoke(ctx, DatasetService_SetBranch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datasetServiceClient) GetBranches(ctx context.Context, in *GetBranchesRequest, opts ...grpc.CallOption) (*GetBranchesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBranchesResponse)
	err := c.cc.Invoke(ctx, DatasetService_GetBranches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datasetServiceClient) GetLeafCommits(ctx context.Context, in *GetLeafCommitsRequest, opts ...grpc.CallOption) (*GetLeafCommitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLeafCommitsResponse)
	err := c.cc.Invoke(ctx, DatasetService_GetLeafCommits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datasetServiceClient) GetBleveInfo(ctx context.Context, in *GetRepoBleveInfoRequest, opts ...grpc.CallOption) (*GetRepoBleveInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRepoBleveInfoResponse)
	err := c.cc.Invoke(ctx, DatasetService_GetBleveInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datasetServiceClient) ListDatasets(ctx context.Context, in *ListDatasetsRequest, opts ...grpc.CallOption) (*ListDatasetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDatasetsResponse)
	err := c.cc.Invoke(ctx, DatasetService_ListDatasets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datasetServiceClient) GetDataset(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[GetDatasetRequest, Dataset], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DatasetService_ServiceDesc.Streams[0], DatasetService_GetDataset_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetDatasetRequest, Dataset]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DatasetService_GetDatasetClient = grpc.ClientStreamingClient[GetDatasetRequest, Dataset]

func (c *datasetServiceClient) CreateDataset(ctx context.Context, in *CreateDatasetRequest, opts ...grpc.CallOption) (*Dataset, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Dataset)
	err := c.cc.Invoke(ctx, DatasetService_CreateDataset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datasetServiceClient) FetchDatasets(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DatasetInquiry, DatasetObject], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DatasetService_ServiceDesc.Streams[1], DatasetService_FetchDatasets_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DatasetInquiry, DatasetObject]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DatasetService_FetchDatasetsClient = grpc.BidiStreamingClient[DatasetInquiry, DatasetObject]

func (c *datasetServiceClient) PushDatasets(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DatasetSuggestion, DatasetInquiry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DatasetService_ServiceDesc.Streams[2], DatasetService_PushDatasets_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DatasetSuggestion, DatasetInquiry]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DatasetService_PushDatasetsClient = grpc.BidiStreamingClient[DatasetSuggestion, DatasetInquiry]

func (c *datasetServiceClient) GetRepositoryInfo(ctx context.Context, in *GetRepositoryInfoRequest, opts ...grpc.CallOption) (*GetRepositoryInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRepositoryInfoResponse)
	err := c.cc.Invoke(ctx, DatasetService_GetRepositoryInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datasetServiceClient) GetRepositoryLog(ctx context.Context, in *GetRepositoryLogRequest, opts ...grpc.CallOption) (*GetRepositoryLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRepositoryLogResponse)
	err := c.cc.Invoke(ctx, DatasetService_GetRepositoryLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datasetServiceClient) DocumentSet(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DocumentSetRequest, DocumentSetResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DatasetService_ServiceDesc.Streams[3], DatasetService_DocumentSet_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DocumentSetRequest, DocumentSetResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DatasetService_DocumentSetClient = grpc.ClientStreamingClient[DocumentSetRequest, DocumentSetResponse]

func (c *datasetServiceClient) Document(ctx context.Context, in *DocumentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DocumentResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DatasetService_ServiceDesc.Streams[4], DatasetService_Document_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DocumentRequest, DocumentResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DatasetService_DocumentClient = grpc.ServerStreamingClient[DocumentResponse]

func (c *datasetServiceClient) Documents(ctx context.Context, in *DocumentsListRequest, opts ...grpc.CallOption) (*DocumentsListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocumentsListResponse)
	err := c.cc.Invoke(ctx, DatasetService_Documents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datasetServiceClient) DocumentDelete(ctx context.Context, in *DocumentDeleteRequest, opts ...grpc.CallOption) (*DocumentDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocumentDeleteResponse)
	err := c.cc.Invoke(ctx, DatasetService_DocumentDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datasetServiceClient) DownloadNamedGraphRevision(ctx context.Context, in *DownloadNamedGraphRevisionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadNamedGraphRevisionResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DatasetService_ServiceDesc.Streams[5], DatasetService_DownloadNamedGraphRevision_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadNamedGraphRevisionRequest, DownloadNamedGraphRevisionResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DatasetService_DownloadNamedGraphRevisionClient = grpc.ServerStreamingClient[DownloadNamedGraphRevisionResponse]

func (c *datasetServiceClient) FindCommonParentRevision(ctx context.Context, in *FindCommonParentRevisionRequest, opts ...grpc.CallOption) (*FindCommonParentRevisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindCommonParentRevisionResponse)
	err := c.cc.Invoke(ctx, DatasetService_FindCommonParentRevision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datasetServiceClient) SyncFrom(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SyncFromRequest, SyncFromResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DatasetService_ServiceDesc.Streams[6], DatasetService_SyncFrom_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SyncFromRequest, SyncFromResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DatasetService_SyncFromClient = grpc.ClientStreamingClient[SyncFromRequest, SyncFromResponse]

func (c *datasetServiceClient) SyncTo(ctx context.Context, in *SyncToRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SyncToResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DatasetService_ServiceDesc.Streams[7], DatasetService_SyncTo_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SyncToRequest, SyncToResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DatasetService_SyncToClient = grpc.ServerStreamingClient[SyncToResponse]

// DatasetServiceServer is the server API for DatasetService service.
// All implementations must embed UnimplementedDatasetServiceServer
// for forward compatibility.
type DatasetServiceServer interface {
	RemoveBranch(context.Context, *RemoveBranchRequest) (*RemoveBranchResponse, error)
	SetBranch(context.Context, *SetBranchRequest) (*SetBranchResponse, error)
	GetBranches(context.Context, *GetBranchesRequest) (*GetBranchesResponse, error)
	GetLeafCommits(context.Context, *GetLeafCommitsRequest) (*GetLeafCommitsResponse, error)
	GetBleveInfo(context.Context, *GetRepoBleveInfoRequest) (*GetRepoBleveInfoResponse, error)
	ListDatasets(context.Context, *ListDatasetsRequest) (*ListDatasetsResponse, error)
	GetDataset(grpc.ClientStreamingServer[GetDatasetRequest, Dataset]) error
	CreateDataset(context.Context, *CreateDatasetRequest) (*Dataset, error)
	FetchDatasets(grpc.BidiStreamingServer[DatasetInquiry, DatasetObject]) error
	PushDatasets(grpc.BidiStreamingServer[DatasetSuggestion, DatasetInquiry]) error
	GetRepositoryInfo(context.Context, *GetRepositoryInfoRequest) (*GetRepositoryInfoResponse, error)
	GetRepositoryLog(context.Context, *GetRepositoryLogRequest) (*GetRepositoryLogResponse, error)
	DocumentSet(grpc.ClientStreamingServer[DocumentSetRequest, DocumentSetResponse]) error
	Document(*DocumentRequest, grpc.ServerStreamingServer[DocumentResponse]) error
	Documents(context.Context, *DocumentsListRequest) (*DocumentsListResponse, error)
	DocumentDelete(context.Context, *DocumentDeleteRequest) (*DocumentDeleteResponse, error)
	DownloadNamedGraphRevision(*DownloadNamedGraphRevisionRequest, grpc.ServerStreamingServer[DownloadNamedGraphRevisionResponse]) error
	FindCommonParentRevision(context.Context, *FindCommonParentRevisionRequest) (*FindCommonParentRevisionResponse, error)
	SyncFrom(grpc.ClientStreamingServer[SyncFromRequest, SyncFromResponse]) error
	// SyncTo streams bucket data from server to client (for remote to local sync)
	SyncTo(*SyncToRequest, grpc.ServerStreamingServer[SyncToResponse]) error
	mustEmbedUnimplementedDatasetServiceServer()
}

// UnimplementedDatasetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDatasetServiceServer struct{}

func (UnimplementedDatasetServiceServer) RemoveBranch(context.Context, *RemoveBranchRequest) (*RemoveBranchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveBranch not implemented")
}
func (UnimplementedDatasetServiceServer) SetBranch(context.Context, *SetBranchRequest) (*SetBranchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetBranch not implemented")
}
func (UnimplementedDatasetServiceServer) GetBranches(context.Context, *GetBranchesRequest) (*GetBranchesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBranches not implemented")
}
func (UnimplementedDatasetServiceServer) GetLeafCommits(context.Context, *GetLeafCommitsRequest) (*GetLeafCommitsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLeafCommits not implemented")
}
func (UnimplementedDatasetServiceServer) GetBleveInfo(context.Context, *GetRepoBleveInfoRequest) (*GetRepoBleveInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBleveInfo not implemented")
}
func (UnimplementedDatasetServiceServer) ListDatasets(context.Context, *ListDatasetsRequest) (*ListDatasetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDatasets not implemented")
}
func (UnimplementedDatasetServiceServer) GetDataset(grpc.ClientStreamingServer[GetDatasetRequest, Dataset]) error {
	return status.Errorf(codes.Unimplemented, "method GetDataset not implemented")
}
func (UnimplementedDatasetServiceServer) CreateDataset(context.Context, *CreateDatasetRequest) (*Dataset, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDataset not implemented")
}
func (UnimplementedDatasetServiceServer) FetchDatasets(grpc.BidiStreamingServer[DatasetInquiry, DatasetObject]) error {
	return status.Errorf(codes.Unimplemented, "method FetchDatasets not implemented")
}
func (UnimplementedDatasetServiceServer) PushDatasets(grpc.BidiStreamingServer[DatasetSuggestion, DatasetInquiry]) error {
	return status.Errorf(codes.Unimplemented, "method PushDatasets not implemented")
}
func (UnimplementedDatasetServiceServer) GetRepositoryInfo(context.Context, *GetRepositoryInfoRequest) (*GetRepositoryInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRepositoryInfo not implemented")
}
func (UnimplementedDatasetServiceServer) GetRepositoryLog(context.Context, *GetRepositoryLogRequest) (*GetRepositoryLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRepositoryLog not implemented")
}
func (UnimplementedDatasetServiceServer) DocumentSet(grpc.ClientStreamingServer[DocumentSetRequest, DocumentSetResponse]) error {
	return status.Errorf(codes.Unimplemented, "method DocumentSet not implemented")
}
func (UnimplementedDatasetServiceServer) Document(*DocumentRequest, grpc.ServerStreamingServer[DocumentResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Document not implemented")
}
func (UnimplementedDatasetServiceServer) Documents(context.Context, *DocumentsListRequest) (*DocumentsListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Documents not implemented")
}
func (UnimplementedDatasetServiceServer) DocumentDelete(context.Context, *DocumentDeleteRequest) (*DocumentDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DocumentDelete not implemented")
}
func (UnimplementedDatasetServiceServer) DownloadNamedGraphRevision(*DownloadNamedGraphRevisionRequest, grpc.ServerStreamingServer[DownloadNamedGraphRevisionResponse]) error {
	return status.Errorf(codes.Unimplemented, "method DownloadNamedGraphRevision not implemented")
}
func (UnimplementedDatasetServiceServer) FindCommonParentRevision(context.Context, *FindCommonParentRevisionRequest) (*FindCommonParentRevisionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindCommonParentRevision not implemented")
}
func (UnimplementedDatasetServiceServer) SyncFrom(grpc.ClientStreamingServer[SyncFromRequest, SyncFromResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SyncFrom not implemented")
}
func (UnimplementedDatasetServiceServer) SyncTo(*SyncToRequest, grpc.ServerStreamingServer[SyncToResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SyncTo not implemented")
}
func (UnimplementedDatasetServiceServer) mustEmbedUnimplementedDatasetServiceServer() {}
func (UnimplementedDatasetServiceServer) testEmbeddedByValue()                        {}

// UnsafeDatasetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DatasetServiceServer will
// result in compilation errors.
type UnsafeDatasetServiceServer interface {
	mustEmbedUnimplementedDatasetServiceServer()
}

func RegisterDatasetServiceServer(s grpc.ServiceRegistrar, srv DatasetServiceServer) {
	// If the following call pancis, it indicates UnimplementedDatasetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DatasetService_ServiceDesc, srv)
}

func _DatasetService_RemoveBranch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveBranchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatasetServiceServer).RemoveBranch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatasetService_RemoveBranch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatasetServiceServer).RemoveBranch(ctx, req.(*RemoveBranchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatasetService_SetBranch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBranchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatasetServiceServer).SetBranch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatasetService_SetBranch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatasetServiceServer).SetBranch(ctx, req.(*SetBranchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatasetService_GetBranches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBranchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatasetServiceServer).GetBranches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatasetService_GetBranches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatasetServiceServer).GetBranches(ctx, req.(*GetBranchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatasetService_GetLeafCommits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeafCommitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatasetServiceServer).GetLeafCommits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatasetService_GetLeafCommits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatasetServiceServer).GetLeafCommits(ctx, req.(*GetLeafCommitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatasetService_GetBleveInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRepoBleveInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatasetServiceServer).GetBleveInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatasetService_GetBleveInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatasetServiceServer).GetBleveInfo(ctx, req.(*GetRepoBleveInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatasetService_ListDatasets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDatasetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatasetServiceServer).ListDatasets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatasetService_ListDatasets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatasetServiceServer).ListDatasets(ctx, req.(*ListDatasetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatasetService_GetDataset_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DatasetServiceServer).GetDataset(&grpc.GenericServerStream[GetDatasetRequest, Dataset]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DatasetService_GetDatasetServer = grpc.ClientStreamingServer[GetDatasetRequest, Dataset]

func _DatasetService_CreateDataset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDatasetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatasetServiceServer).CreateDataset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatasetService_CreateDataset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatasetServiceServer).CreateDataset(ctx, req.(*CreateDatasetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatasetService_FetchDatasets_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DatasetServiceServer).FetchDatasets(&grpc.GenericServerStream[DatasetInquiry, DatasetObject]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DatasetService_FetchDatasetsServer = grpc.BidiStreamingServer[DatasetInquiry, DatasetObject]

func _DatasetService_PushDatasets_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DatasetServiceServer).PushDatasets(&grpc.GenericServerStream[DatasetSuggestion, DatasetInquiry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DatasetService_PushDatasetsServer = grpc.BidiStreamingServer[DatasetSuggestion, DatasetInquiry]

func _DatasetService_GetRepositoryInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRepositoryInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatasetServiceServer).GetRepositoryInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatasetService_GetRepositoryInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatasetServiceServer).GetRepositoryInfo(ctx, req.(*GetRepositoryInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatasetService_GetRepositoryLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRepositoryLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatasetServiceServer).GetRepositoryLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatasetService_GetRepositoryLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatasetServiceServer).GetRepositoryLog(ctx, req.(*GetRepositoryLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatasetService_DocumentSet_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DatasetServiceServer).DocumentSet(&grpc.GenericServerStream[DocumentSetRequest, DocumentSetResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DatasetService_DocumentSetServer = grpc.ClientStreamingServer[DocumentSetRequest, DocumentSetResponse]

func _DatasetService_Document_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DocumentRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DatasetServiceServer).Document(m, &grpc.GenericServerStream[DocumentRequest, DocumentResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DatasetService_DocumentServer = grpc.ServerStreamingServer[DocumentResponse]

func _DatasetService_Documents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocumentsListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatasetServiceServer).Documents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatasetService_Documents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatasetServiceServer).Documents(ctx, req.(*DocumentsListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatasetService_DocumentDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocumentDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatasetServiceServer).DocumentDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatasetService_DocumentDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatasetServiceServer).DocumentDelete(ctx, req.(*DocumentDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatasetService_DownloadNamedGraphRevision_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadNamedGraphRevisionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DatasetServiceServer).DownloadNamedGraphRevision(m, &grpc.GenericServerStream[DownloadNamedGraphRevisionRequest, DownloadNamedGraphRevisionResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DatasetService_DownloadNamedGraphRevisionServer = grpc.ServerStreamingServer[DownloadNamedGraphRevisionResponse]

func _DatasetService_FindCommonParentRevision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindCommonParentRevisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatasetServiceServer).FindCommonParentRevision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatasetService_FindCommonParentRevision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatasetServiceServer).FindCommonParentRevision(ctx, req.(*FindCommonParentRevisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatasetService_SyncFrom_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DatasetServiceServer).SyncFrom(&grpc.GenericServerStream[SyncFromRequest, SyncFromResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DatasetService_SyncFromServer = grpc.ClientStreamingServer[SyncFromRequest, SyncFromResponse]

func _DatasetService_SyncTo_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SyncToRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DatasetServiceServer).SyncTo(m, &grpc.GenericServerStream[SyncToRequest, SyncToResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DatasetService_SyncToServer = grpc.ServerStreamingServer[SyncToResponse]

// DatasetService_ServiceDesc is the grpc.ServiceDesc for DatasetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DatasetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sst.repository.DatasetService",
	HandlerType: (*DatasetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RemoveBranch",
			Handler:    _DatasetService_RemoveBranch_Handler,
		},
		{
			MethodName: "SetBranch",
			Handler:    _DatasetService_SetBranch_Handler,
		},
		{
			MethodName: "GetBranches",
			Handler:    _DatasetService_GetBranches_Handler,
		},
		{
			MethodName: "GetLeafCommits",
			Handler:    _DatasetService_GetLeafCommits_Handler,
		},
		{
			MethodName: "GetBleveInfo",
			Handler:    _DatasetService_GetBleveInfo_Handler,
		},
		{
			MethodName: "ListDatasets",
			Handler:    _DatasetService_ListDatasets_Handler,
		},
		{
			MethodName: "CreateDataset",
			Handler:    _DatasetService_CreateDataset_Handler,
		},
		{
			MethodName: "GetRepositoryInfo",
			Handler:    _DatasetService_GetRepositoryInfo_Handler,
		},
		{
			MethodName: "GetRepositoryLog",
			Handler:    _DatasetService_GetRepositoryLog_Handler,
		},
		{
			MethodName: "Documents",
			Handler:    _DatasetService_Documents_Handler,
		},
		{
			MethodName: "DocumentDelete",
			Handler:    _DatasetService_DocumentDelete_Handler,
		},
		{
			MethodName: "FindCommonParentRevision",
			Handler:    _DatasetService_FindCommonParentRevision_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetDataset",
			Handler:       _DatasetService_GetDataset_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "FetchDatasets",
			Handler:       _DatasetService_FetchDatasets_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "PushDatasets",
			Handler:       _DatasetService_PushDatasets_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "DocumentSet",
			Handler:       _DatasetService_DocumentSet_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Document",
			Handler:       _DatasetService_Document_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DownloadNamedGraphRevision",
			Handler:       _DatasetService_DownloadNamedGraphRevision_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SyncFrom",
			Handler:       _DatasetService_SyncFrom_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SyncTo",
			Handler:       _DatasetService_SyncTo_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "repository.proto",
}

const (
	RefService_ListRefs_FullMethodName = "/sst.repository.RefService/ListRefs"
	RefService_GetRef_FullMethodName   = "/sst.repository.RefService/GetRef"
)

// RefServiceClient is the client API for RefService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RefServiceClient interface {
	ListRefs(ctx context.Context, in *ListRefsRequest, opts ...grpc.CallOption) (*ListRefsResponse, error)
	GetRef(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[GetRefRequest, Ref], error)
}

type refServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRefServiceClient(cc grpc.ClientConnInterface) RefServiceClient {
	return &refServiceClient{cc}
}

func (c *refServiceClient) ListRefs(ctx context.Context, in *ListRefsRequest, opts ...grpc.CallOption) (*ListRefsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRefsResponse)
	err := c.cc.Invoke(ctx, RefService_ListRefs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *refServiceClient) GetRef(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[GetRefRequest, Ref], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RefService_ServiceDesc.Streams[0], RefService_GetRef_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetRefRequest, Ref]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RefService_GetRefClient = grpc.ClientStreamingClient[GetRefRequest, Ref]

// RefServiceServer is the server API for RefService service.
// All implementations must embed UnimplementedRefServiceServer
// for forward compatibility.
type RefServiceServer interface {
	ListRefs(context.Context, *ListRefsRequest) (*ListRefsResponse, error)
	GetRef(grpc.ClientStreamingServer[GetRefRequest, Ref]) error
	mustEmbedUnimplementedRefServiceServer()
}

// UnimplementedRefServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRefServiceServer struct{}

func (UnimplementedRefServiceServer) ListRefs(context.Context, *ListRefsRequest) (*ListRefsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRefs not implemented")
}
func (UnimplementedRefServiceServer) GetRef(grpc.ClientStreamingServer[GetRefRequest, Ref]) error {
	return status.Errorf(codes.Unimplemented, "method GetRef not implemented")
}
func (UnimplementedRefServiceServer) mustEmbedUnimplementedRefServiceServer() {}
func (UnimplementedRefServiceServer) testEmbeddedByValue()                    {}

// UnsafeRefServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RefServiceServer will
// result in compilation errors.
type UnsafeRefServiceServer interface {
	mustEmbedUnimplementedRefServiceServer()
}

func RegisterRefServiceServer(s grpc.ServiceRegistrar, srv RefServiceServer) {
	// If the following call pancis, it indicates UnimplementedRefServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RefService_ServiceDesc, srv)
}

func _RefService_ListRefs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRefsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RefServiceServer).ListRefs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RefService_ListRefs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RefServiceServer).ListRefs(ctx, req.(*ListRefsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RefService_GetRef_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RefServiceServer).GetRef(&grpc.GenericServerStream[GetRefRequest, Ref]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RefService_GetRefServer = grpc.ClientStreamingServer[GetRefRequest, Ref]

// RefService_ServiceDesc is the grpc.ServiceDesc for RefService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RefService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sst.repository.RefService",
	HandlerType: (*RefServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRefs",
			Handler:    _RefService_ListRefs_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetRef",
			Handler:       _RefService_GetRef_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "repository.proto",
}

const (
	CommitService_ListCommits_FullMethodName           = "/sst.repository.CommitService/ListCommits"
	CommitService_GetCommit_FullMethodName             = "/sst.repository.CommitService/GetCommit"
	CommitService_CreateCommit_FullMethodName          = "/sst.repository.CommitService/CreateCommit"
	CommitService_CompareCommits_FullMethodName        = "/sst.repository.CommitService/CompareCommits"
	CommitService_GetCommitDetailsBatch_FullMethodName = "/sst.repository.CommitService/GetCommitDetailsBatch"
)

// CommitServiceClient is the client API for CommitService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommitServiceClient interface {
	ListCommits(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ListCommitsRequest, ListCommitsResponse], error)
	GetCommit(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[GetCommitRequest, Commit], error)
	CreateCommit(ctx context.Context, in *CreateCommitRequest, opts ...grpc.CallOption) (*CreateCommitResponse, error)
	CompareCommits(ctx context.Context, in *CompareCommitsRequest, opts ...grpc.CallOption) (*CompareCommitsResponse, error)
	GetCommitDetailsBatch(ctx context.Context, in *GetCommitDetailsBatchRequest, opts ...grpc.CallOption) (*GetCommitDetailsBatchResponse, error)
}

type commitServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommitServiceClient(cc grpc.ClientConnInterface) CommitServiceClient {
	return &commitServiceClient{cc}
}

func (c *commitServiceClient) ListCommits(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ListCommitsRequest, ListCommitsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CommitService_ServiceDesc.Streams[0], CommitService_ListCommits_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListCommitsRequest, ListCommitsResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CommitService_ListCommitsClient = grpc.ClientStreamingClient[ListCommitsRequest, ListCommitsResponse]

func (c *commitServiceClient) GetCommit(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[GetCommitRequest, Commit], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CommitService_ServiceDesc.Streams[1], CommitService_GetCommit_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetCommitRequest, Commit]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CommitService_GetCommitClient = grpc.ClientStreamingClient[GetCommitRequest, Commit]

func (c *commitServiceClient) CreateCommit(ctx context.Context, in *CreateCommitRequest, opts ...grpc.CallOption) (*CreateCommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCommitResponse)
	err := c.cc.Invoke(ctx, CommitService_CreateCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commitServiceClient) CompareCommits(ctx context.Context, in *CompareCommitsRequest, opts ...grpc.CallOption) (*CompareCommitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompareCommitsResponse)
	err := c.cc.Invoke(ctx, CommitService_CompareCommits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commitServiceClient) GetCommitDetailsBatch(ctx context.Context, in *GetCommitDetailsBatchRequest, opts ...grpc.CallOption) (*GetCommitDetailsBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCommitDetailsBatchResponse)
	err := c.cc.Invoke(ctx, CommitService_GetCommitDetailsBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommitServiceServer is the server API for CommitService service.
// All implementations must embed UnimplementedCommitServiceServer
// for forward compatibility.
type CommitServiceServer interface {
	ListCommits(grpc.ClientStreamingServer[ListCommitsRequest, ListCommitsResponse]) error
	GetCommit(grpc.ClientStreamingServer[GetCommitRequest, Commit]) error
	CreateCommit(context.Context, *CreateCommitRequest) (*CreateCommitResponse, error)
	CompareCommits(context.Context, *CompareCommitsRequest) (*CompareCommitsResponse, error)
	GetCommitDetailsBatch(context.Context, *GetCommitDetailsBatchRequest) (*GetCommitDetailsBatchResponse, error)
	mustEmbedUnimplementedCommitServiceServer()
}

// UnimplementedCommitServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommitServiceServer struct{}

func (UnimplementedCommitServiceServer) ListCommits(grpc.ClientStreamingServer[ListCommitsRequest, ListCommitsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ListCommits not implemented")
}
func (UnimplementedCommitServiceServer) GetCommit(grpc.ClientStreamingServer[GetCommitRequest, Commit]) error {
	return status.Errorf(codes.Unimplemented, "method GetCommit not implemented")
}
func (UnimplementedCommitServiceServer) CreateCommit(context.Context, *CreateCommitRequest) (*CreateCommitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCommit not implemented")
}
func (UnimplementedCommitServiceServer) CompareCommits(context.Context, *CompareCommitsRequest) (*CompareCommitsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompareCommits not implemented")
}
func (UnimplementedCommitServiceServer) GetCommitDetailsBatch(context.Context, *GetCommitDetailsBatchRequest) (*GetCommitDetailsBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommitDetailsBatch not implemented")
}
func (UnimplementedCommitServiceServer) mustEmbedUnimplementedCommitServiceServer() {}
func (UnimplementedCommitServiceServer) testEmbeddedByValue()                       {}

// UnsafeCommitServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommitServiceServer will
// result in compilation errors.
type UnsafeCommitServiceServer interface {
	mustEmbedUnimplementedCommitServiceServer()
}

func RegisterCommitServiceServer(s grpc.ServiceRegistrar, srv CommitServiceServer) {
	// If the following call pancis, it indicates UnimplementedCommitServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CommitService_ServiceDesc, srv)
}

func _CommitService_ListCommits_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CommitServiceServer).ListCommits(&grpc.GenericServerStream[ListCommitsRequest, ListCommitsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CommitService_ListCommitsServer = grpc.ClientStreamingServer[ListCommitsRequest, ListCommitsResponse]

func _CommitService_GetCommit_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CommitServiceServer).GetCommit(&grpc.GenericServerStream[GetCommitRequest, Commit]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CommitService_GetCommitServer = grpc.ClientStreamingServer[GetCommitRequest, Commit]

func _CommitService_CreateCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommitServiceServer).CreateCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommitService_CreateCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommitServiceServer).CreateCommit(ctx, req.(*CreateCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommitService_CompareCommits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompareCommitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommitServiceServer).CompareCommits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommitService_CompareCommits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommitServiceServer).CompareCommits(ctx, req.(*CompareCommitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommitService_GetCommitDetailsBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommitDetailsBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommitServiceServer).GetCommitDetailsBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommitService_GetCommitDetailsBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommitServiceServer).GetCommitDetailsBatch(ctx, req.(*GetCommitDetailsBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CommitService_ServiceDesc is the grpc.ServiceDesc for CommitService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommitService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sst.repository.CommitService",
	HandlerType: (*CommitServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCommit",
			Handler:    _CommitService_CreateCommit_Handler,
		},
		{
			MethodName: "CompareCommits",
			Handler:    _CommitService_CompareCommits_Handler,
		},
		{
			MethodName: "GetCommitDetailsBatch",
			Handler:    _CommitService_GetCommitDetailsBatch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListCommits",
			Handler:       _CommitService_ListCommits_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetCommit",
			Handler:       _CommitService_GetCommit_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "repository.proto",
}
