// Copyright Semantic STEP Technology GmbH, Germany & DCT Co., Ltd. Tianjin, China
// Code generated by protoc-gen-fieldmask. DO NOT EDIT.
// source: repository.proto

package bboltproto

import (
	pbfieldmask "github.com/yeqown/protoc-gen-fieldmask/proto/fieldmask"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
)

func (x *ListDatasetsRequest) fieldMaskWithMode(mode pbfieldmask.MaskMode) *ListDatasetsRequest_FieldMask {
	fm := &ListDatasetsRequest_FieldMask{
		maskMode: mode,
		mask:     pbfieldmask.New(x.ReadMask),
	}

	return fm
}

// FieldMask_Filter generates *ListDatasetsRequest_FieldMask with filter mode, so that
// only the fields in the ListDatasetsRequest.ReadMask will be
// appended into the ListDatasetsRequest.
func (x *ListDatasetsRequest) FieldMask_Filter() *ListDatasetsRequest_FieldMask {
	return x.fieldMaskWithMode(pbfieldmask.MaskMode_Filter)
}

// FieldMask_Prune generates *ListDatasetsRequest_FieldMask with prune mode, so that
// only the fields NOT in the ListDatasetsRequest.ReadMask will be
// appended into the ListDatasetsRequest.
func (x *ListDatasetsRequest) FieldMask_Prune() *ListDatasetsRequest_FieldMask {
	return x.fieldMaskWithMode(pbfieldmask.MaskMode_Prune)
}

// ListDatasetsRequest_FieldMask provide provide helper functions to deal with FieldMask.
type ListDatasetsRequest_FieldMask struct {
	maskMode pbfieldmask.MaskMode
	mask     pbfieldmask.NestedFieldMask
}

// _fm_Dataset is built in variable for Dataset to call FieldMask.Append
var _fm_Dataset = new(Dataset)

// MaskOut_Uuid append Dataset.Uuid into
// ListDatasetsRequest.ReadMask.
func (x *ListDatasetsRequest) MaskOut_Uuid() *ListDatasetsRequest {
	if x.ReadMask == nil {
		x.ReadMask = new(fieldmaskpb.FieldMask)
	}
	x.ReadMask.Append(_fm_Dataset, "uuid")

	return x
}

// MaskedOut_Uuid indicates the field ListDatasetsRequest.Uuid
// exists in the ListDatasetsRequest.ReadMask or not.
func (x *ListDatasetsRequest_FieldMask) MaskedOut_Uuid() bool {
	if x.mask == nil {
		return true
	}

	return x.mask.Masked("uuid")
}

// MaskOut_Iri append Dataset.Iri into
// ListDatasetsRequest.ReadMask.
func (x *ListDatasetsRequest) MaskOut_Iri() *ListDatasetsRequest {
	if x.ReadMask == nil {
		x.ReadMask = new(fieldmaskpb.FieldMask)
	}
	x.ReadMask.Append(_fm_Dataset, "iri")

	return x
}

// MaskedOut_Iri indicates the field ListDatasetsRequest.Iri
// exists in the ListDatasetsRequest.ReadMask or not.
func (x *ListDatasetsRequest_FieldMask) MaskedOut_Iri() bool {
	if x.mask == nil {
		return true
	}

	return x.mask.Masked("iri")
}

// Mask only affects the fields in the ListDatasetsRequest.
func (x *ListDatasetsRequest_FieldMask) Mask(m *Dataset) *Dataset {
	switch x.maskMode {
	case pbfieldmask.MaskMode_Filter:
		x.mask.Filter(m)
	case pbfieldmask.MaskMode_Prune:
		x.mask.Prune(m)
	}

	return m
}

func (x *GetDatasetRequest) fieldMaskWithMode(mode pbfieldmask.MaskMode) *GetDatasetRequest_FieldMask {
	fm := &GetDatasetRequest_FieldMask{
		maskMode: mode,
		mask:     pbfieldmask.New(x.ReadMask),
	}

	return fm
}

// FieldMask_Filter generates *GetDatasetRequest_FieldMask with filter mode, so that
// only the fields in the GetDatasetRequest.ReadMask will be
// appended into the GetDatasetRequest.
func (x *GetDatasetRequest) FieldMask_Filter() *GetDatasetRequest_FieldMask {
	return x.fieldMaskWithMode(pbfieldmask.MaskMode_Filter)
}

// FieldMask_Prune generates *GetDatasetRequest_FieldMask with prune mode, so that
// only the fields NOT in the GetDatasetRequest.ReadMask will be
// appended into the GetDatasetRequest.
func (x *GetDatasetRequest) FieldMask_Prune() *GetDatasetRequest_FieldMask {
	return x.fieldMaskWithMode(pbfieldmask.MaskMode_Prune)
}

// GetDatasetRequest_FieldMask provide provide helper functions to deal with FieldMask.
type GetDatasetRequest_FieldMask struct {
	maskMode pbfieldmask.MaskMode
	mask     pbfieldmask.NestedFieldMask
}

// MaskOut_Uuid append Dataset.Uuid into
// GetDatasetRequest.ReadMask.
func (x *GetDatasetRequest) MaskOut_Uuid() *GetDatasetRequest {
	if x.ReadMask == nil {
		x.ReadMask = new(fieldmaskpb.FieldMask)
	}
	x.ReadMask.Append(_fm_Dataset, "uuid")

	return x
}

// MaskedOut_Uuid indicates the field GetDatasetRequest.Uuid
// exists in the GetDatasetRequest.ReadMask or not.
func (x *GetDatasetRequest_FieldMask) MaskedOut_Uuid() bool {
	if x.mask == nil {
		return true
	}

	return x.mask.Masked("uuid")
}

// MaskOut_Iri append Dataset.Iri into
// GetDatasetRequest.ReadMask.
func (x *GetDatasetRequest) MaskOut_Iri() *GetDatasetRequest {
	if x.ReadMask == nil {
		x.ReadMask = new(fieldmaskpb.FieldMask)
	}
	x.ReadMask.Append(_fm_Dataset, "iri")

	return x
}

// MaskedOut_Iri indicates the field GetDatasetRequest.Iri
// exists in the GetDatasetRequest.ReadMask or not.
func (x *GetDatasetRequest_FieldMask) MaskedOut_Iri() bool {
	if x.mask == nil {
		return true
	}

	return x.mask.Masked("iri")
}

// Mask only affects the fields in the GetDatasetRequest.
func (x *GetDatasetRequest_FieldMask) Mask(m *Dataset) *Dataset {
	switch x.maskMode {
	case pbfieldmask.MaskMode_Filter:
		x.mask.Filter(m)
	case pbfieldmask.MaskMode_Prune:
		x.mask.Prune(m)
	}

	return m
}

func (x *CreateDatasetRequest) fieldMaskWithMode(mode pbfieldmask.MaskMode) *CreateDatasetRequest_FieldMask {
	fm := &CreateDatasetRequest_FieldMask{
		maskMode: mode,
		mask:     pbfieldmask.New(x.ReadMask),
	}

	return fm
}

// FieldMask_Filter generates *CreateDatasetRequest_FieldMask with filter mode, so that
// only the fields in the CreateDatasetRequest.ReadMask will be
// appended into the CreateDatasetRequest.
func (x *CreateDatasetRequest) FieldMask_Filter() *CreateDatasetRequest_FieldMask {
	return x.fieldMaskWithMode(pbfieldmask.MaskMode_Filter)
}

// FieldMask_Prune generates *CreateDatasetRequest_FieldMask with prune mode, so that
// only the fields NOT in the CreateDatasetRequest.ReadMask will be
// appended into the CreateDatasetRequest.
func (x *CreateDatasetRequest) FieldMask_Prune() *CreateDatasetRequest_FieldMask {
	return x.fieldMaskWithMode(pbfieldmask.MaskMode_Prune)
}

// CreateDatasetRequest_FieldMask provide provide helper functions to deal with FieldMask.
type CreateDatasetRequest_FieldMask struct {
	maskMode pbfieldmask.MaskMode
	mask     pbfieldmask.NestedFieldMask
}

// MaskOut_Uuid append Dataset.Uuid into
// CreateDatasetRequest.ReadMask.
func (x *CreateDatasetRequest) MaskOut_Uuid() *CreateDatasetRequest {
	if x.ReadMask == nil {
		x.ReadMask = new(fieldmaskpb.FieldMask)
	}
	x.ReadMask.Append(_fm_Dataset, "uuid")

	return x
}

// MaskedOut_Uuid indicates the field CreateDatasetRequest.Uuid
// exists in the CreateDatasetRequest.ReadMask or not.
func (x *CreateDatasetRequest_FieldMask) MaskedOut_Uuid() bool {
	if x.mask == nil {
		return true
	}

	return x.mask.Masked("uuid")
}

// MaskOut_Iri append Dataset.Iri into
// CreateDatasetRequest.ReadMask.
func (x *CreateDatasetRequest) MaskOut_Iri() *CreateDatasetRequest {
	if x.ReadMask == nil {
		x.ReadMask = new(fieldmaskpb.FieldMask)
	}
	x.ReadMask.Append(_fm_Dataset, "iri")

	return x
}

// MaskedOut_Iri indicates the field CreateDatasetRequest.Iri
// exists in the CreateDatasetRequest.ReadMask or not.
func (x *CreateDatasetRequest_FieldMask) MaskedOut_Iri() bool {
	if x.mask == nil {
		return true
	}

	return x.mask.Masked("iri")
}

// Mask only affects the fields in the CreateDatasetRequest.
func (x *CreateDatasetRequest_FieldMask) Mask(m *Dataset) *Dataset {
	switch x.maskMode {
	case pbfieldmask.MaskMode_Filter:
		x.mask.Filter(m)
	case pbfieldmask.MaskMode_Prune:
		x.mask.Prune(m)
	}

	return m
}

func (x *ListRefsRequest) fieldMaskWithMode(mode pbfieldmask.MaskMode) *ListRefsRequest_FieldMask {
	fm := &ListRefsRequest_FieldMask{
		maskMode: mode,
		mask:     pbfieldmask.New(x.ReadMask),
	}

	return fm
}

// FieldMask_Filter generates *ListRefsRequest_FieldMask with filter mode, so that
// only the fields in the ListRefsRequest.ReadMask will be
// appended into the ListRefsRequest.
func (x *ListRefsRequest) FieldMask_Filter() *ListRefsRequest_FieldMask {
	return x.fieldMaskWithMode(pbfieldmask.MaskMode_Filter)
}

// FieldMask_Prune generates *ListRefsRequest_FieldMask with prune mode, so that
// only the fields NOT in the ListRefsRequest.ReadMask will be
// appended into the ListRefsRequest.
func (x *ListRefsRequest) FieldMask_Prune() *ListRefsRequest_FieldMask {
	return x.fieldMaskWithMode(pbfieldmask.MaskMode_Prune)
}

// ListRefsRequest_FieldMask provide provide helper functions to deal with FieldMask.
type ListRefsRequest_FieldMask struct {
	maskMode pbfieldmask.MaskMode
	mask     pbfieldmask.NestedFieldMask
}

// _fm_Ref is built in variable for Ref to call FieldMask.Append
var _fm_Ref = new(Ref)

// MaskOut_Ref append Ref.Ref into
// ListRefsRequest.ReadMask.
func (x *ListRefsRequest) MaskOut_Ref() *ListRefsRequest {
	if x.ReadMask == nil {
		x.ReadMask = new(fieldmaskpb.FieldMask)
	}
	x.ReadMask.Append(_fm_Ref, "ref")

	return x
}

// MaskedOut_Ref indicates the field ListRefsRequest.Ref
// exists in the ListRefsRequest.ReadMask or not.
func (x *ListRefsRequest_FieldMask) MaskedOut_Ref() bool {
	if x.mask == nil {
		return true
	}

	return x.mask.Masked("ref")
}

// MaskOut_Ref_DatasetUuid append Ref.DatasetUuid into
// ListRefsRequest.ReadMask.
func (x *ListRefsRequest) MaskOut_Ref_DatasetUuid() *ListRefsRequest {
	if x.ReadMask == nil {
		x.ReadMask = new(fieldmaskpb.FieldMask)
	}
	x.ReadMask.Append(_fm_Ref, "ref.dataset_uuid")

	return x
}

// MaskedOut_Ref_DatasetUuid indicates the field ListRefsRequest.DatasetUuid
// exists in the ListRefsRequest.ReadMask or not.
func (x *ListRefsRequest_FieldMask) MaskedOut_Ref_DatasetUuid() bool {
	if x.mask == nil {
		return true
	}

	return x.mask.Masked("ref.dataset_uuid")
}

// MaskOut_Ref_DatasetIri append Ref.DatasetIri into
// ListRefsRequest.ReadMask.
func (x *ListRefsRequest) MaskOut_Ref_DatasetIri() *ListRefsRequest {
	if x.ReadMask == nil {
		x.ReadMask = new(fieldmaskpb.FieldMask)
	}
	x.ReadMask.Append(_fm_Ref, "ref.dataset_iri")

	return x
}

// MaskedOut_Ref_DatasetIri indicates the field ListRefsRequest.DatasetIri
// exists in the ListRefsRequest.ReadMask or not.
func (x *ListRefsRequest_FieldMask) MaskedOut_Ref_DatasetIri() bool {
	if x.mask == nil {
		return true
	}

	return x.mask.Masked("ref.dataset_iri")
}

// MaskOut_Ref_Branch append Ref.Branch into
// ListRefsRequest.ReadMask.
func (x *ListRefsRequest) MaskOut_Ref_Branch() *ListRefsRequest {
	if x.ReadMask == nil {
		x.ReadMask = new(fieldmaskpb.FieldMask)
	}
	x.ReadMask.Append(_fm_Ref, "ref.branch")

	return x
}

// MaskedOut_Ref_Branch indicates the field ListRefsRequest.Branch
// exists in the ListRefsRequest.ReadMask or not.
func (x *ListRefsRequest_FieldMask) MaskedOut_Ref_Branch() bool {
	if x.mask == nil {
		return true
	}

	return x.mask.Masked("ref.branch")
}

// MaskOut_Ref_Leaf append Ref.Leaf into
// ListRefsRequest.ReadMask.
func (x *ListRefsRequest) MaskOut_Ref_Leaf() *ListRefsRequest {
	if x.ReadMask == nil {
		x.ReadMask = new(fieldmaskpb.FieldMask)
	}
	x.ReadMask.Append(_fm_Ref, "ref.leaf")

	return x
}

// MaskedOut_Ref_Leaf indicates the field ListRefsRequest.Leaf
// exists in the ListRefsRequest.ReadMask or not.
func (x *ListRefsRequest_FieldMask) MaskedOut_Ref_Leaf() bool {
	if x.mask == nil {
		return true
	}

	return x.mask.Masked("ref.leaf")
}

// MaskOut_CommitId append Ref.CommitId into
// ListRefsRequest.ReadMask.
func (x *ListRefsRequest) MaskOut_CommitId() *ListRefsRequest {
	if x.ReadMask == nil {
		x.ReadMask = new(fieldmaskpb.FieldMask)
	}
	x.ReadMask.Append(_fm_Ref, "commit_id")

	return x
}

// MaskedOut_CommitId indicates the field ListRefsRequest.CommitId
// exists in the ListRefsRequest.ReadMask or not.
func (x *ListRefsRequest_FieldMask) MaskedOut_CommitId() bool {
	if x.mask == nil {
		return true
	}

	return x.mask.Masked("commit_id")
}

// Mask only affects the fields in the ListRefsRequest.
func (x *ListRefsRequest_FieldMask) Mask(m *Ref) *Ref {
	switch x.maskMode {
	case pbfieldmask.MaskMode_Filter:
		x.mask.Filter(m)
	case pbfieldmask.MaskMode_Prune:
		x.mask.Prune(m)
	}

	return m
}

func (x *GetRefRequest) fieldMaskWithMode(mode pbfieldmask.MaskMode) *GetRefRequest_FieldMask {
	fm := &GetRefRequest_FieldMask{
		maskMode: mode,
		mask:     pbfieldmask.New(x.ReadMask),
	}

	return fm
}

// FieldMask_Filter generates *GetRefRequest_FieldMask with filter mode, so that
// only the fields in the GetRefRequest.ReadMask will be
// appended into the GetRefRequest.
func (x *GetRefRequest) FieldMask_Filter() *GetRefRequest_FieldMask {
	return x.fieldMaskWithMode(pbfieldmask.MaskMode_Filter)
}

// FieldMask_Prune generates *GetRefRequest_FieldMask with prune mode, so that
// only the fields NOT in the GetRefRequest.ReadMask will be
// appended into the GetRefRequest.
func (x *GetRefRequest) FieldMask_Prune() *GetRefRequest_FieldMask {
	return x.fieldMaskWithMode(pbfieldmask.MaskMode_Prune)
}

// GetRefRequest_FieldMask provide provide helper functions to deal with FieldMask.
type GetRefRequest_FieldMask struct {
	maskMode pbfieldmask.MaskMode
	mask     pbfieldmask.NestedFieldMask
}

// MaskOut_Ref append Ref.Ref into
// GetRefRequest.ReadMask.
func (x *GetRefRequest) MaskOut_Ref() *GetRefRequest {
	if x.ReadMask == nil {
		x.ReadMask = new(fieldmaskpb.FieldMask)
	}
	x.ReadMask.Append(_fm_Ref, "ref")

	return x
}

// MaskedOut_Ref indicates the field GetRefRequest.Ref
// exists in the GetRefRequest.ReadMask or not.
func (x *GetRefRequest_FieldMask) MaskedOut_Ref() bool {
	if x.mask == nil {
		return true
	}

	return x.mask.Masked("ref")
}

// MaskOut_Ref_DatasetUuid append Ref.DatasetUuid into
// GetRefRequest.ReadMask.
func (x *GetRefRequest) MaskOut_Ref_DatasetUuid() *GetRefRequest {
	if x.ReadMask == nil {
		x.ReadMask = new(fieldmaskpb.FieldMask)
	}
	x.ReadMask.Append(_fm_Ref, "ref.dataset_uuid")

	return x
}

// MaskedOut_Ref_DatasetUuid indicates the field GetRefRequest.DatasetUuid
// exists in the GetRefRequest.ReadMask or not.
func (x *GetRefRequest_FieldMask) MaskedOut_Ref_DatasetUuid() bool {
	if x.mask == nil {
		return true
	}

	return x.mask.Masked("ref.dataset_uuid")
}

// MaskOut_Ref_DatasetIri append Ref.DatasetIri into
// GetRefRequest.ReadMask.
func (x *GetRefRequest) MaskOut_Ref_DatasetIri() *GetRefRequest {
	if x.ReadMask == nil {
		x.ReadMask = new(fieldmaskpb.FieldMask)
	}
	x.ReadMask.Append(_fm_Ref, "ref.dataset_iri")

	return x
}

// MaskedOut_Ref_DatasetIri indicates the field GetRefRequest.DatasetIri
// exists in the GetRefRequest.ReadMask or not.
func (x *GetRefRequest_FieldMask) MaskedOut_Ref_DatasetIri() bool {
	if x.mask == nil {
		return true
	}

	return x.mask.Masked("ref.dataset_iri")
}

// MaskOut_Ref_Branch append Ref.Branch into
// GetRefRequest.ReadMask.
func (x *GetRefRequest) MaskOut_Ref_Branch() *GetRefRequest {
	if x.ReadMask == nil {
		x.ReadMask = new(fieldmaskpb.FieldMask)
	}
	x.ReadMask.Append(_fm_Ref, "ref.branch")

	return x
}

// MaskedOut_Ref_Branch indicates the field GetRefRequest.Branch
// exists in the GetRefRequest.ReadMask or not.
func (x *GetRefRequest_FieldMask) MaskedOut_Ref_Branch() bool {
	if x.mask == nil {
		return true
	}

	return x.mask.Masked("ref.branch")
}

// MaskOut_Ref_Leaf append Ref.Leaf into
// GetRefRequest.ReadMask.
func (x *GetRefRequest) MaskOut_Ref_Leaf() *GetRefRequest {
	if x.ReadMask == nil {
		x.ReadMask = new(fieldmaskpb.FieldMask)
	}
	x.ReadMask.Append(_fm_Ref, "ref.leaf")

	return x
}

// MaskedOut_Ref_Leaf indicates the field GetRefRequest.Leaf
// exists in the GetRefRequest.ReadMask or not.
func (x *GetRefRequest_FieldMask) MaskedOut_Ref_Leaf() bool {
	if x.mask == nil {
		return true
	}

	return x.mask.Masked("ref.leaf")
}

// MaskOut_CommitId append Ref.CommitId into
// GetRefRequest.ReadMask.
func (x *GetRefRequest) MaskOut_CommitId() *GetRefRequest {
	if x.ReadMask == nil {
		x.ReadMask = new(fieldmaskpb.FieldMask)
	}
	x.ReadMask.Append(_fm_Ref, "commit_id")

	return x
}

// MaskedOut_CommitId indicates the field GetRefRequest.CommitId
// exists in the GetRefRequest.ReadMask or not.
func (x *GetRefRequest_FieldMask) MaskedOut_CommitId() bool {
	if x.mask == nil {
		return true
	}

	return x.mask.Masked("commit_id")
}

// Mask only affects the fields in the GetRefRequest.
func (x *GetRefRequest_FieldMask) Mask(m *Ref) *Ref {
	switch x.maskMode {
	case pbfieldmask.MaskMode_Filter:
		x.mask.Filter(m)
	case pbfieldmask.MaskMode_Prune:
		x.mask.Prune(m)
	}

	return m
}

func (x *ListCommitsRequest) fieldMaskWithMode(mode pbfieldmask.MaskMode) *ListCommitsRequest_FieldMask {
	fm := &ListCommitsRequest_FieldMask{
		maskMode: mode,
		mask:     pbfieldmask.New(x.ReadMask),
	}

	return fm
}

// FieldMask_Filter generates *ListCommitsRequest_FieldMask with filter mode, so that
// only the fields in the ListCommitsRequest.ReadMask will be
// appended into the ListCommitsRequest.
func (x *ListCommitsRequest) FieldMask_Filter() *ListCommitsRequest_FieldMask {
	return x.fieldMaskWithMode(pbfieldmask.MaskMode_Filter)
}

// FieldMask_Prune generates *ListCommitsRequest_FieldMask with prune mode, so that
// only the fields NOT in the ListCommitsRequest.ReadMask will be
// appended into the ListCommitsRequest.
func (x *ListCommitsRequest) FieldMask_Prune() *ListCommitsRequest_FieldMask {
	return x.fieldMaskWithMode(pbfieldmask.MaskMode_Prune)
}

// ListCommitsRequest_FieldMask provide provide helper functions to deal with FieldMask.
type ListCommitsRequest_FieldMask struct {
	maskMode pbfieldmask.MaskMode
	mask     pbfieldmask.NestedFieldMask
}

// _fm_Commit is built in variable for Commit to call FieldMask.Append
var _fm_Commit = new(Commit)

// MaskOut_CommitId append Commit.CommitId into
// ListCommitsRequest.ReadMask.
func (x *ListCommitsRequest) MaskOut_CommitId() *ListCommitsRequest {
	if x.ReadMask == nil {
		x.ReadMask = new(fieldmaskpb.FieldMask)
	}
	x.ReadMask.Append(_fm_Commit, "commit_id")

	return x
}

// MaskedOut_CommitId indicates the field ListCommitsRequest.CommitId
// exists in the ListCommitsRequest.ReadMask or not.
func (x *ListCommitsRequest_FieldMask) MaskedOut_CommitId() bool {
	if x.mask == nil {
		return true
	}

	return x.mask.Masked("commit_id")
}

// MaskOut_Datasets append Commit.Datasets into
// ListCommitsRequest.ReadMask.
func (x *ListCommitsRequest) MaskOut_Datasets() *ListCommitsRequest {
	if x.ReadMask == nil {
		x.ReadMask = new(fieldmaskpb.FieldMask)
	}
	x.ReadMask.Append(_fm_Commit, "datasets")

	return x
}

// MaskedOut_Datasets indicates the field ListCommitsRequest.Datasets
// exists in the ListCommitsRequest.ReadMask or not.
func (x *ListCommitsRequest_FieldMask) MaskedOut_Datasets() bool {
	if x.mask == nil {
		return true
	}

	return x.mask.Masked("datasets")
}

// MaskOut_NamedGraphs append Commit.NamedGraphs into
// ListCommitsRequest.ReadMask.
func (x *ListCommitsRequest) MaskOut_NamedGraphs() *ListCommitsRequest {
	if x.ReadMask == nil {
		x.ReadMask = new(fieldmaskpb.FieldMask)
	}
	x.ReadMask.Append(_fm_Commit, "namedGraphs")

	return x
}

// MaskedOut_NamedGraphs indicates the field ListCommitsRequest.NamedGraphs
// exists in the ListCommitsRequest.ReadMask or not.
func (x *ListCommitsRequest_FieldMask) MaskedOut_NamedGraphs() bool {
	if x.mask == nil {
		return true
	}

	return x.mask.Masked("namedGraphs")
}

// MaskOut_AuthorUri append Commit.AuthorUri into
// ListCommitsRequest.ReadMask.
func (x *ListCommitsRequest) MaskOut_AuthorUri() *ListCommitsRequest {
	if x.ReadMask == nil {
		x.ReadMask = new(fieldmaskpb.FieldMask)
	}
	x.ReadMask.Append(_fm_Commit, "author_uri")

	return x
}

// MaskedOut_AuthorUri indicates the field ListCommitsRequest.AuthorUri
// exists in the ListCommitsRequest.ReadMask or not.
func (x *ListCommitsRequest_FieldMask) MaskedOut_AuthorUri() bool {
	if x.mask == nil {
		return true
	}

	return x.mask.Masked("author_uri")
}

// MaskOut_AuthorTimestamp append Commit.AuthorTimestamp into
// ListCommitsRequest.ReadMask.
func (x *ListCommitsRequest) MaskOut_AuthorTimestamp() *ListCommitsRequest {
	if x.ReadMask == nil {
		x.ReadMask = new(fieldmaskpb.FieldMask)
	}
	x.ReadMask.Append(_fm_Commit, "author_timestamp")

	return x
}

// MaskedOut_AuthorTimestamp indicates the field ListCommitsRequest.AuthorTimestamp
// exists in the ListCommitsRequest.ReadMask or not.
func (x *ListCommitsRequest_FieldMask) MaskedOut_AuthorTimestamp() bool {
	if x.mask == nil {
		return true
	}

	return x.mask.Masked("author_timestamp")
}

// MaskOut_AuthorTimestamp_Seconds append Commit.Seconds into
// ListCommitsRequest.ReadMask.
func (x *ListCommitsRequest) MaskOut_AuthorTimestamp_Seconds() *ListCommitsRequest {
	if x.ReadMask == nil {
		x.ReadMask = new(fieldmaskpb.FieldMask)
	}
	x.ReadMask.Append(_fm_Commit, "author_timestamp.seconds")

	return x
}

// MaskedOut_AuthorTimestamp_Seconds indicates the field ListCommitsRequest.Seconds
// exists in the ListCommitsRequest.ReadMask or not.
func (x *ListCommitsRequest_FieldMask) MaskedOut_AuthorTimestamp_Seconds() bool {
	if x.mask == nil {
		return true
	}

	return x.mask.Masked("author_timestamp.seconds")
}

// MaskOut_AuthorTimestamp_Nanos append Commit.Nanos into
// ListCommitsRequest.ReadMask.
func (x *ListCommitsRequest) MaskOut_AuthorTimestamp_Nanos() *ListCommitsRequest {
	if x.ReadMask == nil {
		x.ReadMask = new(fieldmaskpb.FieldMask)
	}
	x.ReadMask.Append(_fm_Commit, "author_timestamp.nanos")

	return x
}

// MaskedOut_AuthorTimestamp_Nanos indicates the field ListCommitsRequest.Nanos
// exists in the ListCommitsRequest.ReadMask or not.
func (x *ListCommitsRequest_FieldMask) MaskedOut_AuthorTimestamp_Nanos() bool {
	if x.mask == nil {
		return true
	}

	return x.mask.Masked("author_timestamp.nanos")
}

// MaskOut_Message append Commit.Message into
// ListCommitsRequest.ReadMask.
func (x *ListCommitsRequest) MaskOut_Message() *ListCommitsRequest {
	if x.ReadMask == nil {
		x.ReadMask = new(fieldmaskpb.FieldMask)
	}
	x.ReadMask.Append(_fm_Commit, "message")

	return x
}

// MaskedOut_Message indicates the field ListCommitsRequest.Message
// exists in the ListCommitsRequest.ReadMask or not.
func (x *ListCommitsRequest_FieldMask) MaskedOut_Message() bool {
	if x.mask == nil {
		return true
	}

	return x.mask.Masked("message")
}

// MaskOut_Reason append Commit.Reason into
// ListCommitsRequest.ReadMask.
func (x *ListCommitsRequest) MaskOut_Reason() *ListCommitsRequest {
	if x.ReadMask == nil {
		x.ReadMask = new(fieldmaskpb.FieldMask)
	}
	x.ReadMask.Append(_fm_Commit, "reason")

	return x
}

// MaskedOut_Reason indicates the field ListCommitsRequest.Reason
// exists in the ListCommitsRequest.ReadMask or not.
func (x *ListCommitsRequest_FieldMask) MaskedOut_Reason() bool {
	if x.mask == nil {
		return true
	}

	return x.mask.Masked("reason")
}

// Mask only affects the fields in the ListCommitsRequest.
func (x *ListCommitsRequest_FieldMask) Mask(m *Commit) *Commit {
	switch x.maskMode {
	case pbfieldmask.MaskMode_Filter:
		x.mask.Filter(m)
	case pbfieldmask.MaskMode_Prune:
		x.mask.Prune(m)
	}

	return m
}

func (x *GetCommitRequest) fieldMaskWithMode(mode pbfieldmask.MaskMode) *GetCommitRequest_FieldMask {
	fm := &GetCommitRequest_FieldMask{
		maskMode: mode,
		mask:     pbfieldmask.New(x.ReadMask),
	}

	return fm
}

// FieldMask_Filter generates *GetCommitRequest_FieldMask with filter mode, so that
// only the fields in the GetCommitRequest.ReadMask will be
// appended into the GetCommitRequest.
func (x *GetCommitRequest) FieldMask_Filter() *GetCommitRequest_FieldMask {
	return x.fieldMaskWithMode(pbfieldmask.MaskMode_Filter)
}

// FieldMask_Prune generates *GetCommitRequest_FieldMask with prune mode, so that
// only the fields NOT in the GetCommitRequest.ReadMask will be
// appended into the GetCommitRequest.
func (x *GetCommitRequest) FieldMask_Prune() *GetCommitRequest_FieldMask {
	return x.fieldMaskWithMode(pbfieldmask.MaskMode_Prune)
}

// GetCommitRequest_FieldMask provide provide helper functions to deal with FieldMask.
type GetCommitRequest_FieldMask struct {
	maskMode pbfieldmask.MaskMode
	mask     pbfieldmask.NestedFieldMask
}

// MaskOut_CommitId append Commit.CommitId into
// GetCommitRequest.ReadMask.
func (x *GetCommitRequest) MaskOut_CommitId() *GetCommitRequest {
	if x.ReadMask == nil {
		x.ReadMask = new(fieldmaskpb.FieldMask)
	}
	x.ReadMask.Append(_fm_Commit, "commit_id")

	return x
}

// MaskedOut_CommitId indicates the field GetCommitRequest.CommitId
// exists in the GetCommitRequest.ReadMask or not.
func (x *GetCommitRequest_FieldMask) MaskedOut_CommitId() bool {
	if x.mask == nil {
		return true
	}

	return x.mask.Masked("commit_id")
}

// MaskOut_Datasets append Commit.Datasets into
// GetCommitRequest.ReadMask.
func (x *GetCommitRequest) MaskOut_Datasets() *GetCommitRequest {
	if x.ReadMask == nil {
		x.ReadMask = new(fieldmaskpb.FieldMask)
	}
	x.ReadMask.Append(_fm_Commit, "datasets")

	return x
}

// MaskedOut_Datasets indicates the field GetCommitRequest.Datasets
// exists in the GetCommitRequest.ReadMask or not.
func (x *GetCommitRequest_FieldMask) MaskedOut_Datasets() bool {
	if x.mask == nil {
		return true
	}

	return x.mask.Masked("datasets")
}

// MaskOut_NamedGraphs append Commit.NamedGraphs into
// GetCommitRequest.ReadMask.
func (x *GetCommitRequest) MaskOut_NamedGraphs() *GetCommitRequest {
	if x.ReadMask == nil {
		x.ReadMask = new(fieldmaskpb.FieldMask)
	}
	x.ReadMask.Append(_fm_Commit, "namedGraphs")

	return x
}

// MaskedOut_NamedGraphs indicates the field GetCommitRequest.NamedGraphs
// exists in the GetCommitRequest.ReadMask or not.
func (x *GetCommitRequest_FieldMask) MaskedOut_NamedGraphs() bool {
	if x.mask == nil {
		return true
	}

	return x.mask.Masked("namedGraphs")
}

// MaskOut_AuthorUri append Commit.AuthorUri into
// GetCommitRequest.ReadMask.
func (x *GetCommitRequest) MaskOut_AuthorUri() *GetCommitRequest {
	if x.ReadMask == nil {
		x.ReadMask = new(fieldmaskpb.FieldMask)
	}
	x.ReadMask.Append(_fm_Commit, "author_uri")

	return x
}

// MaskedOut_AuthorUri indicates the field GetCommitRequest.AuthorUri
// exists in the GetCommitRequest.ReadMask or not.
func (x *GetCommitRequest_FieldMask) MaskedOut_AuthorUri() bool {
	if x.mask == nil {
		return true
	}

	return x.mask.Masked("author_uri")
}

// MaskOut_AuthorTimestamp append Commit.AuthorTimestamp into
// GetCommitRequest.ReadMask.
func (x *GetCommitRequest) MaskOut_AuthorTimestamp() *GetCommitRequest {
	if x.ReadMask == nil {
		x.ReadMask = new(fieldmaskpb.FieldMask)
	}
	x.ReadMask.Append(_fm_Commit, "author_timestamp")

	return x
}

// MaskedOut_AuthorTimestamp indicates the field GetCommitRequest.AuthorTimestamp
// exists in the GetCommitRequest.ReadMask or not.
func (x *GetCommitRequest_FieldMask) MaskedOut_AuthorTimestamp() bool {
	if x.mask == nil {
		return true
	}

	return x.mask.Masked("author_timestamp")
}

// MaskOut_AuthorTimestamp_Seconds append Commit.Seconds into
// GetCommitRequest.ReadMask.
func (x *GetCommitRequest) MaskOut_AuthorTimestamp_Seconds() *GetCommitRequest {
	if x.ReadMask == nil {
		x.ReadMask = new(fieldmaskpb.FieldMask)
	}
	x.ReadMask.Append(_fm_Commit, "author_timestamp.seconds")

	return x
}

// MaskedOut_AuthorTimestamp_Seconds indicates the field GetCommitRequest.Seconds
// exists in the GetCommitRequest.ReadMask or not.
func (x *GetCommitRequest_FieldMask) MaskedOut_AuthorTimestamp_Seconds() bool {
	if x.mask == nil {
		return true
	}

	return x.mask.Masked("author_timestamp.seconds")
}

// MaskOut_AuthorTimestamp_Nanos append Commit.Nanos into
// GetCommitRequest.ReadMask.
func (x *GetCommitRequest) MaskOut_AuthorTimestamp_Nanos() *GetCommitRequest {
	if x.ReadMask == nil {
		x.ReadMask = new(fieldmaskpb.FieldMask)
	}
	x.ReadMask.Append(_fm_Commit, "author_timestamp.nanos")

	return x
}

// MaskedOut_AuthorTimestamp_Nanos indicates the field GetCommitRequest.Nanos
// exists in the GetCommitRequest.ReadMask or not.
func (x *GetCommitRequest_FieldMask) MaskedOut_AuthorTimestamp_Nanos() bool {
	if x.mask == nil {
		return true
	}

	return x.mask.Masked("author_timestamp.nanos")
}

// MaskOut_Message append Commit.Message into
// GetCommitRequest.ReadMask.
func (x *GetCommitRequest) MaskOut_Message() *GetCommitRequest {
	if x.ReadMask == nil {
		x.ReadMask = new(fieldmaskpb.FieldMask)
	}
	x.ReadMask.Append(_fm_Commit, "message")

	return x
}

// MaskedOut_Message indicates the field GetCommitRequest.Message
// exists in the GetCommitRequest.ReadMask or not.
func (x *GetCommitRequest_FieldMask) MaskedOut_Message() bool {
	if x.mask == nil {
		return true
	}

	return x.mask.Masked("message")
}

// MaskOut_Reason append Commit.Reason into
// GetCommitRequest.ReadMask.
func (x *GetCommitRequest) MaskOut_Reason() *GetCommitRequest {
	if x.ReadMask == nil {
		x.ReadMask = new(fieldmaskpb.FieldMask)
	}
	x.ReadMask.Append(_fm_Commit, "reason")

	return x
}

// MaskedOut_Reason indicates the field GetCommitRequest.Reason
// exists in the GetCommitRequest.ReadMask or not.
func (x *GetCommitRequest_FieldMask) MaskedOut_Reason() bool {
	if x.mask == nil {
		return true
	}

	return x.mask.Masked("reason")
}

// Mask only affects the fields in the GetCommitRequest.
func (x *GetCommitRequest_FieldMask) Mask(m *Commit) *Commit {
	switch x.maskMode {
	case pbfieldmask.MaskMode_Filter:
		x.mask.Filter(m)
	case pbfieldmask.MaskMode_Prune:
		x.mask.Prune(m)
	}

	return m
}
