// Code generated by tools/compiler/compiler.go DO NOT EDIT.

// Copyright Semantic STEP Technology GmbH, Germany & DCT Co., Ltd. Tianjin, China

package rdfs

import (
	"reflect"
	"git.semanticstep.net/x/sst/sst"
	"git.semanticstep.net/x/sst/vocabularies/rdf"
)

type pkg struct{ sst.ElementInfo }

var RDFSVocabulary = sst.Vocabulary{BaseIRI: "http://www.w3.org/2000/01/rdf-schema"}

var (
	PKG = sst.ElementPkg(pkg{})
	_   = PKG
)

// Definitions of rdfs.Class

type IsClass interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Class()
}

type KindClass interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Class()
}

type classI struct{ sst.ElementInfo }

func (classI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Class()      {}
func (classI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Class()    {}
func (classI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource() {}

var classKindInterface reflect.Type

var Class = classI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: RDFSVocabulary, Name: "Class"},
	ASubtypeOf:        []sst.ElementInformer{Resource},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of rdfs.Container

type IsContainer interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Container()
}

type KindContainer interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Container()
}

type containerI struct{ sst.ElementInfo }

func (containerI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Container()   {}
func (containerI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Container() {}
func (containerI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()  {}

var containerKindInterface reflect.Type

var Container = containerI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: RDFSVocabulary, Name: "Container"},
	ASubtypeOf:        []sst.ElementInformer{Resource},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of rdfs.ContainerMembershipProperty

type IsContainerMembershipProperty interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23ContainerMembershipProperty()
}

type KindContainerMembershipProperty interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23ContainerMembershipProperty()
}

type containerMembershipPropertyI struct{ sst.ElementInfo }

func (containerMembershipPropertyI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23ContainerMembershipProperty()   {}
func (containerMembershipPropertyI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F1999_2F02_2F22_2Drdf_2Dsyntax_2Dns_23Property()          {}
func (containerMembershipPropertyI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23ContainerMembershipProperty() {}
func (containerMembershipPropertyI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()                    {}

var containerMembershipPropertyKindInterface reflect.Type

var ContainerMembershipProperty = containerMembershipPropertyI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: RDFSVocabulary, Name: "ContainerMembershipProperty"},
	ASubtypeOf:        []sst.ElementInformer{rdf.Property},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of rdfs.Datatype

type IsDatatype interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Datatype()
}

type KindDatatype interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Datatype()
}

type datatypeI struct{ sst.ElementInfo }

func (datatypeI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Datatype()   {}
func (datatypeI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Class()    {}
func (datatypeI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Datatype() {}
func (datatypeI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource() {}

var datatypeKindInterface reflect.Type

var Datatype = datatypeI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: RDFSVocabulary, Name: "Datatype"},
	ASubtypeOf:        []sst.ElementInformer{Class},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of rdfs.Literal

type IsLiteral interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Literal()
}

type KindLiteral interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Literal()
}

type literalI struct{ sst.ElementInfo }

func (literalI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Literal()    {}
func (literalI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Literal()  {}
func (literalI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource() {}

var literalKindInterface reflect.Type

var Literal = literalI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: RDFSVocabulary, Name: "Literal"},
	ASubtypeOf:        []sst.ElementInformer{Resource},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of rdfs.Resource

type IsResource interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()
}

type KindResource interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()
}

type resourceI struct{ sst.ElementInfo }

func (resourceI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()   {}
func (resourceI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource() {}

var resourceKindInterface reflect.Type

var Resource = resourceI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: RDFSVocabulary, Name: "Resource"},

	AClass: true, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: false, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of rdfs.comment

type IsComment interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23comment()
}

type KindComment interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23comment()
}

type commentI struct{ sst.ElementInfo }

func (commentI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23comment()    {}
func (commentI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource() {}
func (commentI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23comment()  {}

var commentKindInterface reflect.Type

var Comment = commentI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: RDFSVocabulary, Name: "comment"},
	ADomain:           Resource,
	ARange:            Literal,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of rdfs.domain

type IsDomain interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23domain()
}

type KindDomain interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23domain()
}

type domainI struct{ sst.ElementInfo }

func (domainI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23domain()     {}
func (domainI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource() {}
func (domainI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23domain()   {}

var domainKindInterface reflect.Type

var Domain = domainI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: RDFSVocabulary, Name: "domain"},
	ADomain:           rdf.Property,
	ARange:            Class,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of rdfs.isDefinedBy

type IsIsDefinedBy interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23isDefinedBy()
}

type KindIsDefinedBy interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23isDefinedBy()
}

type isDefinedByI struct{ sst.ElementInfo }

func (isDefinedByI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23isDefinedBy()   {}
func (isDefinedByI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()    {}
func (isDefinedByI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23isDefinedBy() {}
func (isDefinedByI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23seeAlso()     {}

var isDefinedByKindInterface reflect.Type

var IsDefinedBy = isDefinedByI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: RDFSVocabulary, Name: "isDefinedBy"},
	ADomain:           Resource,
	ARange:            Resource,
	ASubPropertyOf:    SeeAlso,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of rdfs.label

type IsLabel interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23label()
}

type KindLabel interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23label()
}

type labelI struct{ sst.ElementInfo }

func (labelI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23label()      {}
func (labelI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource() {}
func (labelI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23label()    {}

var labelKindInterface reflect.Type

var Label = labelI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: RDFSVocabulary, Name: "label"},
	ADomain:           Resource,
	ARange:            Literal,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of rdfs.member

type IsMember interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23member()
}

type KindMember interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23member()
}

type memberI struct{ sst.ElementInfo }

func (memberI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23member()     {}
func (memberI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource() {}
func (memberI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23member()   {}

var memberKindInterface reflect.Type

var Member = memberI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: RDFSVocabulary, Name: "member"},
	ADomain:           Resource,
	ARange:            Resource,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of rdfs.range

type IsRange interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23range()
}

type KindRange interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23range()
}

type rangeI struct{ sst.ElementInfo }

func (rangeI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23range()      {}
func (rangeI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource() {}
func (rangeI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23range()    {}

var rangeKindInterface reflect.Type

var Range = rangeI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: RDFSVocabulary, Name: "range"},
	ADomain:           rdf.Property,
	ARange:            Class,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of rdfs.seeAlso

type IsSeeAlso interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23seeAlso()
}

type KindSeeAlso interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23seeAlso()
}

type seeAlsoI struct{ sst.ElementInfo }

func (seeAlsoI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23seeAlso()    {}
func (seeAlsoI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource() {}
func (seeAlsoI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23seeAlso()  {}

var seeAlsoKindInterface reflect.Type

var SeeAlso = seeAlsoI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: RDFSVocabulary, Name: "seeAlso"},
	ADomain:           Resource,
	ARange:            Resource,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of rdfs.subClassOf

type IsSubClassOf interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23subClassOf()
}

type KindSubClassOf interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23subClassOf()
}

type subClassOfI struct{ sst.ElementInfo }

func (subClassOfI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23subClassOf()   {}
func (subClassOfI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()   {}
func (subClassOfI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23subClassOf() {}

var subClassOfKindInterface reflect.Type

var SubClassOf = subClassOfI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: RDFSVocabulary, Name: "subClassOf"},
	ADomain:           Class,
	ARange:            Class,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}

// Definitions of rdfs.subPropertyOf

type IsSubPropertyOf interface {
	sst.ElementInformer
	AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23subPropertyOf()
}

type KindSubPropertyOf interface {
	sst.ElementInformer
	AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23subPropertyOf()
}

type subPropertyOfI struct{ sst.ElementInfo }

func (subPropertyOfI) AsIs_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23subPropertyOf()   {}
func (subPropertyOfI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23Resource()      {}
func (subPropertyOfI) AsKind_http_3A_2F_2Fwww_2Ew3_2Eorg_2F2000_2F01_2Frdf_2Dschema_23subPropertyOf() {}

var subPropertyOfKindInterface reflect.Type

var SubPropertyOf = subPropertyOfI{sst.ElementInfo{
	Element: sst.Element{Vocabulary: RDFSVocabulary, Name: "subPropertyOf"},
	ADomain:           rdf.Property,
	ARange:            rdf.Property,

	AClass: false, AnOptionClass: false, AnAbstractClass: false, ARootClass: false,
	AProperty: true, ADatatypeProperty: false, AnObjectProperty: false, 
	ADatatype: false, AnIndividual: false,
}}
